Repository google/exposure-notifications-verification-server, pull requests merged in 2020-08, with the labels that each got.

#162 Fix PK constraint on users table on realm upgrade.
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/XS

#163 Issue160
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/services.tf
  terraform/sessions.tf
  terraform/sms.tf
Labels: approved, cla: yes, lgtm, size/L

#168 Allow Cloud Run to be managed by both Terraform and our deployment scripts
  builders/deploy.yaml
  builders/migrate.yaml
  builders/promote.yaml
  scripts/deploy
  terraform/csrf.tf
  terraform/database.tf
  terraform/main.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_server.tf
  terraform/services.tf
  terraform/sessions.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#167 Add command line tool to run the whole flow
  cmd/get-certificate/main.go
  cmd/get-code/main.go
  cmd/get-token/main.go
  go.mod
  go.sum
  pkg/clients/apis.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/L

#169 Support custom domain mappings
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#170 Add contexts to clients packages
  .gitignore
  cmd/get-certificate/main.go
  cmd/get-code/main.go
  cmd/get-token/main.go
  pkg/clients/apis.go
  pkg/jsonclient/client.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/M

#171 Switch to gorilla sessions and flash
  cmd/add-sms-config/main.go
  cmd/add-users/main.go
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/assets/500.html
  cmd/server/assets/apikeys.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/index.html
  cmd/server/assets/realm.html
  cmd/server/assets/select-realm.html
  cmd/server/assets/signout.html
  cmd/server/assets/users.html
  cmd/server/main.go
  pkg/controller/apikey/create.go
  pkg/controller/apikey/index.go
  pkg/controller/certapi/certificate.go
  pkg/controller/context.go
  pkg/controller/controller.go
  pkg/controller/csrf/csrf.go
  pkg/controller/csrf/error.go
  pkg/controller/csrfapi/csrfapi.go
  pkg/controller/csrfapi/issue.go
  pkg/controller/flash.go
  pkg/controller/flash/flash.go
  pkg/controller/home/home.go
  pkg/controller/index/index.go
  pkg/controller/issueapi/issue.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/csrf.go
  pkg/controller/middleware/realm.go
  pkg/controller/middleware/sessions.go
  pkg/controller/middleware/template.go
  pkg/controller/realm/index.go
  pkg/controller/realm/realm.go
  pkg/controller/realm/select.go
  pkg/controller/realmadmin/index.go
  pkg/controller/realmadmin/save.go
  pkg/controller/session.go
  pkg/controller/session/create.go
  pkg/controller/session/delete.go
  pkg/controller/session/session.go
  pkg/controller/user/create.go
  pkg/controller/user/delete.go
  pkg/controller/user/index.go
  pkg/controller/verifyapi/verify.go
  pkg/database/authorized_app.go
  pkg/database/realm.go
  pkg/render/html.go
  pkg/render/json.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/XXL

#173 Docker updates
  .dockerignore
  Dockerfile
Labels: approved, cla: yes, lgtm, size/S

#174 Initial cloud build for auto building of all images
  cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/M

#172 Drop disabled users
  cmd/add-users/main.go
  pkg/config/cleanup_server_config.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/middleware/auth.go
  pkg/controller/user/create.go
  pkg/database/migrations.go
  pkg/database/user.go
  pkg/database/user_test.go
Labels: approved, cla: yes, lgtm, size/L

#175 Add cloudrun_location to Terraform variables
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#178 Mobile-friendly changes
  cmd/server/assets/apikeys.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/realm.html
  cmd/server/assets/select-realm.html
  cmd/server/assets/signout.html
  cmd/server/assets/users.html
  cmd/server/main.go
  pkg/controller/csrfapi/csrfapi.go
  pkg/controller/csrfapi/issue.go
  pkg/controller/issueapi/issue.go
  pkg/controller/realm/index.go
  pkg/controller/realm/select.go
  pkg/controller/session/delete.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#177 add pull request template to capture release notes
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/S

#179 Update verification for v1 API on en server.
  go.mod
  go.sum
  pkg/controller/certapi/certapi.go
  pkg/controller/certapi/certificate.go
  pkg/controller/verifyapi/verify.go
  pkg/risk/calculator.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/L

#181 update db debug flag default
  pkg/database/config.go
Labels: approved, cla: yes, lgtm, size/XS

#182 Update README.md
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#187 Certificate issue API doesn't need an active session.
  pkg/controller/certapi/certificate.go
Labels: approved, cla: yes, lgtm, size/XS

#188 Add icco to owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#189 Cherrypick bug fix back to release2 branch
  pkg/controller/certapi/certificate.go
Labels: approved, cla: yes, lgtm, size/XS

#191 Always reset the buffer before rendering
  pkg/render/html.go
  pkg/render/json.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/XS

#193 Fix cloudbuild and Docker optimizations
  Dockerfile
  cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/S

#195 Allow customizing database backup location
  terraform/database.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#190 Add KMS<->DB abstraction
  builders/migrate.yaml
  cmd/add-sms-config/main.go
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/realm.html
  go.mod
  go.sum
  pkg/controller/home/home.go
  pkg/controller/issueapi/issue.go
  pkg/controller/realmadmin/save.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/database_util.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/sms_config.go
  pkg/database/sms_config_test.go
  pkg/database/user.go
  scripts/dev
  scripts/migrate
  terraform/database.tf
  terraform/keys.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/XL

#197 Automate deploy in cloud build
  cloudbuild.yaml
Labels: approved, cla: yes, lgtm, size/M

#152 Add counts of codes generated to users and api key pages
  README.md
  cmd/add-users/main.go
  cmd/server/assets/apikeys.html
  cmd/server/assets/users.html
  pkg/controller/apikey/index.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/user/index.go
  pkg/database/authorized_app_stats.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/user_stats.go
  pkg/database/vercode.go
Labels: approved, cla: yes, lgtm, size/XL

#183 Add Observability configs to Verification servers
  README.md
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  go.mod
  pkg/config/admin_server_config.go
  pkg/config/api_server_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/server_config.go
  pkg/observability/config.go
  pkg/observability/generic.go
  pkg/observability/noop.go
  pkg/observability/observability.go
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/L

#196 Add a /healthz
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  go.mod
  pkg/controller/healthz.go
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/M

#203 Support a local encryption key
  README.md
  go.mod
  go.sum
  pkg/database/database.go
  pkg/database/database_util.go
Labels: approved, cla: yes, lgtm, size/L

#202 Update Terraform and migration scripts
  builders/migrate.yaml
  pkg/database/migrations.go
  scripts/migrate
  terraform/database.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/L

#204 Update envconfig
  README.md
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#205 Use main server o11y package
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/config/admin_server_config.go
  pkg/config/api_server_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/server_config.go
  pkg/observability/config.go
  pkg/observability/generic.go
  pkg/observability/noop.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/L

#207 Spelling Nits
  pkg/config/admin_server_config.go
  pkg/config/issue.go
  pkg/config/server_config.go
  pkg/controller/certapi/certapi.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/issueapi.go
Labels: approved, cla: yes, lgtm, size/S

#206 Switch to built-in base64-bytes helper
  pkg/config/server_config.go
  pkg/database/config.go
Labels: approved, cla: yes, lgtm, size/M

#212 Allow configuring the rate limiter to fail open
  go.mod
  go.sum
  pkg/ratelimit/config.go
Labels: approved, cla: yes, lgtm, size/S

#211 Update dev script with new default variables
  scripts/dev
Labels: approved, cla: yes, lgtm, size/S

#214 Unify on BadRequest
  README.md
  pkg/controller/issueapi/issue.go
  pkg/render/html.go
  pkg/render/json.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/M

#210 Switch to main server logger, always set a logger
  cmd/add-realm/main.go
  cmd/add-users/main.go
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/get-certificate/main.go
  cmd/get-code/main.go
  cmd/get-token/main.go
  cmd/migrate/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/controller/apikey/apikey.go
  pkg/controller/certapi/certapi.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/controller.go
  pkg/controller/home/home.go
  pkg/controller/index/index.go
  pkg/controller/issueapi/issueapi.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/csrf.go
  pkg/controller/middleware/method.go
  pkg/controller/middleware/realm.go
  pkg/controller/middleware/sessions.go
  pkg/controller/middleware/template.go
  pkg/controller/realm/realm.go
  pkg/controller/realmadmin/realmadmin.go
  pkg/controller/session/session.go
  pkg/controller/user/user.go
  pkg/controller/verifyapi/verify.go
  pkg/database/authorized_app_test.go
  pkg/database/migrations.go
  pkg/jsonclient/client.go
  pkg/logging/logging.go
  pkg/otp/code.go
  pkg/render/render.go
  tools/e2e-test/main.go
  tools/gen-secret/main.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#215 Emit ID for verification code
  pkg/api/api.go
  pkg/controller/issueapi/issue.go
  pkg/database/vercode.go
  pkg/otp/code.go
  pkg/otp/code_test.go
Labels: approved, cla: yes, lgtm, size/M

#217 Use database UUIDs
  pkg/controller/issueapi/issue.go
  pkg/database/migrations.go
  pkg/database/vercode.go
  pkg/otp/code.go
  pkg/otp/code_test.go
  pkg/render/render.go
  scripts/dev
Labels: approved, cla: yes, lgtm, size/M

#218 Update deployment/release with fixes
  builders/migrate.yaml
  cmd/migrate/main.go
  pkg/config/config.go
  pkg/database/migrations.go
  scripts/migrate
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/M

#221 Fix rate limiting
  Dockerfile
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/config/admin_server_config.go
Labels: approved, cla: yes, lgtm, size/L

#222 Add template functions stub
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/S

#225 Separate database config loading from connection opening
  cmd/add-realm/main.go
  cmd/add-users/main.go
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/migrate/main.go
  cmd/server/main.go
  pkg/controller/healthz.go
  pkg/database/database.go
  pkg/database/database_util.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#219 CheckCodeStatus API
  cmd/adminapi/main.go
  cmd/server/main.go
  pkg/api/api.go
  pkg/clients/apis.go
  pkg/controller/issueapi/codestatus.go
  pkg/controller/issueapi/issue.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/L

#230 Set encryption keys in initial Terraform migration
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/S

#238 Update package descriptions
  cmd/adminapi/main.go
  cmd/apiserver/main.go
Labels: approved, cla: yes, lgtm, size/XS

#237 Remove Chris from owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#239 fix inconssitency w/ errorCode vs error_code
  pkg/api/api.go
Labels: approved, cla: yes, lgtm, size/XS

#235 Include error in codestatus response
  pkg/api/api.go
  pkg/controller/issueapi/codestatus.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/M

#240 Add header middlware
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/csrf.go
  pkg/controller/middleware/header.go
  pkg/controller/middleware/method.go
  pkg/controller/middleware/realm.go
  pkg/controller/middleware/sessions.go
  pkg/controller/middleware/template.go
Labels: approved, cla: yes, lgtm, size/M

#236 Support symptom date and test date
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  pkg/api/api.go
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/L

#241 Support per-realm config of allowed test types
  cmd/get-code/main.go
  cmd/server/assets/home.html
  cmd/server/assets/realm.html
  pkg/clients/apis.go
  pkg/controller/index/index.go
  pkg/controller/issueapi/issue.go
  pkg/controller/realmadmin/index.go
  pkg/controller/realmadmin/save.go
  pkg/database/migrations.go
  pkg/database/realm.go
  tools/e2e-test/main.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#242 Fix the handler for checkcodestatus
  cmd/adminapi/main.go
Labels: approved, cla: yes, lgtm, size/XS

#243 Use case-insensitive uniqueness
  pkg/database/migrations.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/M

#244 Allow migrations to pass if a default realm already exists
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/XS

#245 Make Firebase URLs configurable
  README.md
  cmd/server/assets/index.html
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, size/S

#246 Allow configuring log debug mode
  cmd/add-realm/main.go
  cmd/add-users/main.go
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/client/main.go
  cmd/get-certificate/main.go
  cmd/get-code/main.go
  cmd/get-token/main.go
  cmd/migrate/main.go
  cmd/server/main.go
  tools/e2e-test/main.go
  tools/gen-secret/main.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#249 Add tracing to jsonclient
  go.mod
  pkg/jsonclient/client.go
Labels: approved, cla: yes, lgtm, size/S

#247 SMS Deep links and settings
  cmd/server/assets/header.html
  cmd/server/assets/realm.html
  pkg/config/admin_server_config.go
  pkg/config/issue.go
  pkg/config/server_config.go
  pkg/controller/home/home.go
  pkg/controller/issueapi/issue.go
  pkg/controller/realmadmin/save.go
  pkg/database/duration.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_test.go
  pkg/database/token.go
  pkg/database/token_test.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  pkg/otp/code.go
  pkg/otp/code_test.go
Labels: approved, cla: yes, lgtm, size/XL

#227 html to check code claim status
  cmd/adminapi/main.go
  cmd/server/assets/apikeys/show.html
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/main.go
  pkg/controller/codestatus/api.go
  pkg/controller/codestatus/controller.go
  pkg/controller/codestatus/index.go
  pkg/controller/codestatus/logic.go
  pkg/controller/codestatus/show.go
  pkg/controller/issueapi/codestatus.go
Labels: approved, cla: yes, lgtm, size/XL

#250 Add metric when rate limited, log errors, log scope
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/M

#251 Move realm into another header
  cmd/server/assets/header.html
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/M

#252 Fix redirect loop with valid Firebase user, but non-database user
  pkg/controller/middleware/auth.go
Labels: approved, cla: yes, lgtm, size/XS

#253 Followup on some nits
  pkg/controller/codestatus/logic.go
  pkg/controller/codestatus/show.go
Labels: approved, cla: yes, lgtm, size/S

#254 Issue185
  pkg/api/api.go
  pkg/api/util.go
  pkg/api/util_test.go
  pkg/controller/verifyapi/verify.go
  pkg/database/token.go
  pkg/database/token_test.go
Labels: approved, cla: yes, lgtm, size/L

#255 fix long code db migration
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/S

#256 fix gorm panic
  pkg/database/token.go
Labels: approved, cla: yes, lgtm, size/XS

#257 Log info in commands
  cmd/add-users/main.go
  cmd/get-certificate/main.go
  cmd/get-code/main.go
  cmd/get-token/main.go
Labels: approved, cla: yes, lgtm, size/S

#261 initialize default realm settings when creating a new realm via cmd l…
  cmd/add-realm/main.go
Labels: approved, cla: yes, lgtm, size/XS

#262 Fixes found while spinning up a new project
  builders/migrate.yaml
  cmd/migrate/main.go
  pkg/database/config.go
  scripts/migrate
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/S

#264 change command line config processing so it can resolve secret://
  cmd/add-realm/main.go
  cmd/add-users/main.go
Labels: approved, cla: yes, lgtm, size/S

#269 Update rate limiter, add more logging
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/ratelimit/config.go
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/L

#270 Alternative sign-in page using Identity Platform
  cmd/server/assets/login.html
  cmd/server/main.go
  pkg/controller/login/controller.go
  pkg/controller/login/login.go
Labels: approved, cla: yes, lgtm, size/L

#272 Fixes the verification flow chart.
  README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#273 Nit: remove form element
  cmd/server/assets/login.html
Labels: approved, cla: yes, lgtm, size/M

#271 Upgrade deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#258 HMAC verification codes in the database
  README.md
  builders/migrate.yaml
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/migrations.go
  pkg/database/token.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  scripts/dev
  scripts/migrate
  terraform/database.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/XL

#275 fix content-type on return and a stray 200 code
  pkg/controller/verifyapi/verify.go
  pkg/jsonclient/client.go
  pkg/render/html.go
  pkg/render/json.go
Labels: approved, cla: yes, lgtm, size/S

#276 Move login html & fix session
  cmd/server/assets/login/login.html
  cmd/server/assets/login/signout.html
  cmd/server/main.go
Labels: approved, cla: yes, lgtm, size/XS

#277 Upgrade to Go 1.15
  Dockerfile
  builders/migrate.yaml
Labels: approved, cla: yes, lgtm, size/XS

#278 Fix code display in UI and verification checks against HMAC values.
  pkg/database/token.go
  pkg/database/vercode.go
  pkg/otp/code.go
  pkg/otp/code_test.go
Labels: approved, cla: yes, lgtm, size/M

#279 Update firebase, local dev
  README.md
  cmd/server/assets/firebase.html
  cmd/server/assets/login/signout.html
  scripts/dev
Labels: approved, cla: yes, lgtm, size/S

#280 Create an email verification page
  cmd/server/assets/login/verifyemail.html
  cmd/server/main.go
  pkg/controller/login/verifyemail.go
Labels: approved, cla: yes, lgtm, size/L

#281 rename interface from signer to keys
  pkg/controller/certapi/certapi.go
  pkg/controller/certapi/certificate.go
  pkg/controller/verifyapi/verify.go
  pkg/gcpkms/gcpkms.go
  pkg/keys/keys.go
Labels: approved, cla: yes, lgtm, size/M

#284 Require user emails be verified to authenticate
  cmd/server/assets/login/verifyemail.html
  pkg/controller/middleware/auth.go
Labels: approved, cla: yes, lgtm, size/S

#285 upgrade terraform module to tf 0.13
  terraform/variables.tf
  terraform/versions.tf
Labels: approved, cla: yes, lgtm, size/S

#288 Remove the existing index page
  cmd/server/assets/firebase.html
  cmd/server/assets/header.html
  cmd/server/assets/index.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/signout.html
  cmd/server/assets/login/verifyemail.html
  cmd/server/main.go
  pkg/controller/index/index.go
  pkg/controller/login/controller.go
  pkg/controller/login/create.go
  pkg/controller/login/signout.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/emailverified.go
  pkg/controller/session/session.go
Labels: approved, cla: yes, lgtm, size/L

#289 Add error flash in as needed
  cmd/server/assets/login/login.html
Labels: approved, cla: yes, lgtm, size/S

#291 Handle verified emails
  cmd/server/assets/login/login.html
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#292 Fix file spacing, declare dom elements upfront
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/login/signout.html
  cmd/server/assets/login/verifyemail.html
Labels: approved, cla: yes, lgtm, size/L

#274 Add generic cache interfaces
  pkg/cache/cacher.go
  pkg/cache/cacher_test.go
  pkg/cache/in_memory.go
  pkg/cache/in_memory_test.go
  pkg/cache/noop.go
  pkg/cache/redis.go
  pkg/cache/redis_test.go
  pkg/database/database.go
  pkg/database/sms_config.go
Labels: approved, cla: yes, lgtm, size/XXL

#248 Add an LB in front of cloud run services
  terraform/lb.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#290 Create a phone registration page
  cmd/server/assets/login/registerphone.html
  cmd/server/assets/login/verifyemail.html
  cmd/server/main.go
  pkg/controller/login/register.go
  pkg/controller/middleware/emailverified.go
Labels: approved, cla: yes, lgtm, size/L

#287 Calculate stats on save
  cmd/server/assets/apikeys/show.html
  cmd/server/assets/header.html
  cmd/server/assets/users/index.html
  cmd/server/assets/users/show.html
  pkg/controller/apikey/show.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/user/index.go
  pkg/controller/user/show.go
  pkg/database/authorized_app.go
  pkg/database/authorized_app_stats.go
  pkg/database/migrations.go
  pkg/database/user.go
  pkg/database/user_stats.go
  pkg/database/vercode.go
  pkg/render/html.go
Labels: approved, cla: yes, lgtm, size/XL

#295 Fix form formatting on SMS template
  cmd/server/assets/realm.html
Labels: approved, cla: yes, lgtm, size/S

#293 Move the error flash insertion to a javascript function
  cmd/server/assets/header.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/registerphone.html
Labels: approved, cla: yes, lgtm, size/M

#294 Add an output with environment variables to run psql.
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#297 Center login form to match mocks
  cmd/server/assets/login/login.html
Labels: approved, cla: yes, lgtm, size/M

#298 Bring back the firebaseui login for new user flow
  cmd/server/assets/firebase.html
  cmd/server/assets/login/legacylogin.html
  cmd/server/assets/login/login.html
  cmd/server/main.go
  pkg/controller/login/login.go
Labels: approved, cla: yes, lgtm, size/L

#301 Accept SMS authentication
  cmd/server/assets/login/login.html
Labels: approved, cla: yes, lgtm, size/M

#328 Fix race in creating cleanup status
  cmd/cleanup/main.go
  pkg/controller/cleanup/cleanup.go
  pkg/database/cleanup.go
Labels: approved, cla: yes, lgtm, size/M

#329 Switch to JSON encoding for cacher, decouple cacher from db
  cmd/server/main.go
  pkg/cache/cacher.go
  pkg/cache/cacher_test.go
  pkg/cache/config.go
  pkg/cache/in_memory.go
  pkg/cache/noop.go
  pkg/cache/redis.go
  pkg/controller/apikey/apikey.go
  pkg/controller/apikey/show.go
  pkg/controller/login/controller.go
  pkg/controller/user/show.go
  pkg/controller/user/user.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/database_util.go
  pkg/database/realm.go
  pkg/database/sms_config.go
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/L

#331 Signout to use flash and redirect
  cmd/server/assets/login/registerphone.html
  cmd/server/assets/login/signout.html
Labels: approved, cla: yes, lgtm, size/S

#302 Page for creating a new user
  cmd/server/assets/login/create.html
  cmd/server/assets/login/legacylogin.html
  cmd/server/assets/login/login.html
  cmd/server/main.go
  pkg/controller/login/create.go
  pkg/controller/login/login.go
  pkg/controller/login/session.go
Labels: approved, cla: yes, lgtm, size/L

#332 Update readme
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#333 nits
  cmd/server/assets/login/create.html
Labels: approved, cla: yes, lgtm, size/XS

#334 Make KMS key ring name configurable
  terraform/keys.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#336 Set request timeout for services behind a GCLB to 25s
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/XS

#335 Nit: only need to load login script for login
  cmd/server/assets/header.html
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/login/create.html
  cmd/server/assets/login/login.html
Labels: approved, cla: yes, lgtm, size/M

#338 Clear() should clear warnings
  pkg/controller/flash/flash.go
Labels: approved, cla: yes, lgtm, size/XS

#342 pin verification server to exposure notifications v0.5.0 release
  go.mod
  go.sum
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/XS

#339 Correct error codes
  pkg/controller/verifyapi/verify.go
Labels: approved, cla: yes, lgtm, size/XS

#343 Allow auth app to check code status
  pkg/controller/codestatus/logic.go
Labels: approved, cla: yes, lgtm, size/S

#345 Fix e2e test logging messages.
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/XS

#330 Per-realm signing
  cmd/add-realm/main.go
  cmd/apiserver/main.go
  cmd/migrate/main.go
  cmd/server/assets/header.html
  cmd/server/assets/realmkeys.html
  cmd/server/main.go
  go.mod
  pkg/config/api_server_config.go
  pkg/config/certificate_signing_config.go
  pkg/config/server_config.go
  pkg/controller/certapi/certapi.go
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/signers.go
  pkg/controller/realmkeys/activate.go
  pkg/controller/realmkeys/index.go
  pkg/controller/realmkeys/new.go
  pkg/controller/realmkeys/realmkeys.go
  pkg/controller/realmkeys/render.go
  pkg/controller/realmkeys/save.go
  pkg/controller/realmkeys/upgrade.go
  pkg/controller/verifyapi/verify.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/duration.go
  pkg/database/errors.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/signing_key.go
  pkg/gcpkms/gcpkms.go
  pkg/keyutils/encoding.go
  pkg/keyutils/public_keys.go
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/XXL

#347 Ignore locally built binary files.
  .gitignore
Labels: approved, cla: yes, lgtm, size/S

#351 Healthz tweaks
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  pkg/controller/apikey/show.go
  pkg/controller/healthz.go
Labels: approved, cla: yes, lgtm, size/S

#353 Add instructions for setting quota project, fix dev script
  README.md
  scripts/dev
Labels: approved, cla: yes, lgtm, size/XS

#352 Clear countdown timers
  cmd/server/assets/home.html
Labels: approved, cla: yes, lgtm, size/S

#354 Document production setup as a module
  terraform/README.md
  terraform/variables.tf
  terraform/versions.tf
Labels: approved, cla: yes, lgtm, size/L

#355 Cache users, api keys, and realms for 30s
  cmd/add-realm/main.go
  cmd/add-users/main.go
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/assets/codestatus/index.html
  cmd/server/main.go
  pkg/config/admin_server_config.go
  pkg/config/api_server_config.go
  pkg/controller/apikey/update.go
  pkg/controller/context.go
  pkg/controller/login/session.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/realm.go
  pkg/controller/realmadmin/realmadmin.go
  pkg/controller/realmadmin/save.go
  pkg/controller/user/update.go
  pkg/controller/user/user.go
  pkg/database/authorized_app.go
  pkg/database/realm.go
  pkg/database/sms_config_test.go
  pkg/database/user.go
  terraform/README.md
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
Labels: approved, cla: yes, lgtm, size/L

#357 need to upgrade realm in migrations that cause realm to be addressed
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/XS

#358 Render inline codestatus responses
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/home.html
  pkg/controller/codestatus/index.go
  pkg/controller/codestatus/show.go
  pkg/database/vercode.go
Labels: approved, cla: yes, lgtm, size/M

#363 Troubleshooting firebase ToS not accepted
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#364 Move realm settings under user dropdown
  cmd/server/assets/header.html
Labels: approved, cla: yes, lgtm, size/M

#365 Disable text selection on short code
  cmd/server/assets/home.html
Labels: approved, cla: yes, lgtm, size/XS

#366 Nit: remove blip when showing expired time
  cmd/server/assets/home.html
Labels: approved, cla: yes, lgtm, size/S

#367 Give server permission to read keys
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/XS

#368 show code with countdown expiry
  cmd/server/assets/codestatus/_codescripts.html
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/home.html
  pkg/controller/codestatus/show.go
Labels: approved, cla: yes, lgtm, size/L

#369 Automatically clear caches on save
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  pkg/controller/apikey/update.go
  pkg/controller/healthz.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/realm.go
  pkg/controller/realmadmin/realmadmin.go
  pkg/controller/realmadmin/save.go
  pkg/controller/user/update.go
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/L

#371 Sort things
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/XS

#361 Add redis opencensus metrics to the server
  go.mod
  go.sum
  pkg/ratelimit/config.go
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#370 Use floating form labels for login / check status
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/header.html
  cmd/server/assets/login/create.html
  cmd/server/assets/login/login.html
Labels: approved, cla: yes, lgtm, size/L

#372 Use js to groom uuid formatting
  cmd/server/assets/codestatus/index.html
Labels: approved, cla: yes, lgtm, size/M

#374 Re-organize README and documentation, remove outdated
  README.md
  docs/api.md
  docs/development.md
  docs/ens-spec.md
  docs/images/getting-started/0_login.png
  docs/images/getting-started/1_create_user.png
  docs/images/getting-started/2_issue_verification_code.png
  docs/images/getting-started/3_verification_code_issued.png
  docs/production.md
  docs/testing.md
Labels: approved, cla: yes, lgtm, size/XL

#375 Expand the show code page to include more fields
  cmd/server/assets/codestatus/show.html
  pkg/controller/codestatus/show.go
Labels: approved, cla: yes, lgtm, size/L

#376 Added redis observability to cache
  go.mod
  go.sum
  pkg/cache/redis.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#377 Remove unused signing key code
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#382 Create separate key manager instances for certs, tokens, and db
  cmd/apiserver/main.go
  pkg/config/api_server_config.go
  pkg/config/certificate_signing_config.go
  pkg/config/server_config.go
  pkg/config/token_signing_config.go
  pkg/controller/certapi/certapi.go
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/signers.go
  pkg/controller/realmkeys/render.go
  pkg/controller/verifyapi/verify.go
  pkg/database/config.go
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/L

#380 Add code expire endpoint
  cmd/adminapi/main.go
  pkg/api/api.go
  pkg/controller/codestatus/expire.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/L

#383 Use new key manager interface
  cmd/add-realm/main.go
  cmd/server/assets/realmkeys.html
  go.mod
  go.sum
  pkg/controller/realmkeys/activate.go
  pkg/controller/realmkeys/new.go
  pkg/database/database.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#388 Nits
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/login/create.html
  cmd/server/assets/login/login.html
  pkg/database/vercode.go
Labels: approved, cla: yes, lgtm, size/M

#387 Add middleware for setting HSTS headers
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  pkg/controller/middleware/hsts.go
Labels: approved, cla: yes, lgtm, size/M

#391 Set 1m idle timeout on Redis connections
  pkg/cache/config.go
  pkg/cache/redis.go
  pkg/ratelimit/config.go
  pkg/redis/config.go
  terraform/main.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/L

#392 Remove maxwidth from index
  cmd/server/assets/codestatus/index.html
Labels: approved, cla: yes, lgtm, size/S

#389 Add support for destroying signing key versions
  cmd/server/assets/realmkeys.html
  cmd/server/main.go
  pkg/controller/realmkeys/destroy.go
  pkg/controller/realmkeys/realmkeys.go
  pkg/controller/realmkeys/render.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#393 Keepalive
  pkg/database/config.go
  pkg/database/database.go
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/S

#348 implement token signing key rotation
  pkg/config/api_server_config.go
  pkg/config/token_signing_config.go
  pkg/controller/certapi/certapi.go
  pkg/controller/certapi/certificate.go
  pkg/controller/verifyapi/verify.go
Labels: approved, cla: yes, lgtm, size/M

#395 make the code more better
  pkg/config/api_server_config.go
  pkg/config/token_signing_config.go
Labels: approved, cla: yes, lgtm, size/M

#399 Fix err message
  pkg/controller/certapi/certificate.go
Labels: approved, cla: yes, lgtm, size/XS
