Repository google/exposure-notifications-verification-server, pull requests merged in 2020-12, with the labels that each got.

#1217 Clarify backup code vs short code
  cmd/server/assets/codes/issue.html
  cmd/server/assets/static/css/application.css
  pkg/controller/codes/issue_test.go
Labels: approved, cla: yes, lgtm, size/L

#1218 Internationalize SMS placeholder input
  cmd/server/assets/codes/issue.html
Labels: approved, cla: yes, lgtm, size/XS

#1219 About link
  cmd/server/assets/login/login.html
Labels: approved, cla: yes, lgtm, size/XS

#1220 Update terraform README with the expected variable values.
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#1224 Do not rate limit chaff requests
  cmd/apiserver/main.go
Labels: approved, cla: yes, lgtm, size/M

#1225 Add observability results for client UUID
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/XS

#1226 Add triage steps for StackdriverExportFailed alert
  docs/playbooks/alerts/StackdriverExportFailed.md
Labels: approved, cla: yes, lgtm, size/S

#1229 Fully i18nize issue page
  cmd/server/assets/codes/_codescripts.html
  cmd/server/assets/codes/issue.html
  cmd/server/assets/codes/show.html
  cmd/server/assets/header.html
  cmd/server/assets/static/js/application.js
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
Labels: approved, cla: yes, lgtm, size/L

#1234 update docs around sending chaff requests
  docs/api.md
Labels: approved, cla: yes, lgtm, size/S

#1233 Display user and external stats as tables
  cmd/server/assets/realmadmin/show.html
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#1235 Doc nits
  docs/api.md
Labels: approved, cla: yes, lgtm, size/S

#1228 Add playbook for HostDown alert.
  docs/playbooks/alerts/HostDown.md
Labels: approved, cla: yes, lgtm, size/S

#1238 Let the browser do date math
  cmd/server/assets/admin/events/index.html
  cmd/server/assets/codes/index.html
  cmd/server/assets/realmadmin/events.html
  cmd/server/assets/static/js/application.js
Labels: approved, cla: yes, lgtm, size/M

#1239 Add UI to share system SMS config
  cmd/server/assets/admin/realms/edit.html
  pkg/controller/admin/realms.go
Labels: approved, cla: yes, lgtm, size/M

#1241 Add docs on how to i18n
  internal/i18n/README.md
Labels: approved, cla: yes, lgtm, size/M

#1191 Sync android apps from json file
  cmd/app-sync/main.go
  cmd/e2e-runner/main.go
  internal/project/random.go
  pkg/api/api.go
  pkg/clients/apis.go
  pkg/clients/responses.go
  pkg/config/appsync_server_config.go
  pkg/controller/appsync/appsync.go
  pkg/controller/appsync/appsync_test.go
  pkg/controller/appsync/controller.go
  pkg/database/mobile_app.go
  pkg/testsuite/e2e.go
  pkg/testsuite/helpers.go
  pkg/testsuite/integration.go
Labels: approved, cla: yes, lgtm, size/L

#1240 Add system admin guide
  README.md
  docs/case-worker-guide.md
  docs/images/system-admin/caches-index.png
  docs/images/system-admin/email-show.png
  docs/images/system-admin/info-show.png
  docs/images/system-admin/new-realm.png
  docs/images/system-admin/new-system-admin.png
  docs/images/system-admin/realm-show-email.png
  docs/images/system-admin/realm-show-sms.png
  docs/images/system-admin/realm-show.png
  docs/images/system-admin/realms-index.png
  docs/images/system-admin/sms-show.png
  docs/images/system-admin/users-index.png
  docs/realm-admin-guide.md
  docs/system-admin-guide.md
Labels: approved, cla: yes, lgtm, size/L

#1244 Capture and display daily active user stats
  cmd/apiserver/main.go
  cmd/server/assets/realmadmin/show.html
  docs/api.md
  pkg/controller/middleware/chaff.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_stats.go
Labels: approved, cla: yes, lgtm, size/L

#1243 Terraform for appsync
  terraform/service_appsync.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/L

#1245 Build and deploy app-sync
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/M

#1246 Use correct container name
  terraform/service_appsync.tf
Labels: approved, cla: yes, lgtm, size/XS

#1247 accept app_name for mobile app sync
  pkg/clients/responses.go
  pkg/controller/appsync/appsync.go
Labels: approved, cla: yes, lgtm, size/XS

#1249 point back to the new user
  pkg/controller/user/importbatch.go
Labels: approved, cla: yes, lgtm, size/L

#1248 add instructions for configuring e2e test runner on a fresh deployment
  docs/images/e2e/image01.png
  docs/images/e2e/image02.png
  docs/images/e2e/image03.png
  docs/images/e2e/image04.png
  docs/images/e2e/image05.png
  docs/images/e2e/image06.png
  docs/images/e2e/image07.png
  docs/images/e2e/image08.png
  docs/images/e2e/image09.png
  docs/images/e2e/image10.png
  docs/images/e2e/image11.png
  docs/images/e2e/image12.png
  docs/production.md
Labels: approved, cla: yes, lgtm, size/M

#1029 Smoke test: also test deploy alerting module with terraform
  scripts/ci-terraform.sh
  terraform-e2e-ci/main.tf
Labels: approved, cla: yes, lgtm, size/S

#1227 Batch API for code issuing
  docs/api.md
  internal/routes/server.go
  pkg/api/api.go
  pkg/controller/issueapi/controller.go
  pkg/controller/issueapi/handle_issue.go
  pkg/controller/issueapi/handle_issue_batch.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/logic.go
  pkg/controller/issueapi/parse_date.go
  pkg/controller/issueapi/show_bulk_issue.go
Labels: approved, cla: yes, lgtm, size/XXL

#1258 Return appsync errors as strings
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
  cmd/appsync/main.go
  pkg/controller/appsync/appsync.go
  terraform/service_appsync.tf
Labels: approved, cla: yes, lgtm, size/M

#1259 Recreates Spanish i18n language file
  internal/i18n/locales/es/default.po
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1262 Only warn on missing regions
  pkg/controller/appsync/appsync.go
Labels: approved, cla: yes, lgtm, size/XS

#1261 Add Redis related metrics to the Verification Server dashboard.
  terraform/alerting/dashboards/verification-server.yaml
Labels: approved, cla: yes, lgtm, size/S

#1263 Adjust probe timeout to 10s.
  terraform/alerting/probers.tf
Labels: approved, cla: yes, lgtm, size/XS

#1260 add deep link handling instructions
  README.md
  docs/link_handling.md
Labels: approved, cla: yes, lgtm, size/L

#1264 Updating realm admin guide
  docs/images/admin/menu_apikeys.png
  docs/images/admin/menu_settings.png
  docs/images/admin/menu_signing.png
  docs/images/admin/menu_users.png
  docs/images/admin/settings01.png
  docs/images/admin/settings_code.png
  docs/realm-admin-guide.md
Labels: approved, cla: yes, lgtm, size/M

#1265 Add bulk issue to case-worker-guide
  docs/case-worker-guide.md
  docs/images/admin/bulk_issue.png
  docs/images/admin/menu_bulk_issue.png
  docs/realm-admin-guide.md
Labels: approved, cla: yes, lgtm, size/M

#1266 Fix image links in guide
  docs/case-worker-guide.md
  docs/images/issue/bulk_issue.png
  docs/images/issue/menu_bulk_issue.png
Labels: approved, cla: yes, lgtm, size/XS

#1267 Add details about errors to the bulk-issue user-guide.
  docs/case-worker-guide.md
  docs/images/issue/bulk_issue_done.png
Labels: approved, cla: yes, lgtm, size/S

#1269 Only check spelling in Go and HTML files
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#1268 Adding fr i18n file
  internal/i18n/locales/fr/default.po
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1270 Print a message when loading returns with no stats
  cmd/server/assets/realmadmin/show.html
Labels: approved, cla: yes, lgtm, size/XS

#1272 Add table of contents to markdown guides
  docs/case-worker-guide.md
  docs/realm-admin-guide.md
  docs/system-admin-guide.md
Labels: approved, cla: yes, lgtm, size/M

#1271 add externalIssuerID to issue sample
  docs/api.md
Labels: approved, cla: yes, lgtm, size/XS

#1273 Nit: Show batch limit in error message
  pkg/controller/issueapi/handle_issue_batch.go
Labels: approved, cla: yes, lgtm, size/XS

#1275 Add a doc on general troubleshooting tips.
  docs/playbooks/tips.md
Labels: approved, cla: yes, lgtm, size/L

#1276 Add more detailed stats help information
  cmd/server/assets/realmadmin/show.html
Labels: approved, cla: yes, lgtm, size/L

#1257 Put o11y context into middleware
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/appsync/main.go
  cmd/cleanup/main.go
  cmd/e2e-runner/main.go
  cmd/enx-redirect/main.go
  cmd/modeler/main.go
  internal/routes/server.go
  pkg/clients/e2e.go
  pkg/controller/certapi/certificate.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/context.go
  pkg/controller/issueapi/handle_issue.go
  pkg/controller/issueapi/handle_issue_batch.go
  pkg/controller/issueapi/logic.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/observability.go
  pkg/controller/verifyapi/verify.go
  pkg/database/database.go
  pkg/observability/observability.go
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/L

#1278 Unify common date types into project
  internal/project/datetime.go
  internal/project/random.go
  pkg/clients/e2e.go
  pkg/controller/admin/events_test.go
  pkg/controller/codes/issue.go
  pkg/controller/codes/issue_test.go
  pkg/controller/issueapi/issue_test.go
  pkg/controller/issueapi/logic.go
  pkg/controller/realmadmin/show.go
  pkg/database/external_issuer_stats.go
  pkg/database/realm_stats.go
  pkg/database/realm_user_stats.go
  pkg/database/token.go
  pkg/database/token_test.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  pkg/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/L

#1277 Use the new batch API for the bulk uploader
  cmd/server/assets/codes/bulk-issue.html
Labels: approved, cla: yes, lgtm, size/M

#1279 Update to floating form styles on realm keys page
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/realmadmin/keys.html
  cmd/server/assets/realmadmin/stats.html
  cmd/server/assets/realmkeys.html
  internal/routes/server.go
  pkg/controller/realmadmin/stats.go
  pkg/controller/realmkeys/render.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/XL

#1274 Add portuguese language translations
  internal/i18n/locales/pt/default.po
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1281 Update slos.tf
  terraform/alerting/slos.tf
Labels: approved, cla: yes, lgtm, size/XS

#1283 Keep uint as uint64 for observability
  pkg/controller/context.go
  pkg/database/database.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/M

#1284 Add Italian language translation
  internal/i18n/locales/it/default.po
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1282 Add clarity around terms
  internal/i18n/README.md
Labels: approved, cla: yes, lgtm, size/M

#1285 Install batch-issue in adminAPI and integration
  cmd/adminapi/main.go
  internal/routes/server.go
  pkg/controller/codes/bulk_issue.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/issue_batch.go
  pkg/testsuite/integration.go
Labels: approved, cla: yes, lgtm, size/XS

#1286 Add CSV and JSON exports for user stats
  cmd/server/assets/realmadmin/stats.html
  cmd/server/assets/static/js/application.js
  cmd/server/assets/users/show.html
  internal/routes/server.go
  internal/routes/server_test.go
  pkg/controller/user/controller.go
  pkg/controller/user/create.go
  pkg/controller/user/show.go
  pkg/controller/user/stats.go
  pkg/database/migrations.go
  pkg/database/realm_test.go
  pkg/database/user.go
  pkg/database/user_stats.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1287 Test nit: Include issue and bulk-issue route
  internal/routes/server_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1288 Document batch-issue API
  docs/api.md
Labels: approved, cla: yes, lgtm, size/L

#1290 Turkish (tr) translation
  internal/i18n/locales/tr/default.po
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1292 Bump key server dependency to 0.18.0
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#1293 Update ElevatedRateLimitedCount.md
  docs/playbooks/alerts/ElevatedRateLimitedCount.md
Labels: approved, cla: yes, lgtm, size/M

#1294 Added conditions to error budget burn policies
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1295 change SMS max length
  cmd/server/assets/realmadmin/_form_codes.html
  pkg/controller/realmadmin/settings.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#1297 Correct link in docs
  docs/realm-admin-guide.md
Labels: approved, cla: yes, lgtm, size/XS

#1300 Don't enable cloudidentity twice
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1303 Add Japanese (ja) locale
  internal/i18n/locales/ja/default.po
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1302 Initial config for Cloud Armor
  docs/playbooks/dos.md
  terraform/dos.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/L

#1304 flipped response/request
  docs/api.md
Labels: approved, cla: yes, lgtm, size/S

#1307 Switch to older associated domain format
  docs/link_handling.md
  pkg/controller/associated/ios.go
Labels: approved, cla: yes, lgtm, size/M

#1308 Update to iOS mobile apps format
  cmd/server/assets/mobileapps/_app.html
  docs/link_handling.md
  pkg/controller/associated/ios.go
  pkg/database/mobile_app.go
Labels: approved, cla: yes, lgtm, size/XS

#1311 Fix the threshold of the stackdriver export failure alert.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1313 Return 400 on Twilio errors
  pkg/controller/issueapi/logic.go
Labels: approved, cla: yes, lgtm, size/XS

#1315 Add an SLO chart in the Verification Server dashboard.
  terraform/alerting/dashboards/verification-server.yaml
Labels: approved, cla: yes, lgtm, size/S

#1316 Use proper/readable units in alert conditions.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1317 Fix stackdriver export alert again.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1314 Adding translation for German[de]
  internal/i18n/locales/de/default.po
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1312 Support multiple from numbers for system SMS configs
  cmd/server/assets/admin/sms/show.html
  cmd/server/assets/realmadmin/_form_sms.html
  pkg/controller/admin/sms.go
  pkg/controller/admin/sms_test.go
  pkg/controller/realmadmin/settings.go
  pkg/controller/realmadmin/sms_test.go
  pkg/database/database.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_test.go
  pkg/database/sms_config.go
  pkg/database/sms_from_number.go
  pkg/database/sms_from_number_test.go
  pkg/render/render.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1318 Document SMS client errors
  docs/api.md
Labels: approved, cla: yes, lgtm, size/XS

#1319 Update alerts.tf
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1324 Try different recatcha reset
  cmd/server/assets/static/js/application.js
Labels: approved, cla: yes, lgtm, size/S

#1327 Update StackdriverExportFailed alert duration to 15min.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1326 allow short code to be in ENX SMS messages / link still required
  cmd/server/assets/realmadmin/_form_codes.html
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/L

#1330 remove jeremyfaller from owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1331 Return a more detailed error when bulk issue is not enabled
  pkg/controller/issueapi/issue_batch.go
Labels: approved, cla: yes, lgtm, size/XS

#1329 Doc limit
  docs/api.md
Labels: approved, cla: yes, lgtm, size/XS

#1332 Remove old /home route
  internal/routes/server.go
Labels: approved, cla: yes, lgtm, size/S

#1336 use warnw correctly
  pkg/controller/issueapi/issue_batch.go
Labels: approved, cla: yes, lgtm, size/XS

#1337 Change rate calculating window of StackdriverExportFailed alert.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1340 Add comment on why we use 5min window to calculate the rate.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1298 Move Renderer behind an interface
  go.mod
  go.sum
  pkg/controller/admin/admin.go
  pkg/controller/apikey/apikey.go
  pkg/controller/appsync/controller.go
  pkg/controller/associated/index.go
  pkg/controller/certapi/certapi.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/codes/bulk_issue_test.go
  pkg/controller/codes/controller.go
  pkg/controller/controller.go
  pkg/controller/email.go
  pkg/controller/healthz.go
  pkg/controller/issueapi/controller.go
  pkg/controller/jwks/jwks.go
  pkg/controller/login/controller.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/csrf.go
  pkg/controller/middleware/emailverified.go
  pkg/controller/middleware/firewall.go
  pkg/controller/middleware/header.go
  pkg/controller/middleware/membership.go
  pkg/controller/middleware/mfa.go
  pkg/controller/middleware/request_id.go
  pkg/controller/middleware/sessions.go
  pkg/controller/mobileapps/mobileapp.go
  pkg/controller/modeler/modeler.go
  pkg/controller/realmadmin/realmadmin.go
  pkg/controller/realmkeys/realmkeys.go
  pkg/controller/redirect/redirect.go
  pkg/controller/user/controller.go
  pkg/controller/verifyapi/verifyapi.go
  pkg/render/csv.go
  pkg/render/email.go
  pkg/render/html.go
  pkg/render/json.go
  pkg/render/renderer.go
  pkg/render/renderer_impl.go
  pkg/render/test_renderer.go
Labels: approved, cla: yes, lgtm, size/L

#1342 Add more padding to graphs
  cmd/server/assets/apikeys/show.html
  cmd/server/assets/realmadmin/stats.html
  cmd/server/assets/users/show.html
Labels: approved, cla: yes, lgtm, size/XS

#1325 Add Multi-SMS template columns to realm db
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/L

#1345 Fine-tuning the latency alert threshold.
  docs/playbooks/alerts/LatencyTooHigh.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1346 Add marilia to owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1347 Refactor Availability SLO definition
  docs/playbooks/slo/FastErrorBudgetBurn.md
  docs/playbooks/slo/SlowErrorBudgetBurn.md
  docs/playbooks/slo/_ErrorBudgetBurn.md
  terraform/alerting/alerts.tf
  terraform/alerting/module.availability-slo/main.tf
  terraform/alerting/module.availability-slo/variables.tf
  terraform/alerting/slos.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1349 Add test for ensuring migration numbers are up and to the right
  pkg/database/database_util.go
  pkg/database/migrations.go
  pkg/database/migrations_test.go
Labels: approved, cla: yes, lgtm, size/M

#1338 Realm settings for multiple SMS templates
  cmd/server/assets/realmadmin/_form_codes.html
  pkg/controller/realmadmin/settings_modify.go
  pkg/controller/realmadmin/settings_show.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/XL

#1351 Add availability SLO alerts on all Cloud Run services.
  terraform/alerting/slos.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#1353 Properly redirect to login when required
  pkg/controller/controller.go
  pkg/controller/flash/flash.go
  pkg/controller/login/signout.go
  pkg/controller/middleware/auth.go
Labels: approved, cla: yes, lgtm, size/M

#1354 fix realm from firewall for apikeys
  pkg/controller/middleware/firewall.go
Labels: approved, cla: yes, lgtm, size/S

#1355 Redirect back if bulk upload is not enabled
  pkg/controller/codes/bulk_issue.go
  pkg/controller/codes/bulk_issue_test.go
Labels: approved, cla: yes, lgtm, size/S

#1360 scrub phone numbers
  pkg/controller/issueapi/logic.go
  pkg/controller/issueapi/logic_test.go
Labels: approved, cla: yes, lgtm, size/M

#1361 Add a rudimentary Latency SLO.
  docs/playbooks/slo/FastLatencyBudgetBurn.md
  docs/playbooks/slo/SlowLatencyBudgetBurn.md
  docs/playbooks/slo/_LatencyBudgetBurn.md
  terraform/alerting/alerts.tf
  terraform/alerting/module.latency-slo/main.tf
  terraform/alerting/module.latency-slo/variables.tf
  terraform/alerting/slos.tf
Labels: approved, cla: yes, lgtm, size/L

#1362 Exclude a rule in Cloud Armor.
  terraform/dos.tf
Labels: approved, cla: yes, lgtm, size/S

#1363 Update latency threshold to 60s.
  terraform/alerting/module.latency-slo/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1364 Fix the name of the SLO.
  terraform/alerting/module.latency-slo/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1352 Allow the issuer to select an SMS template
  cmd/server/assets/codes/issue.html
  docs/api.md
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
  pkg/api/api.go
  pkg/controller/issueapi/logic.go
  pkg/controller/middleware/csrf.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/L

#1365 Add details about handling partial success
  docs/api.md
Labels: approved, cla: yes, lgtm, size/M

#1368 Document error codes table for IssueResponse
  docs/api.md
Labels: approved, cla: yes, lgtm, size/M

#1366 Add a knob to enable Load Balancer logging.
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#1367 Use a single var.project in en-alerting module.
  terraform/README.md
  terraform/alerting/alerts.tf
  terraform/alerting/module.availability-slo/main.tf
  terraform/alerting/module.availability-slo/variables.tf
  terraform/alerting/monitoring.tf
  terraform/alerting/notifications.tf
  terraform/alerting/probers.tf
  terraform/alerting/slos.tf
  terraform/alerting/variables.tf
  terraform/alerting/workspace.tf
Labels: approved, cla: yes, lgtm, size/M

#1369 Clearer outer error message for batch API
  docs/api.md
  pkg/controller/issueapi/issue_batch.go
Labels: approved, cla: yes, lgtm, size/S

#1371 add another scrubbing pattern
  pkg/controller/issueapi/logic.go
  pkg/controller/issueapi/logic_test.go
Labels: approved, cla: yes, lgtm, size/M

#1370 Add SMS template choice to bulk-uploader
  cmd/server/assets/codes/bulk-issue.html
Labels: approved, cla: yes, lgtm, size/S

#1373 Fix log_config terraform config.
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/S

#1374 Fix json output name
  pkg/controller/associated/ios.go
Labels: approved, cla: yes, lgtm, size/XS

#1375 Add linters for Terraform
  .github/workflows/terraform.yml
  terraform-e2e-ci/main.tf
  terraform/alerting/variables.tf
  terraform/mirror/variables.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1378 Simplify SLO budget burn rate alert.
  terraform/alerting/module.availability-slo/main.tf
  terraform/alerting/module.latency-slo/main.tf
Labels: approved, cla: yes, lgtm, size/S

#1386 Update variable names used in the SLO modules to be more consistent.
  terraform/alerting/module.availability-slo/main.tf
  terraform/alerting/module.availability-slo/variables.tf
  terraform/alerting/module.latency-slo/main.tf
  terraform/alerting/module.latency-slo/variables.tf
  terraform/alerting/slos.tf
Labels: approved, cla: yes, lgtm, size/M

#1384 Extract adminapi and apiserver routes into internal/
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/assets/users/show.html
  internal/routes/adminapi.go
  internal/routes/apiserver.go
  pkg/controller/user/update_test.go
Labels: approved, cla: yes, lgtm, size/L

#1385 Disable SLO alerts except for adminapi/apiserver/server.
  terraform/alerting/module.availability-slo/main.tf
  terraform/alerting/module.availability-slo/variables.tf
  terraform/alerting/module.latency-slo/main.tf
  terraform/alerting/module.latency-slo/variables.tf
  terraform/alerting/slos.tf
Labels: approved, cla: yes, lgtm, size/L

#1396 Make daily active stats collection a realm configurable
  cmd/server/assets/realmadmin/_form_general.html
  pkg/controller/middleware/chaff.go
  pkg/controller/realmadmin/settings_modify.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#1395 Only send welcome email for new firebase user
  cmd/server/assets/users/import.html
  internal/auth/firebase.go
  pkg/controller/user/create.go
  pkg/controller/user/importbatch.go
Labels: approved, cla: yes, lgtm, size/M

#1376 e2e coverage for BatchIssueCode API
  pkg/clients/apis.go
  pkg/clients/e2e.go
  pkg/database/realm.go
  pkg/integration/integration_test.go
  pkg/testsuite/clients.go
  pkg/testsuite/e2e.go
  pkg/testsuite/integration.go
Labels: approved, cla: yes, lgtm, size/L

#1398 Only display daily actives graph if enabled
  cmd/server/assets/realmadmin/_stats_codes.html
  cmd/server/assets/realmadmin/_stats_daily_active_users.html
  cmd/server/assets/realmadmin/_stats_external_issuers.html
  cmd/server/assets/realmadmin/_stats_users.html
  cmd/server/assets/realmadmin/stats.html
Labels: approved, cla: yes, lgtm, size/XL

#1392 Add a note about client-provided UUIDs
  docs/api.md
Labels: approved, cla: yes, lgtm, size/S

#1401 Enable alert on enx-redirect service.
  terraform/alerting/slos.tf
Labels: approved, cla: yes, lgtm, size/XS

#1400 Add RBAC check to issue_batch api
  pkg/controller/issueapi/issue_batch.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/S

#1403 Only create Apache logs for local dev
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/e2e-runner/main.go
  cmd/server/main.go
  internal/routes/adminapi.go
  internal/routes/apiserver.go
  internal/routes/enx_redirect.go
  internal/routes/server.go
  pkg/testsuite/integration.go
Labels: approved, cla: yes, lgtm, size/M

#1404 Add API key type for accessing statistics
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/apikeys/new.html
  cmd/server/assets/apikeys/show.html
  docs/api.md
  internal/routes/adminapi.go
  pkg/controller/apikey/create.go
  pkg/controller/middleware/apikey.go
  pkg/database/authorized_app.go
  pkg/database/authorized_app_test.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#1407 Add ph translations
  internal/i18n/locales/ph/default.po
Labels: approved, cla: yes, lgtm, size/L

#1410 Mount Apache logger in binary
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/enx-redirect/main.go
  cmd/server/main.go
  internal/routes/adminapi.go
  internal/routes/apiserver.go
  internal/routes/enx_redirect.go
  internal/routes/server.go
Labels: approved, cla: yes, lgtm, size/M

#1405 Add descriptions for rbac permissions
  cmd/server/assets/users/_form.html
  cmd/server/assets/users/show.html
  pkg/controller/user/create.go
  pkg/controller/user/show.go
  pkg/controller/user/update.go
  pkg/controller/user/update_test.go
  pkg/rbac/rbac.go
  pkg/rbac/rbac_gen.go
  pkg/render/renderer_impl.go
Labels: approved, cla: yes, lgtm, size/L

#1413 Also includes 3xx responses as part of the good SLI signal.
  terraform/alerting/module.availability-slo/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1414 Create a no-op failure SMS provider
  pkg/database/sms_config.go
  pkg/sms/noop.go
  pkg/sms/sms.go
Labels: approved, cla: yes, lgtm, size/M

#1411 Add implied permissions - write permissions need read permissions to be useful
  pkg/controller/user/update_test.go
  pkg/rbac/rbac.go
  pkg/rbac/rbac_test.go
Labels: approved, cla: yes, lgtm, size/L

#1416 Don't allow admin API keys to read stats
  docs/api.md
  internal/routes/adminapi.go
Labels: approved, cla: yes, lgtm, size/XS

#1415 Update google provider to 3.51
  terraform/alerting/variables.tf
  terraform/mirror/variables.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#1417 Add terraform lock to source control
  terraform-e2e-ci/.terraform.lock.hcl
Labels: approved, cla: yes, lgtm, size/M

#1418 Document implied permissions, enforce via javascript
  cmd/server/assets/users/_form.html
  pkg/controller/user/update_test.go
  pkg/rbac/rbac.go
  pkg/render/renderer_impl.go
Labels: approved, cla: yes, lgtm, size/L

#1420 Make SMS message failures info level
  pkg/controller/controller.go
  pkg/controller/issueapi/logic.go
Labels: approved, cla: yes, lgtm, size/XS

#1419 Wait for Redis connections to become available
  pkg/cache/config.go
  pkg/cache/redis.go
  pkg/redis/config.go
Labels: approved, cla: yes, lgtm, size/S

#1379 Remember user's SMS template preference
  cmd/server/assets/codes/bulk-issue.html
  cmd/server/assets/codes/issue.html
  pkg/cache/cacher_test.go
  pkg/controller/issueapi/logic.go
  pkg/database/membership.go
  pkg/database/membership_test.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#1421 Add specific instructions for Error Burn playbook
  docs/playbooks/slo/_ErrorBudgetBurn.md
Labels: approved, cla: yes, lgtm, size/S

#1422 Extract trace context if present and add to logger
  pkg/controller/middleware/logger.go
Labels: approved, cla: yes, lgtm, size/S

#1424 Show bad path 404s
  pkg/controller/redirect/index_test.go
Labels: approved, cla: yes, lgtm, size/S

#1425 Don't close chaff on routes return
  cmd/apiserver/main.go
  internal/routes/apiserver.go
Labels: approved, cla: yes, lgtm, size/M

#1428 Use envvar to increase stackdriver timeout to 1min.
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/S

#1426 Adding an test for bulk-issue error handling
  internal/routes/adminapi.go
  internal/routes/server.go
  pkg/controller/issueapi/controller.go
  pkg/controller/issueapi/issue_batch_test.go
  pkg/controller/issueapi/logic.go
  pkg/integration/integration_test.go
  pkg/testsuite/clients.go
  pkg/testsuite/integration.go
Labels: approved, cla: yes, lgtm, size/L

#1427 Terraform destroy first remove database from state
  scripts/ci-terraform.sh
  terraform-e2e-ci/.terraform.lock.hcl
Labels: approved, cla: yes, lgtm, size/XS

#1429 Update deps
  go.mod
  go.sum
  pkg/render/test_renderer.go
Labels: approved, cla: yes, lgtm, size/XL
