Repository google/exposure-notifications-verification-server, pull requests merged in 2020-07, with the labels that each got.

#92 fix terraform issues
  terraform/keys.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/S

#96 Fix typo
  pkg/controller/verifyapi/verify.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#98 Fix negative test being reported as likely.
  cmd/server/assets/home.html
  pkg/api/api.go
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/M

#97 Use retry library
  go.mod
  go.sum
  pkg/database/database_util.go
  pkg/retry/retry.go
Labels: approved, cla: yes, lgtm, size/L

#99 Set PROJECT_ID on services
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/S

#100 Grant observability IAM permissions
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/M

#85 Fix CI
  pkg/database/authorized_app_test.go
  pkg/database/config.go
  pkg/database/database_util.go
  pkg/database/token_test.go
  pkg/database/user_test.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/M

#102 make common cmpopts var
  pkg/database/authorized_app_test.go
  pkg/database/database_util.go
  pkg/database/token_test.go
  pkg/database/user_test.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/S

#101 Update verification protocol for v1.5
  cmd/server/assets/home.html
  go.mod
  go.sum
  pkg/api/api.go
  pkg/config/server_config.go
  pkg/controller/certapi/certificate.go
  pkg/controller/home/home.go
  pkg/controller/issueapi/issue.go
  pkg/controller/verifyapi/verify.go
  pkg/database/migrations.go
  pkg/database/token.go
  pkg/database/token_test.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  pkg/otp/code.go
Labels: approved, cla: yes, lgtm, size/L

#106 Replace rate limiter
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/L

#107 add formal API for APIserver cover/chaff requests from devices
  cmd/apiserver/main.go
  cmd/get-cover/main.go
  pkg/api/api.go
  pkg/controller/cover/cover.go
Labels: approved, lgtm, size/L

#112 Admin API Keys
  cmd/apiserver/main.go
  cmd/server/assets/apikeys.html
  pkg/controller/apikey/apikey.go
  pkg/controller/apikey/savekey.go
  pkg/controller/middleware/apikey.go
  pkg/database/authorized_app.go
  pkg/database/authorized_app_test.go
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/M

#111 Switch to redis-based rate limiting
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/config/api_server_config.go
  pkg/config/server_config.go
  pkg/ratelimit/config.go
  terraform/main.tf
  terraform/redis.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#115 update terraform/build for adminapi
  scripts/build
  scripts/deploy
  scripts/promote
  terraform/service_admin_apiserver.tf
Labels: approved, cla: yes, lgtm, size/L

#116 update readme file for API usage
  README.md
Labels: approved, cla: yes, lgtm, size/L

#118 Adds Tracking Information to Codes to allow auditing
  pkg/controller/issueapi/issue.go
  pkg/controller/middleware/apikey.go
  pkg/database/migrations.go
  pkg/database/vercode.go
  pkg/otp/code.go
Labels: approved, cla: yes, lgtm, size/M

#113 feat: add rate limiting per user email for admin
  cmd/server/main.go
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#120 Gracefully stop and cleanup servers
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/migrate/main.go
  cmd/server/main.go
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/L

#119 Move ipKeyFunc to allocate once
  cmd/server/main.go
Labels: approved, cla: yes, lgtm, size/XS

#126 Set and configure max conns
  terraform/README.md
  terraform/database.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#124 Make KMS and Redis regions configurable
  terraform/keys.tf
  terraform/redis.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#125 Add SMS interfaces and Twilio implementation
  pkg/sms/noop.go
  pkg/sms/sms.go
  pkg/sms/twilio.go
  pkg/sms/twilio_test.go
Labels: approved, cla: yes, lgtm, size/L

#127 Use server package to start servers
  .github/ISSUE_TEMPLATE/feature.md
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/config/admin_server_config.go
  pkg/config/api_server_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, size/L

#128 add unix timestamp for code expiry
  pkg/api/api.go
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/S

#129 Support reloading templates in dev
  cmd/server/main.go
  pkg/render/html.go
Labels: approved, cla: yes, lgtm, size/M

#130 Add more SMS functionality
  cmd/server/assets/home.html
  pkg/api/api.go
  pkg/controller/home/home.go
  pkg/controller/issueapi/issue.go
  pkg/database/database.go
  pkg/database/migrations.go
  pkg/database/sms_config.go
  pkg/database/sms_config_test.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  pkg/sms/noop.go
  pkg/sms/sms.go
  pkg/sms/twilio.go
  pkg/sms/twilio_test.go
Labels: approved, cla: yes, lgtm, size/L

#132 Stop running GH tests - we have prow now
  .github/workflows/stale.yml
  .github/workflows/test.yml
Labels: approved, cla: yes, lgtm, size/M

#131 Allow pulling secrets in the database layer
  cmd/add-sms-config/main.go
  cmd/add-users/main.go
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/migrate/main.go
  cmd/server/main.go
  go.mod
  pkg/controller/home/home.go
  pkg/controller/issueapi/issue.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/database_util.go
  pkg/database/sms_config.go
  pkg/database/sms_config_test.go
Labels: approved, cla: yes, lgtm, size/L

#135 Add deployment for Twilio
  docs/using-cloud-sql-proxy.md
  pkg/controller/home/home.go
  terraform/database.tf
  terraform/main.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/sms.tf
Labels: approved, cla: yes, lgtm, size/L

#136 Use chaff for handling fake requests
  README.md
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/get-cover/main.go
  go.mod
  go.sum
  pkg/api/api.go
  pkg/controller/cover/cover.go
Labels: approved, cla: yes, lgtm, size/L

#140 Stop using gorilla/context
  cmd/server/main.go
  go.mod
  go.sum
  pkg/controller/apikey/apikey.go
  pkg/controller/flash/flash.go
  pkg/controller/home/home.go
  pkg/controller/issueapi/issue.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/html/html.go
  pkg/controller/user.go
  pkg/controller/user/deleteuser.go
  pkg/controller/user/saveuser.go
  pkg/controller/user/user.go
Labels: approved, cla: yes, lgtm, size/L

#142 Followup PR comments
  cmd/add-realm/main.go
  pkg/controller/user.go
  pkg/database/sms_config.go
Labels: approved, cla: yes, lgtm, size/M

#144 add logging handler on servers
  cmd/adminapi/main.go
  cmd/apiserver/main.go
Labels: approved, cla: yes, lgtm, size/XS

#145 add whaught to owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#146 Fix up indexes after MT upgrade.
  pkg/database/authorized_app.go
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/M

#147 Make realm changing nicer by defaulting to currently selected.
  cmd/server/assets/selectrealm.html
  pkg/controller/realm/select.go
Labels: approved, cla: yes, lgtm, size/S

#148 update docs to mention realms, add-users script fixes
  README.md
  cmd/add-users/main.go
Labels: approved, cla: yes, lgtm, size/S

#150 Add basic realm admin page.
  cmd/server/assets/header.html
  cmd/server/assets/realm.html
  cmd/server/main.go
  pkg/controller/realmadmin/index.go
  pkg/controller/realmadmin/save.go
Labels: approved, cla: yes, lgtm, size/L

#154 Update envconfig and enserver
  cmd/add-realm/main.go
  cmd/add-sms-config/main.go
  cmd/add-users/main.go
  cmd/migrate/main.go
  go.mod
  go.sum
  pkg/config/admin_server_config.go
  pkg/config/api_server_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/config.go
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, size/L

#155 Fix presubmit test bug to surface error message better
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/S

#156 Switch to gorilla sessions and encrypted cookies
  cmd/server/assets/selectrealm.html
  cmd/server/main.go
  go.mod
  pkg/config/server_config.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/realm.go
  pkg/controller/realm/cookie.go
  pkg/controller/realm/index.go
  pkg/controller/realm/realm.go
  pkg/controller/realm/select.go
  pkg/controller/session/create.go
  pkg/controller/session/delete.go
  pkg/controller/session/session.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XL

#159 Update deps to pull in new secret resolver
  go.mod
  go.sum
  pkg/database/database_util.go
  pkg/database/sms_config_test.go
Labels: approved, cla: yes, lgtm, size/M
