Repository google/exposure-notifications-verification-server, pull requests merged in 2020-10, with the labels that each got.

#725 Fix some bad time math
  pkg/controller/middleware/realm.go
Labels: approved, cla: yes, lgtm, size/XS

#724 Doc cleanup largely based on spelling/grammar check
  docs/realm_guide.md
  docs/user_guide.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#727 Actually use factor when setting limit
  pkg/controller/modeler/modeler.go
Labels: approved, cla: yes, lgtm, size/XS

#728 Add service networking dependency for VPC connector
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#730 Fix change-password back link
  cmd/server/assets/login/change-password.html
  cmd/server/assets/login/register-phone.html
  pkg/controller/session.go
Labels: approved, cla: yes, lgtm, size/XS

#729 Trim whitespace from user-input
  cmd/server/assets/login/change-password.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  pkg/controller/admin/users.go
  pkg/controller/login/reset_password.go
  pkg/controller/login/select_password.go
  pkg/controller/user/create.go
  pkg/controller/user/update.go
Labels: approved, cla: yes, lgtm, size/M

#723 Create a grace period before MFA is required
  cmd/server/assets/realmadmin/_form_security.html
  cmd/server/assets/users/import.html
  pkg/controller/middleware/mfa.go
  pkg/controller/realmadmin/settings.go
  pkg/database/duration.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#731 Always include build_id and build_tag in metrics
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/metrics.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
  pkg/controller/verifyapi/metrics.go
  pkg/controller/verifyapi/verify.go
  pkg/database/database.go
  pkg/database/metrics.go
  pkg/observability/observability.go
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/L

#733 Fix cleanup nil pointer dereference.
  pkg/controller/cleanup/cleanup.go
Labels: approved, cla: yes, lgtm, size/S

#734 Show skip link properly with grace period
  cmd/server/assets/login/register-phone.html
  pkg/controller/login/register.go
  pkg/controller/middleware/mfa.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#736 Include knative info in metrics if present
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/M

#737 Disable editing user email
  cmd/server/assets/users/_form.html
  pkg/controller/user/update.go
Labels: approved, cla: yes, lgtm, size/XS

#739 Nit: switch user -> currentUser
  pkg/controller/admin/realms.go
  pkg/controller/codestatus/logic.go
  pkg/controller/issueapi/issue.go
  pkg/controller/login/change_password.go
  pkg/controller/login/select.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/emailverified.go
  pkg/controller/middleware/realm.go
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/M

#741 Respond to paste, keyup, and change
  cmd/server/assets/login/change-password.html
  cmd/server/assets/login/select-password.html
Labels: approved, cla: yes, lgtm, size/XS

#743 Attempt to fix realm quota alert
  cmd/server/assets/realmadmin/_form_abuse_prevention.html
  go.mod
  go.sum
  pkg/controller/issueapi/issue.go
  pkg/controller/realmadmin/express.go
  pkg/controller/realmadmin/settings.go
Labels: approved, cla: yes, lgtm, size/L

#738 Add appstore url to mobile apps.
  cmd/server/assets/mobileapps/_app.html
  cmd/server/assets/mobileapps/show.html
  pkg/controller/mobileapps/create.go
  pkg/controller/mobileapps/update.go
  pkg/database/migrations.go
  pkg/database/mobile_app.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/M

#745 Too many attempts message
  cmd/server/assets/login/login.html
  internal/firebase/error.go
  pkg/controller/login/reset_password.go
Labels: approved, cla: yes, lgtm, size/S

#746 Update deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#749 Deprecate old routing for resetPassword / verifyemail
  cmd/server/main.go
Labels: approved, cla: yes, lgtm, size/S

#748 Minor tweaks
  cmd/server/assets/login/login.html
  cmd/server/assets/users/import.html
Labels: approved, cla: yes, lgtm, size/XS

#747 Refactor the view registration code in verification server.
  pkg/controller/certapi/certapi.go
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/metrics.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/cleanup/metrics.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/issueapi.go
  pkg/controller/issueapi/metrics.go
  pkg/controller/verifyapi/metrics.go
  pkg/controller/verifyapi/verify.go
  pkg/controller/verifyapi/verifyapi.go
  pkg/database/database.go
  pkg/database/metrics.go
Labels: approved, cla: yes, lgtm, size/XL

#750 Unify custom host handling logic
  terraform/README.md
  terraform/alerting/probers.tf
  terraform/alerting/variables.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/variables.tf
  terraform/verification-lb.tf
Labels: approved, cla: yes, lgtm, size/L

#753 Lock merged PRs and closed issues after a day
  .github/workflows/lock.yml
Labels: approved, cla: yes, lgtm, size/S

#755 Update Terraform quick setup
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#714 Add integration tests for verification server
  pkg/config/integration_config.go
  pkg/integration/clients.go
  pkg/integration/helpers.go
  pkg/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/XL

#756 Recreate firebase user, no metric
  cmd/server/assets/users/show.html
  pkg/controller/login/reset_password.go
  pkg/controller/user/create.go
  pkg/controller/user/reset_password.go
  pkg/controller/user/show.go
Labels: approved, cla: yes, lgtm, size/L

#757 Custom email verify page
  cmd/server/assets/login/verify-email-check.html
  cmd/server/main.go
  internal/firebase/verify_password_reset_code.go
  pkg/controller/login/verify_email.go
Labels: approved, cla: yes, lgtm, size/M

#744 Add presubmit check for tabs in html files.
  Makefile
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/S

#759 Log metric for in use hosts
  terraform/alerting/monitoring.tf
Labels: approved, cla: yes, lgtm, size/S

#758 Record metric for recreated firebase user
  pkg/controller/login/reset_password.go
  pkg/controller/metrics.go
  pkg/controller/user/reset_password.go
  pkg/controller/user/show.go
Labels: approved, cla: yes, lgtm, size/M

#761 Forgot project field for requests_by_host metric
  terraform/alerting/monitoring.tf
Labels: approved, cla: yes, lgtm, size/XS

#765 Handle edge case when realm quota is first enabled
  cmd/server/assets/realmadmin/_form_abuse_prevention.html
  pkg/config/admin_server_config.go
  pkg/config/server_config.go
  pkg/controller/realmadmin/settings.go
Labels: approved, cla: yes, lgtm, size/M

#770 Add chaodaig as approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#762 Don't fail terraform if no custom domain supplied
  terraform/verification-lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#767 Fix bad ens:// protocol (E_MISSING_ONE_SLASH)
  pkg/controller/redirect/index.go
  pkg/controller/redirect/index_test.go
Labels: approved, cla: yes, lgtm, size/M

#769 Make prevent_destroy configurable
  terraform/database.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#772 Remove prevent_destroy
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#774 List recent codes on code-status page
  cmd/server/assets/codestatus/index.html
  pkg/controller/codestatus/expire.go
  pkg/controller/codestatus/index.go
  pkg/controller/codestatus/show.go
  pkg/database/token.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/L

#763 Move verification server related monitoring configs to a sub folder.
  terraform/alerting/main.tf
  terraform/alerting/verification-server/dashboards/e2e.yaml
  terraform/alerting/verification-server/dashboards/verification-server.yaml
  terraform/alerting/verification-server/monitoring.tf
  terraform/alerting/verification-server/notifications.tf
  terraform/alerting/verification-server/probers.tf
  terraform/alerting/verification-server/variables.tf
  terraform/alerting/verification-server/workspace.tf
  terraform/verification-lb.tf
Labels: approved, cla: yes, lgtm, size/M

#777 Switch show-code to GET
  cmd/server/assets/codestatus/index.html
  cmd/server/main.go
  pkg/controller/codestatus/show.go
Labels: approved, cla: yes, lgtm, size/M

#776 Client-side password-reset
  cmd/server/assets/firebase.html
  cmd/server/assets/login/reset-password.html
  pkg/controller/login/reset_password.go
Labels: approved, cla: yes, lgtm, size/M

#778 Don't require Firebase TOS and PP
  docs/development.md
  pkg/config/server_config.go
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#780 Show code createdAt in local time
  cmd/server/assets/codestatus/index.html
Labels: approved, cla: yes, lgtm, size/XS

#775 Add a /request metric with blame/result field.
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/metrics.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/M

#781 Move password-reset to the client for users/show in admin
  cmd/server/assets/login/reset-password.html
  cmd/server/assets/users/show.html
  cmd/server/main.go
  internal/firebase/password_reset_email.go
  pkg/controller/user/create.go
  pkg/controller/user/importbatch.go
  pkg/controller/user/reset_password.go
  pkg/controller/user/show.go
Labels: approved, cla: yes, lgtm, size/M

#782 use redirect hostname to lookup realm for correct mobile app
  cmd/enx-redirect/main.go
  pkg/config/redirect_config.go
  pkg/controller/associated/android.go
  pkg/controller/associated/index.go
  pkg/controller/associated/ios.go
  pkg/database/mobile_app.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#783 wrap errors
  pkg/controller/associated/android.go
  pkg/controller/associated/ios.go
Labels: approved, cla: yes, lgtm, size/XS

#784 Recent codes index
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/S

#785 Add /request metric.
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
  pkg/controller/verifyapi/metrics.go
  pkg/controller/verifyapi/verify.go
Labels: approved, cla: yes, lgtm, size/M

#786 Add log errors for e2e fail
  cmd/e2e-runner/main.go
Labels: approved, cla: yes, lgtm, size/S

#764 Manage metric descriptor in terraform
  terraform/alerting/variables.tf
  terraform/alerting/verification-server/metrics.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#794 Add /api/issue/sms_request metric.
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/M

#790 Update firebase version, remove UI stuff
  README.md
  cmd/server/assets/firebase.html
Labels: approved, cla: yes, lgtm, size/S

#792 Remove unnecessary metric increment in validateToken()
  pkg/controller/certapi/certapi.go
Labels: approved, cla: yes, lgtm, size/XS

#789 Use new metrics in dashboards
  terraform/alerting/verification-server/dashboards/e2e.yaml
  terraform/alerting/verification-server/dashboards/verification-server.yaml
  terraform/alerting/verification-server/metrics.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#766 Adding support for App Links, fallback to Play Store.
  cmd/enx-redirect/main.go
  pkg/controller/redirect/appstore.go
  pkg/controller/redirect/index.go
  pkg/controller/redirect/index_test.go
  pkg/controller/redirect/redirect.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#795 Add /api/issue/realm_token metric.
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
Labels: approved, cla: yes, lgtm, size/S

#793 Remove old metrics in /api/certificate API
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/metrics.go
Labels: approved, cla: yes, lgtm, size/M

#796 Allow custom email server for invitations
  cmd/server/main.go
  pkg/config/server_config.go
  pkg/controller/user/importbatch.go
  pkg/controller/user/reset_password.go
  pkg/controller/user/user.go
  pkg/email/config.go
  pkg/email/firebase.go
  pkg/email/smtp.go
Labels: approved, cla: yes, lgtm, size/L

#798 Nit: typo
  cmd/server/assets/admin/realms/edit.html
  cmd/server/assets/admin/realms/new.html
  cmd/server/assets/admin/users/new.html
  cmd/server/assets/mobileapps/_app.html
  cmd/server/assets/realm.html
  cmd/server/assets/realmkeys.html
  cmd/server/assets/users/_form.html
  pkg/controller/admin/realms.go
Labels: approved, cla: yes, lgtm, size/M

#797 Generate invitation email from template
  cmd/server/assets/email/_plainheader.html
  cmd/server/assets/email/default_invitation.html
  cmd/server/main.go
  pkg/controller/user/importbatch.go
  pkg/controller/user/reset_password.go
  pkg/email/config.go
  pkg/email/noop.go
  pkg/email/smtp.go
  pkg/render/email.go
Labels: approved, cla: yes, lgtm, size/L

#800 Changing some words
  cmd/server/assets/email/_plainheader.html
  cmd/server/assets/email/default_invite.html
Labels: approved, cla: yes, lgtm, size/XS

#801 Fix realm token related metrics in /api/issue.
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
Labels: approved, cla: yes, lgtm, size/S

#803 Fixing a nil pointer in e2e
  cmd/e2e-runner/main.go
Labels: approved, cla: yes, lgtm, size/XS

#802 Also modify how /api/issue/realm_token_latest is recorded.
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
Labels: approved, cla: yes, lgtm, size/XS

#804 Use new /realm_token_latest metric in the dashboard.
  terraform/alerting/verification-server/dashboards/.verification-server.yaml.swp
  terraform/alerting/verification-server/dashboards/verification-server.yaml
  terraform/alerting/verification-server/metrics.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#806 Fix pagination off-by-one
  pkg/controller/user/index.go
Labels: approved, cla: yes, lgtm, size/M

#807 double checking things
  cmd/server/assets/email/_plainheader.html
  pkg/controller/user/index.go
Labels: approved, cla: yes, lgtm, size/XS

#808 Delete .verification-server.yaml.swp
  terraform/alerting/verification-server/dashboards/.verification-server.yaml.swp
Labels: approved, cla: yes, lgtm, size/XS

#809 Add .swp file to .gitignore
  .gitignore
Labels: approved, cla: yes, lgtm, size/XS

#813 Cleanup verify API metrics.
  pkg/controller/verifyapi/metrics.go
  pkg/controller/verifyapi/verify.go
Labels: approved, cla: yes, lgtm, size/M

#812 Cleanup issue API metrics
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
Labels: approved, cla: yes, lgtm, size/M

#815 Update key server dep
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#817 nil panic
  pkg/controller/codestatus/show.go
Labels: approved, cla: yes, lgtm, size/XS

#822 Remove quota related metrics.
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
Labels: approved, cla: yes, lgtm, size/S

#823 Fix seed script (URL is required)
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XS

#829 Return on realm lookup error
  cmd/server/assets/400.html
  pkg/controller/controller.go
  pkg/controller/redirect/index.go
Labels: approved, cla: yes, lgtm, size/M

#828 Add a per-realm-per-user chart on the stats page.
  cmd/server/assets/realmadmin/show.html
  pkg/controller/realmadmin/show.go
  pkg/controller/realmadmin/show_test.go
  pkg/database/realm.go
  pkg/database/realm_test.go
  pkg/database/user_stats.go
Labels: approved, cla: yes, lgtm, size/L

#825 Make alert names consistent
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/XS

#832 e2e test runner random suffix 32 chars instead of picking an int under 10000
  cmd/e2e-runner/main.go
Labels: approved, cla: yes, lgtm, size/S

#833 Move email send out to controller
  cmd/server/main.go
  pkg/controller/email_compose.go
  pkg/controller/user/controller.go
  pkg/controller/user/importbatch.go
  pkg/controller/user/reset_password.go
  pkg/email/config.go
  pkg/email/firebase.go
  pkg/email/noop.go
  pkg/email/smtp.go
Labels: approved, cla: yes, lgtm, size/L

#834 Give system admins ability to clear caches
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/enx-redirect/main.go
  cmd/modeler/main.go
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/caches/index.html
  cmd/server/main.go
  pkg/cache/cacher.go
  pkg/cache/cacher_test.go
  pkg/cache/in_memory.go
  pkg/cache/noop.go
  pkg/cache/redis.go
  pkg/cache/redis_test.go
  pkg/controller/admin/admin.go
  pkg/controller/admin/caches.go
  pkg/controller/apikey/show.go
  pkg/controller/associated/index.go
  pkg/controller/issueapi/issue.go
  pkg/controller/jwks/jwks.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/realm.go
  pkg/controller/modeler/modeler.go
  pkg/controller/realmadmin/settings.go
  pkg/controller/realmadmin/show.go
  pkg/controller/redirect/index.go
  pkg/controller/user/show.go
  pkg/database/authorized_app_stats.go
  pkg/database/database.go
  pkg/database/realm.go
  pkg/integration/helpers.go
  pkg/keyutils/public_keys.go
Labels: approved, cla: yes, lgtm, size/XL

#835 Fix race in TestIssueToken
  pkg/database/token_test.go
Labels: approved, cla: yes, lgtm, size/XS

#836 Add missing copyrights to files, and add a presubmit check.
  Makefile
  docs/images/architecture/main.go
  pkg/controller/healthz.go
  pkg/controller/realmadmin/show_test.go
  pkg/database/countries.go
  pkg/observability/observability.go
  pkg/ratelimit/limitware/middleware.go
  pkg/sms/twilio_test.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/L

#840 When a date is clicked in the realm, highlight day in per-user data.
  cmd/server/assets/realmadmin/show.html
Labels: approved, cla: yes, lgtm, size/M

#843 make url optional
  pkg/database/mobile_app.go
  pkg/database/mobile_app_test.go
Labels: approved, cla: yes, lgtm, size/S

#845 Use Android intent links in place of bouncing.
  pkg/controller/redirect/appstore.go
  pkg/controller/redirect/index.go
  pkg/controller/redirect/index_test.go
Labels: approved, cla: yes, lgtm, size/L

#846 Allow blank entry for URL.
  pkg/database/mobile_app.go
Labels: approved, cla: yes, lgtm, size/XS

#847 Use midnight when updating stats while creating a VerificationCode
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  pkg/timeutils/midnight.go
Labels: approved, cla: yes, lgtm, size/L

#850 Depend on the ENS' copy of timeutils
  go.mod
  go.sum
  pkg/database/vercode.go
  pkg/timeutils/midnight.go
Labels: approved, cla: yes, lgtm, size/M

#814 Update/deduplicate metrics in the cleanup handler.
  pkg/controller/certapi/certificate.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/cleanup/metrics.go
  pkg/controller/issueapi/issue.go
  pkg/controller/verifyapi/verify.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/L

#852 Set default to tls 1.2
  terraform/verification-lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#853 Typo
  terraform/verification-lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#855 Limit redirector LB to TLS 1.2+
  terraform/redirect-lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#851 Fix uses of time.Truncate
  pkg/controller/issueapi/issue.go
  pkg/controller/realmadmin/show_test.go
  pkg/database/authorized_app.go
  pkg/database/realm.go
  pkg/database/realm_test.go
  pkg/database/token.go
  pkg/database/token_test.go
  pkg/database/user.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/M

#856 Fix errorcode conversion to string
  pkg/controller/user/importbatch.go
Labels: approved, cla: yes, lgtm, size/XS

#849 Use realm email to send mail templates
  cmd/server/assets/email/default_email_verify.html
  cmd/server/assets/email/default_reset_password.html
  cmd/server/assets/login/verify-email.html
  cmd/server/assets/realmadmin/_form_email.html
  cmd/server/assets/realmadmin/edit.html
  cmd/server/main.go
  pkg/config/server_config.go
  pkg/controller/email_compose.go
  pkg/controller/login/reset_password.go
  pkg/controller/login/verify_email_receive.go
  pkg/controller/login/verify_email_send.go
  pkg/controller/realmadmin/express.go
  pkg/controller/realmadmin/settings.go
  pkg/controller/user/controller.go
  pkg/controller/user/importbatch.go
  pkg/controller/user/send_invite.go
  pkg/database/database.go
  pkg/database/email_config.go
  pkg/database/email_config_test.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/sms_config.go
  pkg/email/config.go
Labels: approved, cla: yes, lgtm, size/XXL

#859 System email settings
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/email/show.html
  cmd/server/main.go
  pkg/controller/admin/email.go
Labels: approved, cla: yes, lgtm, size/L

#860 e2e test script is guarded against prod resources
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/S

#861 More info on error for scripts/terraform.sh
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#862 E2E test: update usage of gcloud to prevent breakage from future breaking API changes
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/S

#863 Support multiple keys for HMAC secrets
  docs/production.md
  terraform/database.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#841 E2E tests for incremental deployment
  Makefile
  pkg/config/integration_config.go
  pkg/integration/integration_test.go
  pkg/testsuite/clients.go
  pkg/testsuite/e2e.go
  pkg/testsuite/helpers.go
  pkg/testsuite/integration.go
  pkg/testsuite/suite.go
  scripts/e2e-test.sh
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/XL

#870 Document setting versioning and lifecycle on Terraform state
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#874 Realm not required for email verify
  cmd/server/main.go
Labels: approved, cla: yes, lgtm, size/XS

#875 Backup the Cloud SQL database to GCS every 6 hours
  terraform/database.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#876 change log message when redirect doesn't redirect
  pkg/controller/redirect/index.go
Labels: approved, cla: yes, lgtm, size/XS

#877 Retention policy and versioning are mutually exclusive
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#880 Move JS and CSS external
  cmd/adminapi/main.go
  cmd/server/assets/admin/caches/index.html
  cmd/server/assets/admin/email/show.html
  cmd/server/assets/admin/info.html
  cmd/server/assets/admin/realms/edit.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/realms/new.html
  cmd/server/assets/admin/sms/show.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/new.html
  cmd/server/assets/apikeys/edit.html
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/apikeys/new.html
  cmd/server/assets/apikeys/show.html
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/login/account.html
  cmd/server/assets/login/change-password.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/reset-password.html
  cmd/server/assets/login/select-password.html
  cmd/server/assets/login/select-realm.html
  cmd/server/assets/login/signout.html
  cmd/server/assets/login/verify-email-check.html
  cmd/server/assets/login/verify-email.html
  cmd/server/assets/mobileapps/edit.html
  cmd/server/assets/mobileapps/index.html
  cmd/server/assets/mobileapps/new.html
  cmd/server/assets/mobileapps/show.html
  cmd/server/assets/realm.html
  cmd/server/assets/realmadmin/edit.html
  cmd/server/assets/realmadmin/events.html
  cmd/server/assets/realmadmin/show.html
  cmd/server/assets/realmkeys.html
  cmd/server/assets/static/css/application.css
  cmd/server/assets/static/js/application.js
  cmd/server/assets/users/edit.html
  cmd/server/assets/users/import.html
  cmd/server/assets/users/index.html
  cmd/server/assets/users/new.html
  cmd/server/assets/users/show.html
  cmd/server/main.go
  pkg/controller/issueapi/issueapi.go
  pkg/database/user.go
  pkg/testsuite/integration.go
Labels: approved, cla: yes, lgtm, size/XL

#879 Move routes for server into internal package
  cmd/server/main.go
  internal/routes/routes.go
  internal/routes/server.go
Labels: approved, cla: yes, lgtm, size/XL

#884 Rename all e2e test scripts to make people not want to run them locally
  .gitignore
  scripts/ci-e2e-test.sh
  scripts/ci-terraform.sh
  terraform-e2e-ci/README.md
  terraform-e2e-ci/main.tf
Labels: approved, cla: yes, lgtm, size/S

#887 Fix verify email flow with no realm
  cmd/server/assets/email/default_email_verify.html
  cmd/server/assets/login/verify-email.html
  internal/routes/server.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/M

#889 add help text around iOS ENX
  cmd/server/assets/mobileapps/_app.html
Labels: approved, cla: yes, lgtm, size/S

#888 Add output for backup command
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#883 thread test date all the way through
  pkg/api/api.go
  pkg/controller/issueapi/issue.go
  pkg/controller/verifyapi/verify.go
  pkg/database/migrations.go
  pkg/database/token.go
  pkg/database/token_test.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  pkg/otp/code.go
Labels: approved, cla: yes, lgtm, size/L

#891 Don't output callback registration logs outside of debug mode
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/S

#878 Revamp the realm stats
  cmd/server/assets/realmadmin/show.html
  internal/routes/server.go
  pkg/controller/realmadmin/show.go
  pkg/controller/realmadmin/stats.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/L

#892 update api docs w/ new fields
  docs/api.md
Labels: approved, cla: yes, lgtm, size/XS

#893 Record metrics in e2e runner.
  pkg/clients/e2e.go
  pkg/clients/metrics.go
  pkg/observability/observability.go
  terraform-e2e/state.tf
Labels: approved, cla: yes, lgtm, size/L

#896 Nit: use ResultNotOK() for result label.
  pkg/controller/cleanup/cleanup.go
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/XS

#897 Pull CSRF token from metadata
  cmd/server/assets/header.html
  cmd/server/assets/static/js/application.js
  pkg/controller/middleware/csrf.go
Labels: approved, cla: yes, lgtm, size/S

#898 Fix context race when sending email
  pkg/email/smtp.go
Labels: approved, cla: yes, lgtm, size/XS

#900 Make it possible to save system email configs
  cmd/server/assets/admin/email/show.html
Labels: approved, cla: yes, lgtm, size/XS

#899 Use text templates for emails (not-html)
  cmd/server/assets/email/_plainheader.txt
  cmd/server/assets/email/default_email_verify.txt
  cmd/server/assets/email/default_invite.txt
  cmd/server/assets/email/default_reset_password.txt
  pkg/render/email.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/M

#903 remove content transfer type
  cmd/server/assets/email/_plainheader.txt
Labels: approved, cla: yes, lgtm, size/XS

#902 Introduce auth provider interface
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/login/reset-password.html
  cmd/server/assets/login/verify-email-check.html
  cmd/server/assets/login/verify-email.html
  cmd/server/assets/users/show.html
  cmd/server/main.go
  internal/auth/auth.go
  internal/auth/firebase.go
  internal/auth/session.go
  internal/firebase/verify_email.go
  internal/routes/server.go
  pkg/controller/admin/admin.go
  pkg/controller/admin/users.go
  pkg/controller/email.go
  pkg/controller/email_compose.go
  pkg/controller/login/controller.go
  pkg/controller/login/login.go
  pkg/controller/login/reset_password.go
  pkg/controller/login/select_password.go
  pkg/controller/login/session.go
  pkg/controller/login/verify_email_send.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/emailverified.go
  pkg/controller/middleware/mfa.go
  pkg/controller/session.go
  pkg/controller/user/controller.go
  pkg/controller/user/create.go
  pkg/controller/user/importbatch.go
  pkg/controller/user/reset_password.go
  pkg/controller/user/send_invite.go
  pkg/controller/user/show.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/XXL

#904 fix email from string
  pkg/controller/admin/users.go
  pkg/controller/email.go
Labels: approved, cla: yes, lgtm, size/XS

#908 Increase e2e test timeout.
  pkg/clients/e2e.go
Labels: approved, cla: yes, lgtm, size/XS

#909 Clean up deleted API keys after 1 week
  pkg/config/cleanup_server_config.go
  pkg/controller/cleanup/cleanup.go
  pkg/database/authorized_app.go
Labels: approved, cla: yes, lgtm, size/M

#913 Try and fix use case of burst capacity
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/XS

#914 Validate and populate realm email templates
  pkg/controller/email.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#915 Include email templates / useSystem in auditing
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#918 Create alerts using MQL
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/alerts/RealmTokenRemainingCapacityLow.yaml
  terraform/alerting/verification-server/scripts/upsert_alert_policy.sh
Labels: approved, cla: yes, lgtm, size/L

#921 Add alert on e2e test failure ratio.
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/alerts/E2ETestErrorRatioHigh.yaml
  terraform/alerting/verification-server/metrics.tf
Labels: approved, cla: yes, lgtm, size/M

#917 Allow override of invite template
  cmd/server/assets/email/_plainheader.txt
  cmd/server/assets/email/default_email_verify.txt
  cmd/server/assets/email/default_invite.txt
  cmd/server/assets/email/default_reset_password.txt
  cmd/server/assets/realmadmin/_form_codes.html
  cmd/server/assets/realmadmin/_form_email.html
  pkg/controller/email.go
  pkg/controller/realmadmin/settings.go
Labels: approved, cla: yes, lgtm, size/M

#925 change default allowed back dating to 27 days (from 14)
  pkg/config/admin_server_config.go
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, size/XS

#924 Add notification channel to the MQL based alerts.
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/scripts/upsert_alert_policy.sh
Labels: approved, cla: yes, lgtm, size/S

#907 Cleanup metrics in ratelimit middleware
  pkg/ratelimit/limitware/metrics.go
  pkg/ratelimit/limitware/middleware.go
  terraform/alerting/verification-server/dashboards/verification-server.yaml
  terraform/alerting/verification-server/metrics.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/L

#881 Add test harness for headless browser testing
  cmd/server/assets/home.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  go.mod
  go.sum
  internal/auth/auth.go
  internal/auth/firebase.go
  internal/auth/local.go
  internal/browser/browser.go
  internal/browser/executor.go
  internal/envstest/envstest.go
  internal/envstest/random.go
  internal/envstest/server.go
  internal/project/root.go
  pkg/controller/home/home_test.go
  pkg/controller/login/session.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/sessions.go
  pkg/database/database_util.go
Labels: approved, cla: yes, lgtm, size/XXL

#927 Recently issued codes are YOURs
  cmd/server/assets/codestatus/index.html
Labels: approved, cla: yes, lgtm, size/XS

#929 Scope mobileapp lookup to the realm
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/M

#911 Add alerting playbooks
  docs/playbooks/Elevated_5xx.md
  docs/playbooks/Elevated_Latency_Greater_than_2s.md
  docs/playbooks/Elevated_Rate_Limited_Count.md
  docs/playbooks/Host_Down.md
  docs/playbooks/Realm_Token_Capacity_Utilization_Above_Threshold.md
  docs/playbooks/index.md
Labels: approved, cla: yes, lgtm, size/L

#930 Remove myself from owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#931 add ZERO WIDTH NO-BREAK SPACE to our cut set
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#932 Fix the notification channel flag.
  terraform/alerting/verification-server/scripts/upsert_alert_policy.sh
Labels: approved, cla: yes, lgtm, size/XS

#934 extend default symptom range to 28, from 27 days
  pkg/config/admin_server_config.go
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, size/XS

#935 Download stats in a card at the end?
  cmd/server/assets/realmadmin/show.html
Labels: approved, cla: yes, lgtm, size/S

#922 Return CSV if requested from realm stats.
  internal/routes/server.go
  pkg/controller/realmadmin/show.go
  pkg/database/realm.go
  pkg/database/realm_stats.go
Labels: approved, cla: yes, lgtm, size/L

#936 Bump key server to v0.15.0
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#937 Enable BinaryAuth and Container Analysis APIs
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS
