Repository google/exposure-notifications-verification-server, pull requests merged in 2020-11, with the labels that each got.

#947 Run containers as nobody
  builders/build.yaml
  builders/enx-redirect.dockerfile
  builders/passwd
  builders/server.dockerfile
  builders/service.dockerfile
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/M

#948 Use super-trim all over
  internal/project/trim.go
  internal/project/trim_test.go
  pkg/controller/admin/users.go
  pkg/controller/login/select_password.go
  pkg/controller/user/create.go
  pkg/controller/user/update.go
  pkg/database/authorized_app.go
  pkg/database/database.go
  pkg/database/mobile_app.go
  pkg/database/realm.go
  pkg/database/user.go
  pkg/database/vercode.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/L

#951 Show mobile apps in system admin - Part 1
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/mobileapps/show.html
  internal/routes/server.go
  pkg/controller/admin/mobile_apps.go
  pkg/database/mobile_app.go
Labels: approved, cla: yes, lgtm, size/L

#950 Use MQL to define RealmTokenRemainingCapacityLow alert.
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/alerts/RealmTokenRemainingCapacityLow.yaml
  terraform/alerting/verification-server/metrics.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/L

#953 Add generic pagination functionality
  cmd/server/assets/shared/_pagination.html
  internal/browser/executor.go
  pkg/controller/middleware/currentpath.go
  pkg/controller/middleware/template.go
  pkg/database/pagination.go
  pkg/pagination/pagination.go
Labels: approved, cla: yes, lgtm, size/L

#943 Generalize the RecordLatency function to be reused later.
  pkg/clients/e2e.go
  pkg/observability/observability.go
Labels: approved, cla: yes, lgtm, size/M

#944 Record latency in our API endpoint
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/metrics.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/cleanup/metrics.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
  pkg/controller/verifyapi/metrics.go
  pkg/controller/verifyapi/verify.go
Labels: approved, cla: yes, lgtm, size/L

#956 Disable colored output for Terraform in CI
  scripts/ci-terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#949 add debug logging to device APIs
  pkg/controller/certapi/certificate.go
  pkg/database/token.go
  pkg/database/vercode.go
  pkg/otp/code_test.go
Labels: approved, cla: yes, lgtm, size/M

#957 Define "Elevated latency" error using MQL.
  terraform/alerting/main.tf
  terraform/alerting/variables.tf
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/monitoring.tf
  terraform/alerting/verification-server/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#955 Paginate mobile apps
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/mobileapps/edit.html
  cmd/server/assets/mobileapps/index.html
  cmd/server/assets/mobileapps/new.html
  cmd/server/assets/mobileapps/show.html
  pkg/controller/mobileapps/create.go
  pkg/controller/mobileapps/create_test.go
  pkg/controller/mobileapps/index.go
  pkg/controller/mobileapps/show.go
  pkg/controller/mobileapps/update.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#958 Fix the alerts
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#952 Show realm name with mobile app
  cmd/server/assets/admin/mobileapps/show.html
  pkg/controller/admin/mobile_apps.go
  pkg/database/mobile_app.go
  pkg/database/mobile_app_test.go
Labels: approved, cla: yes, lgtm, size/L

#960 Define E2E test alert in MQL
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/alerts/E2ETestErrorRatioHigh.yaml
  terraform/alerting/verification-server/scripts/upsert_alert_policy.sh
Labels: approved, cla: yes, lgtm, size/L

#962 Paginate mobile apps in system admin
  cmd/server/assets/admin/mobileapps/show.html
  pkg/controller/admin/mobile_apps.go
  pkg/database/mobile_app.go
  pkg/database/mobile_app_test.go
  pkg/database/pagination.go
Labels: approved, cla: yes, lgtm, size/M

#965 Set proper minimal provier version
  terraform/alerting/variables.tf
  terraform/alerting/verification-server/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#963 Define five_xx alerts in MQL
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#966 Add a test
  cmd/server/assets/users/_form.html
  cmd/server/assets/users/index.html
  pkg/controller/user/search_test.go
Labels: approved, cla: yes, lgtm, size/L

#971 Fail the test if closing the connection fails
  pkg/database/database.go
  pkg/database/database_util.go
Labels: approved, cla: yes, lgtm, size/S

#972 mobile apps link
  cmd/server/assets/admin/mobileapps/show.html
  cmd/server/assets/admin/realms/edit.html
Labels: approved, cla: yes, lgtm, size/S

#969 improve verification code retention and UUID checking
  go.mod
  pkg/config/cleanup_server_config.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/codestatus/logic.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/L

#970 Search bar for mobile apps
  cmd/server/assets/admin/mobileapps/show.html
  cmd/server/assets/users/index.html
  pkg/controller/admin/mobile_apps.go
  pkg/database/mobile_app.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#976 Allow system admin users to see/edit all users
  pkg/controller/user/delete.go
  pkg/controller/user/show.go
  pkg/controller/user/update.go
Labels: approved, cla: yes, lgtm, size/S

#968 Define probers alert in MQL.
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/probers.tf
Labels: approved, cla: yes, lgtm, size/M

#982 Move string trims out of controller
  cmd/server/assets/email/_plainheader.txt
  pkg/controller/admin/superusers.go
  pkg/controller/user/create.go
  pkg/controller/user/update.go
  pkg/database/mobile_app.go
  pkg/database/realm.go
  pkg/database/user.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/M

#983 Log TEKs when it failed to publish to key server.
  pkg/clients/e2e.go
Labels: approved, cla: yes, lgtm, size/XS

#967 Define rate limit alerts in MQL
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/L

#984 Rename Admin to SystemAdmin in users table
  cmd/server/assets/header.html
  cmd/server/assets/login/account.html
  internal/routes/server.go
  pkg/controller/admin/superusers.go
  pkg/controller/login/select.go
  pkg/controller/middleware/auth.go
  pkg/controller/user/show.go
  pkg/database/migrations.go
  pkg/database/realm_test.go
  pkg/database/user.go
  pkg/database/user_test.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#986 Audit delete user
  pkg/controller/admin/users.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/M

#987 Fix system admin query
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/XS

#992 Ensure emails are sanitized
  pkg/render/email.go
Labels: approved, cla: yes, lgtm, size/XS

#985 Show pills for realm/system admin
  cmd/server/assets/admin/users/index.html
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/S

#990 Link to system admin from realm select
  cmd/server/assets/header.html
  cmd/server/assets/login/select-realm.html
Labels: approved, cla: yes, lgtm, size/M

#988 Filter user search to system admins
  cmd/server/assets/admin/users/index.html
  pkg/controller/admin/users.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/M

#989 Make e2e-runner dashboard more useful.
  terraform/alerting/verification-server/dashboards/e2e.yaml
  terraform/alerting/verification-server/metrics.tf
Labels: approved, cla: yes, lgtm, size/M

#994 Merge the system admin and users page
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/superusers/index.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/new.html
  internal/routes/server.go
  pkg/controller/admin/users_list.go
  pkg/controller/admin/users_operations.go
Labels: approved, cla: yes, lgtm, size/L

#996 Update system-admin realm details page
  cmd/server/assets/admin/realms/edit.html
Labels: approved, cla: yes, lgtm, size/S

#999 Use scopes for filtering, update CSS
  cmd/server/assets/admin/mobileapps/index.html
  cmd/server/assets/admin/mobileapps/show.html
  cmd/server/assets/admin/realms/edit.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/new.html
  internal/routes/server.go
  pkg/controller/admin/admin.go
  pkg/controller/admin/mobile_apps.go
  pkg/controller/admin/realms.go
  pkg/controller/admin/users_list.go
  pkg/controller/admin/users_operations.go
  pkg/database/scopes.go
  pkg/database/user.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/XL

#1001 Move the log line.
  pkg/clients/e2e.go
Labels: approved, cla: yes, lgtm, size/XS

#1000 Limit number of non-deleted KMS signing keys on a realm
  cmd/server/assets/realmkeys.html
  pkg/controller/realmkeys/render.go
  pkg/controller/realmkeys/save.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/L

#997 Make it easy to select and admin as realm admin
  cmd/server/assets/admin/realms/edit.html
  internal/routes/server.go
  pkg/controller/admin/realms.go
Labels: approved, cla: yes, lgtm, size/M

#995 System admin user details
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/show.html
  cmd/server/assets/login/account.html
  cmd/server/assets/users/show.html
  internal/routes/server.go
  pkg/controller/admin/users_list.go
Labels: approved, cla: yes, lgtm, size/L

#1002 Ensure bits don't overflow
  pkg/database/authorized_app.go
  pkg/database/authorized_app_test.go
  pkg/database/database.go
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/S

#981 Optionally mirror dependent Docker Hub images
  pkg/database/database_util.go
  terraform/mirror/docker.tf
  terraform/mirror/main.tf
  terraform/mirror/service.tf
  terraform/mirror/variables.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1005 Authenticate to private Docker on CI
  pkg/cache/redis_test.go
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#1006 Switch user search over to scopes
  cmd/server/assets/users/index.html
  internal/routes/server.go
  pkg/controller/user/index.go
  pkg/controller/user/search.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#1010 stagger the e2e runners
  terraform/service_e2e_runner.tf
Labels: approved, cla: yes, lgtm, size/XS

#1011 E2e improvements
  cmd/e2e-runner/main.go
  pkg/clients/e2e.go
  terraform/service_e2e_runner.tf
Labels: approved, cla: yes, lgtm, size/S

#1007 Allow admins to add/remove users from other realms
  cmd/server/assets/admin/realms/edit.html
  cmd/server/assets/admin/users/show.html
  internal/routes/server.go
  pkg/controller/admin/realms.go
Labels: approved, cla: yes, lgtm, size/M

#1013 Update Realm_Token_Capacity_Utilization_Above_Threshold.md
  docs/playbooks/Realm_Token_Capacity_Utilization_Above_Threshold.md
Labels: approved, cla: yes, lgtm, size/XS

#1014 Support configuring regional database replicas
  terraform/database.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#1015 Fix missing commas
  terraform/alerting/verification-server/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1016 Cleanup unused terraform-e2e directory
  terraform-e2e/state.tf
Labels: approved, cla: yes, lgtm, size/XS

#1018 Allow searching API keys
  cmd/server/assets/apikeys/index.html
  pkg/controller/apikey/index.go
  pkg/database/realm.go
  pkg/database/scopes.go
Labels: approved, cla: yes, lgtm, size/M

#1019 Strictify the MQL queries that were broken.
  terraform/alerting/verification-server/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1020 Pagination for event/audit logs
  cmd/server/assets/realmadmin/events.html
  pkg/controller/realmadmin/events.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#1017 Only show 5 next/prev pages
  pkg/database/pagination.go
Labels: approved, cla: yes, lgtm, size/S

#1023 Search through events by time
  cmd/server/assets/realmadmin/events.html
  pkg/controller/realmadmin/events.go
  pkg/database/realm.go
  pkg/database/scopes.go
Labels: approved, cla: yes, lgtm, size/M

#1022 Add a warning at the top of metrics.tf.
  terraform/alerting/verification-server/metrics.tf
Labels: approved, cla: yes, lgtm, size/XS

#1024 Move /users to /realm/users
  cmd/server/assets/header.html
  cmd/server/assets/login/account.html
  cmd/server/assets/users/_form.html
  cmd/server/assets/users/import.html
  cmd/server/assets/users/index.html
  cmd/server/assets/users/new.html
  cmd/server/assets/users/show.html
  internal/routes/server.go
  pkg/controller/user/delete.go
  pkg/controller/user/search_test.go
  pkg/controller/user/update.go
Labels: approved, cla: yes, lgtm, size/M

#1027 Move realm db lists to ref system-wide queries
  pkg/controller/realmadmin/events.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#1030 Fix the group by field name.
  terraform/alerting/verification-server/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1021 Add titles everywhere
  pkg/controller/admin/caches.go
  pkg/controller/admin/email.go
  pkg/controller/admin/info.go
  pkg/controller/admin/mobile_apps.go
  pkg/controller/admin/realms.go
  pkg/controller/admin/sms.go
  pkg/controller/admin/users_list.go
  pkg/controller/admin/users_operations.go
  pkg/controller/apikey/create.go
  pkg/controller/apikey/index.go
  pkg/controller/apikey/show.go
  pkg/controller/apikey/update.go
  pkg/controller/codestatus/index.go
  pkg/controller/codestatus/show.go
  pkg/controller/context.go
  pkg/controller/home/home.go
  pkg/controller/login/account.go
  pkg/controller/login/change_password.go
  pkg/controller/login/login.go
  pkg/controller/login/register.go
  pkg/controller/login/reset_password.go
  pkg/controller/login/select.go
  pkg/controller/login/select_password.go
  pkg/controller/login/signout.go
  pkg/controller/login/verify_email_receive.go
  pkg/controller/login/verify_email_send.go
  pkg/controller/mobileapps/create.go
  pkg/controller/mobileapps/index.go
  pkg/controller/mobileapps/show.go
  pkg/controller/mobileapps/update.go
  pkg/controller/realmadmin/events.go
  pkg/controller/realmadmin/settings.go
  pkg/controller/realmadmin/show.go
  pkg/controller/realmkeys/render.go
  pkg/controller/redirect/index.go
  pkg/controller/user/import.go
  pkg/controller/user/index.go
  pkg/controller/user/show.go
  pkg/controller/user/update.go
Labels: approved, cla: yes, lgtm, size/M

#1031 Do not return successful JSON on SMS error
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/S

#1032 Strictify the alert query.
  terraform/alerting/verification-server/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1033 make date required default true for new realms
  cmd/server/assets/realmadmin/_form_codes.html
  pkg/controller/home/home_test.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/S

#1034 Remove metrics descriptor definitions in Terraform.
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/metrics.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/L

#1036 Fix system admin events search form
  cmd/server/assets/admin/events/index.html
Labels: approved, cla: yes, lgtm, size/S

#1035 Add realms search
  cmd/server/assets/admin/realms/index.html
  pkg/controller/admin/realms.go
  pkg/database/realm.go
  pkg/database/scopes.go
Labels: approved, cla: yes, lgtm, size/M

#1037 Fix misnamed log header
  pkg/controller/middleware/realm.go
Labels: approved, cla: yes, lgtm, size/XS

#1039 Make the magnifying-glass search icon clickable everywhere
  cmd/server/assets/admin/events/index.html
  cmd/server/assets/admin/mobileapps/index.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/users/index.html
Labels: approved, cla: yes, lgtm, size/S

#1042 Strictify the alert MQL query.
  terraform/alerting/verification-server/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1041 Update local provider to 2.0
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#1044 Unify search icons and UX
  cmd/server/assets/admin/events/index.html
  cmd/server/assets/admin/mobileapps/index.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/realmadmin/events.html
  cmd/server/assets/users/index.html
Labels: approved, cla: yes, lgtm, size/L

#1045 Clarify chaff response parsing
  docs/api.md
Labels: approved, cla: yes, lgtm, size/XS

#1043 Search mobile apps
  cmd/server/assets/mobileapps/index.html
  pkg/controller/mobileapps/index.go
  pkg/database/realm.go
  pkg/database/scopes.go
Labels: approved, cla: yes, lgtm, size/M

#1046 Update to latest en server
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/L

#1047 Fix user_id constraint
  internal/routes/server.go
Labels: approved, cla: yes, lgtm, size/XS

#1048 Run codeql on javascript too
  .github/workflows/codeql-analysis.yml
Labels: approved, cla: yes, lgtm, size/XS

#1051 Copy adjustments for consistency and specificity
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/realmadmin/show.html
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1053 Add tests for system admin routes
  internal/routes/server.go
  internal/routes/server_test.go
Labels: approved, cla: yes, lgtm, size/L

#1054 Add noreferrer to external links
  cmd/server/assets/mobileapps/show.html
Labels: approved, cla: yes, lgtm, size/XS

#1059 Run codeql on interval
  .github/workflows/codeql-analysis.yml
Labels: approved, cla: yes, lgtm, size/XS

#1058 Add more routing tests
  internal/routes/server.go
  internal/routes/server_test.go
  pkg/controller/jwks/jwks.go
Labels: approved, cla: yes, lgtm, size/L

#1057 Export users to CSV
  cmd/server/assets/users/import.html
  internal/routes/server.go
  pkg/controller/user/export.go
Labels: approved, cla: yes, lgtm, size/M

#1063 Skip invitations checkbox for bulk-import
  cmd/server/assets/users/import.html
  internal/auth/auth.go
  internal/auth/firebase.go
  internal/auth/local.go
  pkg/api/api.go
  pkg/controller/admin/users_operations.go
  pkg/controller/user/create.go
  pkg/controller/user/importbatch.go
Labels: approved, cla: yes, lgtm, size/M

#1070 Nit: remove extra vars from import page
  cmd/server/assets/users/import.html
  pkg/controller/user/import.go
Labels: approved, cla: yes, lgtm, size/XS

#1068 Let the observability package to register the sql related views.
  go.mod
  go.sum
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/S

#1062 Add json chaffing to apiserver.
  cmd/apiserver/main.go
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#1066 Add log-based metric to monitor OpenCensus stackdriver export.
  terraform/alerting/verification-server/alerts.tf
  terraform/alerting/verification-server/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#1067 Incremental e2e tests: use latest service for running tests
  scripts/ci-e2e-test.sh
Labels: approved, cla: yes, lgtm, size/XS

#1071 Update routing paths for apikeys and mobileapps
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/mobileapps/index.html
  cmd/server/assets/admin/realms/edit.html
  cmd/server/assets/apikeys/edit.html
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/apikeys/new.html
  cmd/server/assets/apikeys/show.html
  cmd/server/assets/header.html
  cmd/server/assets/mobileapps/edit.html
  cmd/server/assets/mobileapps/index.html
  cmd/server/assets/mobileapps/new.html
  cmd/server/assets/mobileapps/show.html
  internal/routes/server.go
  internal/routes/server_test.go
  pkg/controller/admin/mobile_apps_test.go
  pkg/controller/apikey/create.go
  pkg/controller/apikey/create_test.go
  pkg/controller/apikey/disable.go
  pkg/controller/apikey/enable.go
  pkg/controller/apikey/update.go
  pkg/controller/mobileapps/create.go
  pkg/controller/mobileapps/create_test.go
  pkg/controller/mobileapps/disable.go
  pkg/controller/mobileapps/enable.go
  pkg/controller/mobileapps/update.go
  pkg/controller/user/search_test.go
Labels: approved, cla: yes, lgtm, size/M

#1074 adding variable propagation for notification-email
  terraform/alerting/main.tf
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1072 Fill out assertions for Users search test
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/new.html
  internal/auth/local.go
  pkg/controller/admin/users_operations.go
  pkg/controller/admin/users_test.go
Labels: approved, cla: yes, lgtm, size/M

#1077 Assert system-admin mobile apps search
  cmd/server/assets/admin/mobileapps/index.html
  pkg/controller/admin/mobile_apps_test.go
Labels: approved, cla: yes, lgtm, size/S

#1080 Test system-admin realm create, search, and leave
  cmd/server/assets/admin/realms/edit.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/realms/new.html
  pkg/controller/admin/realms_test.go
  pkg/controller/admin/users_test.go
Labels: approved, cla: yes, lgtm, size/M

#1079 Test system SMS config
  cmd/server/assets/admin/sms/show.html
  pkg/controller/admin/sms_test.go
Labels: approved, cla: yes, lgtm, size/M

#1078 Test system email settings
  cmd/server/assets/admin/email/show.html
  pkg/controller/admin/email_test.go
Labels: approved, cla: yes, lgtm, size/M

#1085 Test system-admin audit event search
  cmd/server/assets/admin/events/index.html
  pkg/controller/admin/events_test.go
Labels: approved, cla: yes, lgtm, size/M

#1086 Accept client UUID for issued-code tracking
  docs/api.md
  pkg/api/api.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/issue_test.go
  pkg/database/migrations.go
  pkg/integration/integration_test.go
  pkg/otp/code.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/M

#1089 Update code issue path
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/verify-email.html
  internal/routes/server.go
  pkg/controller/home/home_test.go
  pkg/controller/login/change_password.go
  pkg/controller/login/login.go
  pkg/controller/login/select.go
  pkg/controller/user/delete.go
Labels: approved, cla: yes, lgtm, size/M

#1088 Adding service definition and SLO definition
  terraform/alerting/verification-server/monitoring.tf
  terraform/alerting/verification-server/slos.tf
Labels: approved, cla: yes, lgtm, size/M

#1095 Fixing SLO at 99.5 and conditional on GCLB
  terraform/alerting/verification-server/slos.tf
Labels: approved, cla: yes, lgtm, size/XS

#1094 Organize the code to avoid the lint warning.
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/M

#1096 Cleanup codes/ paths
  cmd/adminapi/main.go
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/verify-email.html
  internal/routes/server.go
  internal/routes/server_test.go
  pkg/controller/codes/api.go
  pkg/controller/codes/controller.go
  pkg/controller/codes/expire.go
  pkg/controller/codes/index.go
  pkg/controller/codes/logic.go
  pkg/controller/codes/show.go
  pkg/controller/home/home_test.go
  pkg/controller/login/change_password.go
  pkg/controller/login/login.go
  pkg/controller/login/select.go
  pkg/controller/user/delete.go
  pkg/database/migrations.go
  pkg/testsuite/integration.go
Labels: approved, cla: yes, lgtm, size/L

#1097 Move /codes html folder and template names
  cmd/server/assets/codes/_codescripts.html
  cmd/server/assets/codes/index.html
  cmd/server/assets/codes/issue.html
  cmd/server/assets/codes/show.html
  pkg/controller/codes/index.go
  pkg/controller/codes/show.go
  pkg/controller/home/home.go
Labels: approved, cla: yes, lgtm, size/S

#1102 Remove remaining remnants of /home
  cmd/server/assets/codes/issue.html
  internal/routes/server.go
  pkg/controller/codes/issue.go
  pkg/controller/codes/issue_test.go
Labels: approved, cla: yes, lgtm, size/M

#1101 Fast burn alert
  docs/playbooks/Fast_Error_Budget_Burn.md
  docs/playbooks/index.md
  terraform/alerting/verification-server/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1104 Delete serverless vpc connector ahead of time
  scripts/ci-terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#1093 Flattern the terraform alert config for verification server.
  terraform/alerting/alerts.tf
  terraform/alerting/dashboards/e2e.yaml
  terraform/alerting/dashboards/verification-server.yaml
  terraform/alerting/main.tf
  terraform/alerting/monitoring.tf
  terraform/alerting/notifications.tf
  terraform/alerting/probers.tf
  terraform/alerting/slos.tf
  terraform/alerting/variables.tf
  terraform/alerting/verification-server/variables.tf
  terraform/alerting/workspace.tf
Labels: approved, cla: yes, lgtm, size/M

#1105 Setting to allow bulk upload
  cmd/server/assets/realmadmin/_form_codes.html
  pkg/controller/realmadmin/settings.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#1069 Bulk issue
  cmd/server/assets/codes/bulk-issue.html
  cmd/server/assets/header.html
  cmd/server/assets/static/js/application.js
  cmd/server/assets/users/import.html
  internal/routes/server.go
  pkg/api/api.go
  pkg/controller/issueapi/bulk_issue.go
  pkg/controller/issueapi/issue.go
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/L

#1108 Pretty bulk-upload form
  cmd/server/assets/codes/bulk-issue.html
Labels: approved, cla: yes, lgtm, size/L

#1081 Add a test to check each alert has a corresponding playbook.
  docs/playbooks/alerts/E2ETestErrorRatioHigh.md
  docs/playbooks/alerts/Elevated500s.md
  docs/playbooks/alerts/ElevatedLatencyGreaterThan2s.md
  docs/playbooks/alerts/ElevatedRateLimitedCount.md
  docs/playbooks/alerts/FastErrorBudgetBurn.md
  docs/playbooks/alerts/HostDown.md
  docs/playbooks/alerts/RealmTokenRemainingCapacityLow.md
  docs/playbooks/alerts/StackdriverExportFailed.md
  docs/playbooks/index.md
  docs/playbooks/playbook_test.go
  go.mod
  go.sum
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/L

#1109 More bulk upload js
  cmd/server/assets/codes/bulk-issue.html
Labels: approved, cla: yes, lgtm, size/M

#1107 Add i18n framework
  cmd/server/assets/codes/issue.html
  go.mod
  go.sum
  internal/i18n/i18n.go
  internal/i18n/i18n_test.go
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/routes/server.go
  pkg/controller/middleware/locale.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/L

#1110 Reverse dates for user stats
  cmd/server/assets/users/show.html
Labels: approved, cla: yes, lgtm, size/S

#1112 Set a valid default value for var.https-forwarding-rule
  terraform/alerting/variables.tf
Labels: approved, cla: yes, size/XS

#1113 Fix the unit in the alert policy query
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1117 Reverse apikeys charts
  cmd/server/assets/apikeys/show.html
Labels: approved, cla: yes, lgtm, size/S

#1115 Fix playbook link
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1114 Switch var to let for function-scoped javascript
  cmd/server/assets/codes/bulk-issue.html
  cmd/server/assets/codes/issue.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/verify-email-check.html
  cmd/server/assets/realmadmin/show.html
  cmd/server/assets/static/js/application.js
  cmd/server/assets/users/import.html
Labels: approved, cla: yes, lgtm, size/M

#1040 All / System events filter + link from realms
  cmd/server/assets/admin/events/index.html
  cmd/server/assets/admin/realms/edit.html
  pkg/controller/admin/events.go
  pkg/controller/realmadmin/events.go
  pkg/database/realm.go
  pkg/database/scopes.go
Labels: approved, cla: yes, lgtm, size/M

#1121 Don't consume quota for client-provided code UUID
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/S

#1118 Remove RealmTokenRemainingCapacityLow alert
  docs/playbooks/alerts/RealmTokenRemainingCapacityLow.md
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/metrics.go
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/L

#1120 Slow burn alert
  docs/playbooks/alerts/SlowErrorBudgetBurn.md
  docs/playbooks/index.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1122 Define locales paths and load into container
  builders/server.dockerfile
  internal/envstest/server.go
  internal/i18n/i18n.go
  internal/routes/server.go
  pkg/config/server_config.go
  pkg/controller/middleware/i18n.go
  pkg/otp/code_test.go
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/L

#1124 Generate an audit entry when quota is bumped
  pkg/controller/realmadmin/settings.go
  pkg/database/audit_entry.go
Labels: approved, cla: yes, lgtm, size/S

#1125 Stop bulk upload if we see certain permanent errors or throttling
  cmd/server/assets/codes/bulk-issue.html
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/M

#1123 Add more i18n examples
  cmd/server/assets/codes/issue.html
  cmd/server/assets/header.html
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
Labels: approved, cla: yes, lgtm, size/L

#1127 Remove chart from dashboard.
  terraform/alerting/dashboards/verification-server.yaml
Labels: approved, cla: yes, lgtm, size/S

#1129 Keep fake success on no-user
  pkg/controller/login/reset_password.go
Labels: approved, cla: yes, lgtm, size/XS

#1130 More resilient recaptcha
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/login/login.html
Labels: approved, cla: yes, lgtm, size/L

#1132 Parameterize database_version
  terraform/database.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#1133 Don't require realm for sms registration
  cmd/server/assets/login/register-phone.html
  internal/routes/server.go
Labels: approved, cla: yes, lgtm, size/S

#1134 Truncate long event entries
  cmd/server/assets/admin/events/index.html
  cmd/server/assets/realmadmin/events.html
Labels: approved, cla: yes, lgtm, size/XS

#1138 Add additional queries to understand the latency
  docs/playbooks/alerts/ElevatedLatencyGreaterThan2s.md
Labels: approved, cla: yes, lgtm, size/M

#1141 Switch how we make this bool column
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/XS

#1142 Maintenance mode env var
  cmd/apiserver/main.go
  docs/api.md
  pkg/api/api.go
  pkg/config/admin_server_config.go
  pkg/config/issue.go
  pkg/config/server_config.go
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/M

#1143 block verify and throw up a banner
  cmd/server/assets/header.html
  pkg/config/api_server_config.go
  pkg/controller/middleware/template.go
  pkg/controller/verifyapi/verify.go
Labels: approved, cla: yes, lgtm, size/S

#1128 Throttle bulk code issuance using server ratelimiter config
  cmd/server/assets/codes/bulk-issue.html
  docs/api.md
Labels: approved, cla: yes, lgtm, size/M

#1145 helper function for retries
  cmd/server/assets/codes/bulk-issue.html
Labels: approved, cla: yes, lgtm, size/M

#1146 Update register phone catcha
  cmd/server/assets/login/register-phone.html
  pkg/controller/login/select.go
  pkg/controller/middleware/mfa.go
Labels: approved, cla: yes, lgtm, size/L

#1147 Share js retry logic
  cmd/server/assets/codes/bulk-issue.html
  cmd/server/assets/static/js/application.js
  cmd/server/assets/users/import.html
Labels: approved, cla: yes, lgtm, size/M

#1136 Spanish feedback
  internal/i18n/locales/es/default.po
Labels: approved, cla: yes, lgtm, size/XS

#1148 Terraform smoke test: fix db matching regex so that it works with new…
  scripts/ci-terraform.sh
Labels: approved, cla: yes, lgtm, size/XS

#1149 Have the bulk uploader pay attention to our enum values, version js
  cmd/server/assets/header.html
  cmd/server/assets/static/js/application.js
Labels: approved, cla: yes, lgtm, size/S

#1151 Fix feature tag
  .github/ISSUE_TEMPLATE/feature.md
Labels: approved, cla: yes, lgtm, size/XS

#1154 fix off by 12 error
  pkg/config/admin_server_config.go
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, size/XS

#1156 Set timeouts on rawSQL before gorm
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/XS
