Repository google/exposure-notifications-verification-server, pull requests merged in 2020-06, with the labels that each got.

#75 Fix Terraform-related deployment issues
  terraform/README.md
  terraform/main.tf
  terraform/variables.tf
Labels: cla: yes

#80 Give all services access to the token
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
Labels: approved, cla: yes, lgtm, size/S

#78 Update README.md
  terraform/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#81 Fix duplicate "apiserver-csrf" resource name
  terraform/service_cleanup.tf
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#82 Refactor mono config to non-mono config
  cmd/apiserver/main.go
  cmd/cleanup/main.go
  cmd/server/main.go
  pkg/config/api_server_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/config.go
  pkg/config/server_config.go
  pkg/controller/apikey/apikey.go
  pkg/controller/apikey/savekey.go
  pkg/controller/certapi/certificate.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/home/home.go
  pkg/controller/index/index.go
  pkg/controller/issueapi/issue.go
  pkg/controller/middleware/html/html.go
  pkg/controller/session/session.go
  pkg/controller/signout/signout.go
  pkg/controller/user/deleteuser.go
  pkg/controller/user/saveuser.go
  pkg/controller/user/user.go
  pkg/controller/verifyapi/verify.go
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
Labels: approved, cla: yes, lgtm, size/L

#84 Too many addresses of things...
  pkg/config/config.go
Labels: approved, cla: yes, lgtm, size/XS

#87 Fix typo
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
