Repository google/exposure-notifications-verification-server, pull requests merged in 2020-09, with the labels that each got.

#426 add sys admin screen for creating realms
  cmd/server/assets/admin/new.html
  cmd/server/assets/admin/realms.html
  cmd/server/assets/header.html
  cmd/server/main.go
  pkg/controller/admin/admin.go
  pkg/controller/admin/create_realm.go
  pkg/controller/admin/index.go
  pkg/controller/user/create.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#428 highlight public key discovery doc
  cmd/server/assets/realmkeys.html
Labels: approved, cla: yes, lgtm, size/XS

#431 Fix image used by e2e-runner service.
  builders/deploy.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#434 register 412 response code
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/XS

#409 Finish GCLB Terraform setup
  terraform/lb.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#435 pin to exposuer-notification-server v0.6.0
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#436 Make load balancer configs optional.
  terraform/lb.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#437 settings for enx
  cmd/server/assets/realm.html
  cmd/server/main.go
  pkg/controller/realmadmin/express.go
  pkg/controller/realmadmin/index.go
  pkg/controller/realmadmin/save.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#438 Small realm changes
  cmd/server/assets/realm.html
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#433 Upgrade Deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/L

#439 Redis name configurable in terraform
  .gitignore
  terraform-e2e/README.md
  terraform-e2e/main.tf
  terraform/redis.tf
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#440 Support multiple custom domains
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#442 Change spacing on realms index
  cmd/server/assets/admin/realms.html
Labels: approved, cla: yes, lgtm, size/S

#443 Fix bug in GCLB terraform
  terraform/lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#444 Add realm admin and user guides
  README.md
  docs/api.md
  docs/images/admin/apikeys01.png
  docs/images/admin/apikeys02.png
  docs/images/admin/apikeys03.png
  docs/images/admin/keys01.png
  docs/images/admin/keys02.png
  docs/images/admin/keys03.png
  docs/images/admin/settings01.png
  docs/images/admin/settings02.png
  docs/images/admin/settings03.png
  docs/images/admin/settings04.png
  docs/images/admin/sms01.png
  docs/images/admin/users01.png
  docs/images/admin/users02.png
  docs/images/users/issue01.png
  docs/images/users/issue02.png
  docs/images/users/step01.png
  docs/images/users/step02.png
  docs/images/users/step03.png
  docs/images/users/step04.png
  docs/realm_guide.md
  docs/user_guide.md
Labels: approved, cla: yes, lgtm, size/L

#445 Update ens to main branch
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/L

#447 Create reset password page
  cmd/server/assets/login/login.html
  cmd/server/assets/login/resetpassword.html
  cmd/server/main.go
  pkg/controller/login/resetpassword.go
Labels: approved, cla: yes, lgtm, size/L

#448 Unbreak builds on OSX
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#451 Restore the old API key code
  pkg/api/api.go
Labels: approved, cla: yes, lgtm, size/XS

#453 correct casing in json examples
  docs/api.md
Labels: approved, cla: yes, lgtm, size/S

#454 Fix intial container images path in terraform services
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#455 Ensure Debugw always has the right number of fields
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/L

#462 Add migration docs for quick -> production
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/M

#458 show long code expiry in UI on code check
  cmd/server/assets/codestatus/show.html
  pkg/controller/codestatus/show.go
  pkg/database/vercode.go
Labels: approved, cla: yes, lgtm, size/M

#463 Change default service for GCLB
  terraform/lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#464 put e2e command line tool back
  cmd/e2e-runner/main.go
  go.mod
  go.sum
  pkg/clients/e2e.go
  pkg/config/e2e_runner_server_config.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/L

#465 Move API requests to a sub router
  cmd/adminapi/main.go
  cmd/apiserver/main.go
Labels: approved, cla: yes, lgtm, size/M

#466 Copy pasta error
  cmd/adminapi/main.go
Labels: approved, cla: yes, lgtm, size/XS

#467 Echo project id in scripts
  scripts/build
  scripts/deploy
  scripts/promote
Labels: approved, cla: yes, lgtm, size/XS

#450 Allow rotating most secrets
  docs/production.md
  pkg/config/server_config.go
  pkg/database/authorized_app.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/database_util.go
  pkg/database/migrations.go
  pkg/database/token.go
  pkg/database/token_test.go
  pkg/database/vercode.go
Labels: approved, cla: yes, lgtm, size/L

#470 add admin API to api docs
  docs/api.md
Labels: approved, cla: yes, lgtm, size/L

#472 Add existing alerts to terraform
  terraform/alerting/notifications.tf
  terraform/alerting/probers.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#473 Add favicon and stuff
  cmd/server/assets/favicon.ico
  cmd/server/assets/header.html
  cmd/server/assets/static/android-chrome-192x192.png
  cmd/server/assets/static/android-chrome-512x512.png
  cmd/server/assets/static/apple-touch-icon.png
  cmd/server/assets/static/browserconfig.xml
  cmd/server/assets/static/favicon-16x16.png
  cmd/server/assets/static/favicon-32x32.png
  cmd/server/assets/static/favicon.ico
  cmd/server/assets/static/mstile-144x144.png
  cmd/server/assets/static/mstile-150x150.png
  cmd/server/assets/static/mstile-310x150.png
  cmd/server/assets/static/mstile-310x310.png
  cmd/server/assets/static/mstile-70x70.png
  cmd/server/assets/static/safari-pinned-tab.svg
  cmd/server/assets/static/site.webmanifest
  cmd/server/main.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/L

#475 Add padding fields to API
  docs/api.md
  pkg/api/api.go
Labels: approved, cla: yes, lgtm, size/L

#396 Add opencensus integration
  go.mod
  go.sum
  pkg/database/database.go
  pkg/database/token_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#479 Fix bash command
  terraform/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#480 Document users and admin configuration
  docs/production.md
Labels: approved, cla: yes, lgtm, size/S

#481 Trim space around public keys
  cmd/server/assets/realmkeys.html
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/XS

#482 Fix some docs inconsistencies
  .gitignore
  README.md
  docs/production.md
Labels: approved, cla: yes, lgtm, size/S

#485 Revert "Add opencensus integration"
  go.mod
  go.sum
  pkg/database/database.go
  pkg/database/token_test.go
Labels: approved, cla: yes, lgtm, size/M

#484 Fix data races in tests
  pkg/database/database.go
  pkg/database/migrations.go
  pkg/database/token_test.go
  pkg/database/vercode.go
Labels: approved, cla: yes, lgtm, size/L

#468 Use crypto/rand to generate random suffixes in API keys.
  cmd/e2e-runner/main.go
Labels: approved, cla: yes, lgtm, size/S

#486 Clarify that padding is b64-encoded
  docs/api.md
Labels: approved, cla: yes, lgtm, size/S

#487 Don't save the returned callback struct
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/M

#490 Add random padding to responses
  pkg/api/api.go
Labels: approved, cla: yes, lgtm, size/M

#489 Remove the callback library causing race issue
  go.mod
  go.sum
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/M

#488 Use new filesystem key manager
  docs/development.md
  docs/production.md
  go.mod
  go.sum
  pkg/database/database.go
  pkg/database/database_util.go
  tools/gen-keys/main.go
Labels: approved, cla: yes, lgtm, size/L

#492 Fix build step names for promote
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/S

#495 Remove some unnecessary logs
  pkg/jsonclient/client.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/S

#496 Upgrade to Go 1.15.1
  builders/build.yaml
  go.mod
Labels: approved, cla: yes, lgtm, size/S

#500 Revert "Remove some unnecessary logs"
  pkg/jsonclient/client.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/S

#501 New user email
  cmd/server/assets/users/new.html
  pkg/controller/user/create.go
  pkg/controller/user/update.go
Labels: approved, cla: yes, lgtm, size/M

#497 Add middleware for debug headers
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  pkg/controller/middleware/debug.go
Labels: approved, cla: yes, lgtm, size/M

#503 HMAC instead of hash keys in the cacher
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  docs/development.md
  docs/production.md
  pkg/cache/cacher.go
  pkg/cache/config.go
  terraform/redis.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/M

#493 Update Terraform README re using alerting rules
  terraform/README.md
  terraform/alerting/notifications.tf
  terraform/alerting/probers.tf
  terraform/alerting/workspace.tf
Labels: approved, cla: yes, lgtm, size/M

#502 Rename bucket_policy_only -> uniform_bucket_level_access
  terraform/build.tf
Labels: approved, cla: yes, lgtm, size/XS

#499 Acquire a lock before registering callbacks
  pkg/database/database.go
  pkg/database/database_util.go
Labels: approved, cla: yes, lgtm, size/S

#504 Floating labels for new user
  cmd/server/assets/header.html
  cmd/server/assets/users/_form.html
  cmd/server/assets/users/new.html
Labels: approved, cla: yes, lgtm, size/L

#459 Terraform smoke test
  .gitignore
  scripts/e2e-test.sh
  scripts/terraform.sh
  terraform-e2e/README.md
  terraform-e2e/main.tf
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/L

#505 Grant perms to HMAC keys
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/M

#507 Ensure success flash can be dismissed
  cmd/server/assets/header.html
Labels: approved, cla: yes, lgtm, size/S

#508 add user account guidelines
  docs/realm_guide.md
Labels: approved, cla: yes, lgtm, size/S

#510 Build before migrating
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#494 Add dashboards to be managed by Terraform.
  terraform/alerting/dashboards/e2e.yaml
  terraform/alerting/dashboards/verification-server.yaml
  terraform/alerting/monitoring.tf
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/M

#512 Allow realm to specify if MFA is required, prompt, or optional
  cmd/server/assets/header.html
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/realm.html
  pkg/controller/controller.go
  pkg/controller/login/session.go
  pkg/controller/middleware/realm.go
  pkg/controller/realm/index.go
  pkg/controller/realmadmin/save.go
  pkg/controller/session.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#516 Change to columns strings for dashboards
  terraform/alerting/dashboards/e2e.yaml
  terraform/alerting/dashboards/verification-server.yaml
Labels: approved, cla: yes, lgtm, size/XS

#515 5xx Alert
  terraform/alerting/monitoring.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#520 Add realm configuration for requiring dates
  cmd/server/assets/home.html
  cmd/server/assets/realm.html
  docs/api.md
  pkg/api/api.go
  pkg/controller/issueapi/issue.go
  pkg/controller/realmadmin/save.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#523 Populate cert as empty string on error
  pkg/controller/realmkeys/render.go
Labels: approved, cla: yes, lgtm, size/XS

#513 Switch to APIKey+IP rate limiting, HMAC values
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  docs/development.md
  docs/production.md
  pkg/ratelimit/config.go
  pkg/ratelimit/limitware/middleware.go
  terraform/redis.tf
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/L

#522 Enforce realm MFA as middleware
  cmd/server/assets/login/registerphone.html
  cmd/server/assets/realm.html
  cmd/server/main.go
  pkg/controller/login/register.go
  pkg/controller/login/signout.go
  pkg/controller/middleware/mfa.go
  pkg/controller/middleware/realm.go
  pkg/controller/realm/index.go
  pkg/controller/session.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#526 Add yegle to owners
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#521 Add alert for rate_limited_count metric.
  terraform/alerting/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#527 Backfill realm stats based on user and apikey stats
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/M

#528 Code issue attempt chart should also group by the issuing realm.
  terraform/alerting/dashboards/verification-server.yaml
Labels: approved, cla: yes, lgtm, size/XS

#529 Add rate_limited_count chart.
  terraform/alerting/dashboards/verification-server.yaml
Labels: approved, cla: yes, lgtm, size/S

#530 Separate loading realm and require realm
  cmd/server/assets/realms/select.html
  cmd/server/main.go
  pkg/controller/middleware/realm.go
Labels: approved, cla: yes, lgtm, size/M

#531 Add some comments about LoadRealm
  cmd/server/main.go
  pkg/controller/middleware/realm.go
Labels: approved, cla: yes, lgtm, size/S

#533 More consistent UI and project structure
  cmd/server/assets/admin/new.html
  cmd/server/assets/admin/realms.html
  cmd/server/assets/apikeys/edit.html
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/apikeys/new.html
  cmd/server/assets/apikeys/show.html
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/reset-password.html
  cmd/server/assets/login/select-realm.html
  cmd/server/assets/login/signout.html
  cmd/server/assets/login/verify-email.html
  cmd/server/assets/realm.html
  cmd/server/assets/realmkeys.html
  cmd/server/assets/realms/select.html
  cmd/server/assets/realmstats.html
  cmd/server/assets/users/_form.html
  cmd/server/assets/users/edit.html
  cmd/server/assets/users/index.html
  cmd/server/assets/users/new.html
  cmd/server/assets/users/show.html
  cmd/server/main.go
  pkg/controller/controller.go
  pkg/controller/login/register.go
  pkg/controller/login/reset_password.go
  pkg/controller/login/select.go
  pkg/controller/login/verify_email.go
  pkg/controller/middleware/emailverified.go
  pkg/controller/realm/index.go
  pkg/controller/realm/realm.go
  pkg/controller/realm/select.go
Labels: approved, cla: yes, lgtm, size/XXL

#541 Implement pagination for the Users page
  cmd/server/assets/users/index.html
  cmd/server/main.go
  pkg/controller/user/index.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#542 Adding a fast-forward for very-long lists
  pkg/controller/user/index.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/M

#543 Check for empty string
  pkg/controller/user/index.go
Labels: approved, cla: yes, lgtm, size/S

#544 Upgrade rate limiter
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/server/main.go
  go.mod
  go.sum
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/S

#548 Add initial scaffolding for abuse prevention
  cmd/server/assets/realm.html
  pkg/controller/realmadmin/save.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#509 Remove new-user link
  cmd/server/assets/login/login.html
  pkg/controller/user/delete.go
Labels: approved, cla: yes, lgtm, size/XS

#546 https -> ens protocol redirect service
  cmd/enx-redirect/assets/404.html
  cmd/enx-redirect/assets/500.html
  cmd/enx-redirect/assets/header.html
  cmd/enx-redirect/main.go
  pkg/config/redirect_config.go
  pkg/controller/redirect/index.go
  pkg/controller/redirect/redirect.go
Labels: approved, cla: yes, lgtm, size/L

#539 Create empty page for user import.
  cmd/server/assets/users/import.html
  cmd/server/assets/users/index.html
  cmd/server/assets/users/new.html
  cmd/server/assets/users/show.html
  cmd/server/main.go
  pkg/controller/user/import.go
Labels: approved, cla: yes, lgtm, size/L

#550 Fix migrate
  builders/cloud-sql-exec
  builders/migrate.dockerfile
Labels: approved, cla: yes, lgtm, size/S

#552 Don't mount migrations on the verification server
  builders/migrate.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#554 Add a pagination footer
  cmd/server/assets/users/index.html
  pkg/controller/user/index.go
Labels: approved, cla: yes, lgtm, size/XS

#557 ensure we're comparing lowercase to lowercase
  pkg/config/redirect_config.go
  pkg/controller/redirect/index.go
Labels: approved, cla: yes, lgtm, size/XS

#556 OTP entry form instead of window alert
  cmd/server/assets/header.html
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/reset-password.html
  pkg/controller/login/select.go
Labels: approved, cla: yes, lgtm, size/L

#555 Generate new user account on the server-side
  cmd/server/assets/users/_form.html
  cmd/server/assets/users/new.html
  cmd/server/main.go
  go.mod
  go.sum
  pkg/controller/user/create.go
  pkg/controller/user/user.go
Labels: approved, cla: yes, lgtm, size/M

#547 Fix terraform smoke test: initiate before destroy
  scripts/terraform.sh
Labels: approved, cla: yes, lgtm, size/S

#551 Add modeling service for abuse prevention
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
  cmd/modeler/main.go
  cmd/server/assets/header.html
  cmd/server/assets/realm.html
  cmd/server/assets/users/import.html
  cmd/server/main.go
  go.mod
  go.sum
  pkg/config/modeler.go
  pkg/controller/modeler/modeler.go
  pkg/controller/modeler/modeler_test.go
  pkg/controller/realmadmin/realmadmin.go
  pkg/controller/realmadmin/save.go
  pkg/database/database.go
  pkg/database/migrations.go
  pkg/database/modeler_status.go
  pkg/database/realm.go
  pkg/database/realm_stats.go
  pkg/digest/digest.go
  pkg/ratelimit/limitware/middleware.go
  terraform/service_modeler.tf
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#560 Add admin/info page to display build info
  cmd/server/assets/admin/info.html
  cmd/server/assets/header.html
  cmd/server/main.go
  pkg/controller/admin/info.go
  pkg/controller/middleware/template.go
  pkg/render/render.go
Labels: approved, cla: yes, lgtm, size/M

#559 change to map based config, match wildcard path
  cmd/enx-redirect/main.go
  pkg/config/redirect_config.go
  pkg/controller/redirect/index.go
  pkg/controller/redirect/redirect.go
Labels: approved, cla: yes, lgtm, size/M

#561 Allow system admins to remove themselves from a realm
  cmd/server/assets/users/_form.html
  cmd/server/assets/users/index.html
  pkg/controller/user/create.go
  pkg/controller/user/delete.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/M

#565 Remove new auth user create
  cmd/server/assets/login/create.html
  cmd/server/main.go
  pkg/controller/login/create.go
Labels: approved, cla: yes, lgtm, size/L

#563 Email verification requirement setting
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/verify-email.html
  cmd/server/assets/realm.html
  cmd/server/main.go
  pkg/api/api.go
  pkg/controller/login/register.go
  pkg/controller/login/verify_email.go
  pkg/controller/middleware/emailverified.go
  pkg/controller/realmadmin/save.go
  pkg/controller/session.go
  pkg/controller/user/import.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#564 Terraform smoke test use dynamic GCP projects
  scripts/e2e-test.sh
Labels: approved, cla: yes, lgtm, size/M

#566 Switch to toasts for notices
  cmd/server/assets/_flash.html
  cmd/server/assets/header.html
Labels: approved, cla: yes, lgtm, size/M

#567 Fix javascript as toasts
  cmd/server/assets/_flash.html
  cmd/server/assets/header.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/reset-password.html
  cmd/server/assets/login/signout.html
  cmd/server/assets/login/verify-email.html
  cmd/server/assets/users/new.html
Labels: approved, cla: yes, lgtm, size/L

#568 Create a password selection page
  cmd/server/assets/login/select-password.html
  cmd/server/main.go
  pkg/controller/login/select_password.go
Labels: approved, cla: yes, lgtm, size/L

#558 Redirector Terraform
  builders/build.yaml
  terraform/service_redirect.tf
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#570 Use realmid
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/XS

#571 Add enforcement mechanism for realm quotas
  cmd/adminapi/main.go
  cmd/server/main.go
  pkg/config/admin_server_config.go
  pkg/config/issue.go
  pkg/config/server_config.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/issueapi.go
  pkg/controller/issueapi/metrics.go
Labels: approved, cla: yes, lgtm, size/L

#562 Allow managing system admins via the UI
  cmd/add-users/main.go
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/realms.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/realms/new.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/new.html
  cmd/server/assets/header.html
  cmd/server/main.go
  docs/production.md
  pkg/controller/admin/admin.go
  pkg/controller/admin/index.go
  pkg/controller/admin/realms.go
  pkg/controller/admin/users.go
  pkg/database/migrations.go
  pkg/database/user.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XL

#578 Make default session duration 20h
  pkg/config/server_config.go
Labels: approved, cla: yes, lgtm, size/XS

#579 Complexity requirements UI
  cmd/server/assets/login/select-password.html
  pkg/config/server_config.go
  pkg/controller/login/select_password.go
Labels: approved, cla: yes, lgtm, size/L

#581 Add Redirect Loadbalancer
  terraform/lb.tf
Labels: approved, cla: yes, lgtm, size/M

#583 Add session idle duration
  cmd/server/assets/home.html
  cmd/server/main.go
  pkg/config/server_config.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/sessions.go
  pkg/controller/session.go
Labels: approved, cla: yes, lgtm, size/M

#553 Logic for batch user import
  cmd/server/assets/users/import.html
  cmd/server/assets/users/index.html
  cmd/server/main.go
  pkg/controller/user/importbatch.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/L

#585 Add customizable realm welcome banner
  cmd/server/assets/home.html
  cmd/server/assets/realm.html
  go.mod
  go.sum
  pkg/controller/home/home.go
  pkg/controller/realmadmin/save.go
  pkg/controller/session.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#584 Record password reset time
  cmd/server/assets/login/select-password.html
  cmd/server/main.go
  pkg/controller/login/login.go
  pkg/controller/login/select_password.go
  pkg/database/migrations.go
  pkg/database/user.go
  pkg/database/user_test.go
Labels: approved, cla: yes, lgtm, size/L

#586 Typo in image name
  terraform/service_redirect.tf
Labels: approved, cla: yes, lgtm, size/XS

#587 Move tools to tools
  cmd/add-realm/main.go
  docs/testing.md
  tools/get-certificate/main.go
  tools/get-code/main.go
  tools/get-token/main.go
Labels: approved, cla: yes, lgtm, size/L

#590 Add enx to deployment and promote
  builders/deploy.yaml
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/M

#591 Handle nil realm in logic
  pkg/controller/middleware/emailverified.go
Labels: approved, cla: yes, lgtm, size/XS

#593 Service name should be enx-redirect
  terraform/service_redirect.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/M

#594 More fixes for enx redirect config
  terraform/lb.tf
  terraform/service_redirect.tf
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#592 Realm setting for password rotation
  cmd/server/assets/realm.html
  pkg/controller/realmadmin/save.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#596 Enforce password rotation
  cmd/server/assets/login/reset-password.html
  cmd/server/main.go
  pkg/controller/controller.go
  pkg/controller/middleware/realm.go
  pkg/controller/session.go
Labels: approved, cla: yes, lgtm, size/L

#598 Redirect to show page after user-create
  cmd/server/assets/users/new.html
  cmd/server/assets/users/show.html
  pkg/controller/user/create.go
  pkg/controller/user/importbatch.go
  pkg/controller/user/show.go
  pkg/controller/user/update.go
Labels: approved, cla: yes, lgtm, size/L

#601 Update UX on realm settings
  cmd/server/assets/header.html
  cmd/server/assets/realm.html
  cmd/server/assets/realmadmin/_form_abuse_prevention.html
  cmd/server/assets/realmadmin/_form_codes.html
  cmd/server/assets/realmadmin/_form_express.html
  cmd/server/assets/realmadmin/_form_general.html
  cmd/server/assets/realmadmin/_form_security.html
  cmd/server/assets/realmadmin/_form_sms.html
  cmd/server/assets/realmadmin/edit.html
  cmd/server/assets/realmadmin/show.html
  cmd/server/main.go
  pkg/controller/realmadmin/express.go
  pkg/controller/realmadmin/index.go
  pkg/controller/realmadmin/settings.go
  pkg/controller/realmadmin/show.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/XXL

#602 As you type verify password
  cmd/server/assets/login/select-password.html
Labels: approved, cla: yes, lgtm, size/L

#603 Load realm for system admin pages
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/info.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/realms/new.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/new.html
  cmd/server/assets/header.html
  cmd/server/main.go
Labels: approved, cla: yes, lgtm, size/L

#597 Issue582
  cmd/server/assets/realm.html
  cmd/server/assets/realmadmin/_form_codes.html
  pkg/config/admin_server_config.go
  pkg/config/issue.go
  pkg/config/server_config.go
  pkg/controller/issueapi/issue.go
  pkg/controller/realmadmin/express.go
  pkg/controller/realmadmin/settings.go
  pkg/database/realm.go
  pkg/database/realm_test.go
  pkg/render/render.go
  terraform/service_admin_apiserver.tf
  terraform/service_server.tf
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XL

#605 remove double li
  cmd/server/assets/realmadmin/_form_codes.html
Labels: approved, cla: yes, lgtm, size/XS

#612 Add /health to redirect server
  cmd/enx-redirect/main.go
  pkg/controller/healthz.go
Labels: approved, cla: yes, lgtm, size/S

#611 Add extra hosts flag to monitor
  terraform/alerting/probers.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#613 Fix lb.tf typos in redirect LB
  terraform/lb.tf
Labels: approved, cla: yes, size/XS

#615 Colons not equal signs
  terraform/services.tf
Labels: approved, cla: yes, size/XS

#614 don't show expiry countdown if claimed
  cmd/server/assets/codestatus/show.html
  pkg/controller/codestatus/show.go
Labels: approved, cla: yes, lgtm, size/XS

#618 Upgrade key server dep to 0.9.1
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#622 Only save SMS on the SMS form
  cmd/server/assets/realmadmin/_form_sms.html
  pkg/controller/realmadmin/settings.go
Labels: approved, cla: yes, lgtm, size/M

#623 Hide ENX settings once enabled behind advanced panel
  cmd/server/assets/realmadmin/edit.html
Labels: approved, cla: yes, lgtm, size/M

#624 Suppress user-not-found error
  cmd/server/assets/login/reset-password.html
Labels: approved, cla: yes, lgtm, size/XS

#599 Create an account settings page
  cmd/server/assets/header.html
  cmd/server/assets/login/account.html
  cmd/server/assets/login/verify-email.html
  cmd/server/main.go
  pkg/controller/login/account.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/L

#625 Avoid integer overflow when model is negative
  pkg/controller/modeler/modeler.go
  pkg/controller/modeler/modeler_test.go
  pkg/database/modeler_status.go
Labels: approved, cla: yes, lgtm, size/M

#626 Give modeler ability to clear the cache
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/modeler/main.go
  cmd/server/main.go
  pkg/config/modeler.go
  pkg/controller/modeler/modeler_test.go
  terraform/service_modeler.tf
Labels: approved, cla: yes, lgtm, size/M

#604 Use the same cacher for public key and signing caches
  cmd/apiserver/main.go
  cmd/server/main.go
  go.sum
  pkg/controller/certapi/certapi.go
  pkg/controller/jwks/jwks.go
  pkg/controller/realmkeys/realmkeys.go
  pkg/controller/realmkeys/render.go
  pkg/keyutils/public_keys.go
Labels: approved, cla: yes, lgtm, size/L

#621 Require region codes are globally unique
  cmd/server/assets/realmadmin/_form_abuse_prevention.html
  cmd/server/assets/realmadmin/_form_codes.html
  cmd/server/assets/realmadmin/_form_general.html
  cmd/server/assets/realmadmin/_form_security.html
  cmd/server/assets/realmadmin/_form_sms.html
  pkg/controller/realmadmin/settings.go
  pkg/database/database.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/L

#617 Tabbed navigation
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/admin/info.html
  cmd/server/assets/admin/realms/index.html
  cmd/server/assets/admin/realms/new.html
  cmd/server/assets/admin/users/index.html
  cmd/server/assets/admin/users/new.html
  cmd/server/assets/apikeys/edit.html
  cmd/server/assets/apikeys/index.html
  cmd/server/assets/apikeys/new.html
  cmd/server/assets/apikeys/show.html
  cmd/server/assets/codestatus/index.html
  cmd/server/assets/codestatus/show.html
  cmd/server/assets/header.html
  cmd/server/assets/home.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/reset-password.html
  cmd/server/assets/login/select-password.html
  cmd/server/assets/login/select-realm.html
  cmd/server/assets/login/verify-email.html
  cmd/server/assets/realm.html
  cmd/server/assets/realmadmin/edit.html
  cmd/server/assets/realmadmin/show.html
  cmd/server/assets/realmkeys.html
  cmd/server/assets/users/edit.html
  cmd/server/assets/users/import.html
  cmd/server/assets/users/index.html
  cmd/server/assets/users/new.html
  cmd/server/assets/users/show.html
  cmd/server/main.go
  pkg/controller/middleware/currentpath.go
Labels: approved, cla: yes, lgtm, size/L

#628 Allow deletion of factors
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/login/account.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/users/import.html
Labels: approved, cla: yes, lgtm, size/L

#630 Minor fixes to MFA page
  cmd/server/assets/login/register-phone.html
Labels: approved, cla: yes, lgtm, size/M

#631 Fix ID on express tab
  cmd/server/assets/realmadmin/edit.html
Labels: approved, cla: yes, lgtm, size/XS

#632 Use more consistent ordering on realm selection and lists pages
  pkg/database/realm.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/S

#633 Multi-factor selection at login
  cmd/server/assets/login/_loginscripts.html
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
Labels: approved, cla: yes, lgtm, size/L

#636 Wait for signout redirect if there is an error
  cmd/server/assets/login/login.html
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/signout.html
Labels: approved, cla: yes, lgtm, size/S
