Repository google/exposure-notifications-verification-server, pull requests merged in 2021-01, with the labels that each got.

#1503 Ping db on health instead of opening new connection
  internal/routes/adminapi.go
  internal/routes/apiserver.go
  internal/routes/enx_redirect.go
  internal/routes/server.go
  pkg/controller/healthz.go
  pkg/testsuite/integration.go
  terraform/alerting/probers.tf
Labels: approved, cla: yes, lgtm, size/M

#1504 Unify in-memory server bootstrap
  cmd/e2e-runner/main.go
  internal/clients/adminapi.go
  internal/clients/apiserver.go
  internal/clients/appsync.go
  internal/clients/clients.go
  internal/envstest/adminapi.go
  internal/envstest/apiserver.go
  internal/envstest/harness.go
  internal/envstest/server.go
  pkg/clients/apis.go
  pkg/clients/e2e.go
  pkg/controller/appsync/appsync.go
  pkg/controller/appsync/appsync_test.go
  pkg/controller/appsync/controller.go
  pkg/controller/issueapi/handle_issue_batch_test.go
  pkg/controller/issueapi/handle_issue_test.go
  pkg/integration/integration_test.go
  pkg/jsonclient/client.go
  pkg/testsuite/clients.go
  pkg/testsuite/e2e.go
  pkg/testsuite/helpers.go
  pkg/testsuite/integration.go
  pkg/testsuite/suite.go
  terraform/service_e2e_runner.tf
  tools/get-certificate/main.go
  tools/get-code/main.go
  tools/get-token/main.go
Labels: approved, cla: yes, lgtm, size/XXL

#1507 Temporarily don't check database connection
  terraform/alerting/probers.tf
Labels: approved, cla: yes, lgtm, size/XS

#1505 Check copyright and date
  .github/workflows/codereview.yaml
  Makefile
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#1506 Do not limit health checks
  go.mod
  pkg/controller/healthz.go
Labels: approved, cla: yes, lgtm, size/S

#1508 Refactor Cloud Run annotations in Terraform config.
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1510 Simplify latency alerting
  terraform/alerting/module.latency-alert/main.tf
  terraform/alerting/module.latency-alert/variables.tf
  terraform/alerting/slos.tf
Labels: approved, cla: yes, lgtm, size/L

#1511 Fix and test for regression for long code expiry
  pkg/controller/codes/expire.go
  pkg/controller/issueapi/issue_test.go
  pkg/controller/issueapi/validate_code.go
  pkg/database/duration.go
Labels: approved, cla: yes, lgtm, size/S

#1513 Separate Cloud Run Service & Revision annotations for terraform
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1514 Update key server dep to 0.19.0
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#1515 Use custom domain in e2e-runner if it's available
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/XS

#1516 Use full URL in e2e-runner.
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/XS

#1509 I18N for bulk-issue
  cmd/server/assets/codes/bulk-issue.html
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/ph/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
Labels: approved, cla: yes, lgtm, size/XL

#1518 Update firebase to the latest version
  cmd/server/assets/firebase.html
Labels: approved, cla: yes, lgtm, size/XS

#1519 Reset recaptcha on expire
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/static/js/application.js
Labels: approved, cla: yes, lgtm, size/S

#1520 Only emit an error when shouldCleanup actually fails
  pkg/controller/cleanup/cleanup.go
Labels: approved, cla: yes, lgtm, size/S

#1522 Switch modeler logs to debug
  pkg/controller/modeler/modeler.go
Labels: approved, cla: yes, lgtm, size/XS

#1521 Remove Chao :(
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1523 Return NotFound for invalid UUIDs
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/M

#1524 Show raw error body if unmarshal fails
  internal/clients/clients.go
Labels: approved, cla: yes, lgtm, size/XS

#1527 Add a CloudSchedulerJobFailed alert based on log metric.
  docs/playbooks/alerts/CloudSchedulerJobFailed.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1526 Support for Twilio messaging service
  cmd/server/assets/realmadmin/_form_sms.html
  pkg/controller/realmadmin/sms_test.go
  pkg/database/migrations.go
  pkg/database/realm_test.go
  pkg/database/sms_config.go
  pkg/database/sms_from_number_test.go
  pkg/sms/twilio.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/M

#1525 Introduce advanced search and bulk permissions
  .github/workflows/codereview.yaml
  cmd/server/assets/static/js/application.js
  cmd/server/assets/users/index.html
  internal/routes/server.go
  pkg/controller/user/bulk_permissions.go
  pkg/controller/user/index.go
  pkg/database/bulk_permission.go
  pkg/database/bulk_permission_test.go
  pkg/database/scopes.go
  pkg/database/scopes_test.go
  pkg/rbac/rbac.go
Labels: approved, cla: yes, lgtm, size/XL

#1529 Nits: never rollback code sql type, check content-type header
  internal/clients/clients.go
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/S

#1530 Skip conflict and already succeeded lines of csv retries
  cmd/server/assets/static/js/application.js
Labels: approved, cla: yes, lgtm, size/M

#1531 Support testType field as input for bulk-upload
  cmd/server/assets/codes/bulk-issue.html
  cmd/server/assets/static/js/application.js
Labels: approved, cla: yes, lgtm, size/S

#1533 Delete any orphaned entries before creating foreignkey
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/S

#1534 Drop FK constraints if they already exist before creating
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/XS

#1535 Simplify alerts
  terraform/alerting/module.availability-slo/main.tf
  terraform/alerting/module.availability-slo/variables.tf
  terraform/alerting/module.latency-slo/main.tf
  terraform/alerting/module.latency-slo/variables.tf
  terraform/alerting/slos.tf
Labels: approved, cla: yes, lgtm, size/M

#1537 Retry database pings in health checks
  pkg/controller/healthz.go
Labels: approved, cla: yes, lgtm, size/S

#1539 Pad batch requests and eliminate inner padding
  pkg/api/api.go
  pkg/controller/issueapi/handle_issue_batch.go
Labels: approved, cla: yes, lgtm, size/M

#1540 fix lints. Add presubmit overall test coverage output
  Makefile
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/XS

#1541 Fix padding
  pkg/api/api.go
  pkg/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/M

#1542 Switch the batch uploader client to outer padding
  cmd/server/assets/static/js/application.js
  docs/api.md
Labels: approved, cla: yes, lgtm, size/S

#1544 Drop optional calculation of Daily Active Users
  cmd/server/assets/realmadmin/_form_general.html
  cmd/server/assets/realmadmin/_stats_daily_active_users.html
  cmd/server/assets/realmadmin/stats.html
  pkg/controller/middleware/chaff.go
  pkg/controller/middleware/chaff_test.go
  pkg/controller/realmadmin/settings_modify.go
  pkg/controller/realmadmin/settings_modify_test.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_stats.go
  pkg/database/realm_stats_test.go
Labels: approved, cla: yes, lgtm, size/L

#1545 Log URLs and response codes in appsync errors, increase max size to 64kb
  internal/clients/clients.go
  pkg/config/appsync_server_config.go
Labels: approved, cla: yes, lgtm, size/S

#1547 Remove leading slash in clients
  internal/clients/clients.go
Labels: approved, cla: yes, lgtm, size/XS

#1549 Check session expiration on login
  internal/routes/server.go
  pkg/controller/login/controller.go
  pkg/controller/login/login.go
  pkg/controller/login/register_phone.go
  pkg/controller/login/select_realm.go
  pkg/controller/middleware/auth.go
Labels: approved, cla: yes, lgtm, size/M

#1551 Document enx-redirector for realm and system admins
  docs/images/admin/mobile-apps-index.png
  docs/images/admin/mobile-apps-new.png
  docs/realm-admin-guide.md
  docs/system-admin-guide.md
Labels: approved, cla: yes, lgtm, size/L

#1550 Add intelligence for redirecting post-login
  cmd/server/assets/login/register-phone.html
  cmd/server/assets/login/verify-email.html
  internal/routes/server.go
  pkg/controller/login/change_password.go
  pkg/controller/login/controller.go
  pkg/controller/login/login.go
  pkg/controller/login/login_test.go
  pkg/controller/login/post_authenticate.go
  pkg/controller/login/post_authenticate_test.go
  pkg/controller/login/select_realm.go
  pkg/controller/user/delete.go
Labels: approved, cla: yes, lgtm, size/L

#1553 Cover random number gen
  internal/project/random.go
  internal/project/random_test.go
Labels: approved, cla: yes, lgtm, size/M

#1552 Create metrics for when humans access secrets or decrypt values
  terraform/alerting/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#1555 Add other email templates to the realm settings UI
  cmd/server/assets/realmadmin/_form_email.html
  internal/project/context_test.go
  pkg/controller/realmadmin/settings_modify.go
Labels: approved, cla: yes, lgtm, size/L

#1557 Bad request for jwks invalid region
  pkg/controller/jwks/jwks.go
Labels: approved, cla: yes, lgtm, size/M

#1559 Allow JWKs to work with region code as well
  pkg/controller/jwks/jwks.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: approved, cla: yes, lgtm, size/M

#1560 Share alldigits as a project util
  internal/project/util.go
  internal/project/util_test.go
  pkg/database/realm.go
  pkg/database/sms_config.go
Labels: approved, cla: yes, lgtm, size/M

#1556 Fire alerts when humans do secret things
  docs/playbooks/alerts/HumanAccessedSecret.md
  docs/playbooks/alerts/HumanDecryptedValue.md
  terraform/alerting/alerts.tf
  terraform/alerting/monitoring.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1561 allow for redirect cert changes without outages
  terraform/redirect-lb.tf
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#1558 fix bulk_issue_test
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/header.html
  go.mod
  go.sum
  pkg/controller/codes/bulk_issue_test.go
  pkg/render/renderer_impl.go
Labels: approved, cla: yes, lgtm, size/M

#1563 Move appsync warnings to debug level
  pkg/controller/appsync/appsync.go
Labels: approved, cla: yes, lgtm, size/XS

#1565 Defensively check deleted_at fields in realm/user join tables for memberships
  pkg/database/pagination.go
  pkg/database/realm.go
  pkg/database/realm_test.go
  pkg/database/scopes.go
Labels: approved, cla: yes, lgtm, size/M

#1566 Delete users who are deleted
  cmd/server/assets/admin/users/index.html
  pkg/database/migrations.go
  pkg/database/user.go
Labels: approved, cla: yes, lgtm, size/S

#1570 add directions for adding redirect domains
  docs/system-admin-guide.md
Labels: approved, cla: yes, lgtm, size/M

#1571 Stop issuing codes if the twilio SMS queue is full
  cmd/server/assets/static/js/application.js
  pkg/api/api.go
  pkg/controller/issueapi/send_sms.go
  pkg/sms/twilio.go
Labels: approved, cla: yes, lgtm, size/S

#1572 Add Binary Authorization for Cloud Run
  builders/build.yaml
  scripts/build
  terraform/binary_authorization.tf
  terraform/main.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1573 Update CloudSchedulerJobFailed.md
  docs/playbooks/alerts/CloudSchedulerJobFailed.md
Labels: approved, cla: yes, lgtm, size/S

#1578 Move e2e client into internal/
  cmd/e2e-runner/main.go
  internal/clients/e2e.go
  pkg/clients/metrics.go
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/L

#1577 Move associated site data responses into api package
  pkg/api/android.go
  pkg/api/ios.go
  pkg/controller/associated/android.go
  pkg/controller/associated/index.go
  pkg/controller/associated/ios.go
Labels: approved, cla: yes, lgtm, size/L

#1576 Add issue mean latency metric to dashboard
  terraform/alerting/dashboards/verification-server.yaml
Labels: approved, cla: yes, lgtm, size/S

#1579 Add Binauthz envvars to Terraform builder
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1580 Fix deprecation notice
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1583 Merge e2e configurations
  Makefile
  cmd/e2e-runner/main.go
  internal/envstest/adminapi.go
  internal/envstest/apiserver.go
  internal/envstest/bootstrap.go
  internal/envstest/harness.go
  internal/envstest/integration.go
  pkg/database/mobile_app.go
  pkg/integration/integration_test.go
  pkg/testsuite/e2e.go
  scripts/ci-e2e-test.sh
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/XL

#1584 Marshal errors with *ErrorReturn type
  cmd/server/assets/codes/issue.html
  pkg/api/api.go
  pkg/controller/issueapi/handle_issue.go
  pkg/controller/issueapi/send_sms.go
Labels: approved, cla: yes, lgtm, size/S

#1585 Add optional enx-redirect tests to e2e-runner
  cmd/e2e-runner/main.go
  docs/production.md
  internal/clients/clients.go
  internal/clients/e2e.go
  internal/clients/enx_redirect.go
  internal/envstest/bootstrap.go
  pkg/config/e2e_runner_server_config.go
  terraform/service_e2e_runner.tf
  tools/e2e-test/main.go
Labels: approved, cla: yes, lgtm, size/L

#1586 Don't return http.Response when unneeded
  internal/clients/adminapi.go
  internal/clients/apiserver.go
  internal/clients/appsync.go
  internal/clients/clients.go
  internal/clients/enx_redirect.go
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/M

#1582 Save Realm into context
  pkg/controller/middleware/membership.go
Labels: approved, cla: yes, lgtm, size/XS

#1588 Actually delete e2e API keys and mobile apps
  internal/envstest/bootstrap.go
  internal/envstest/integration.go
Labels: approved, cla: yes, lgtm, size/M

#1587 Test email/sms validation and system
  pkg/database/email_config_test.go
  pkg/database/sms_config_test.go
Labels: approved, cla: yes, lgtm, size/L

#1589 Use correct prefix
  internal/envstest/bootstrap.go
Labels: approved, cla: yes, lgtm, size/XS

#1590 ios != android
  internal/envstest/bootstrap.go
Labels: approved, cla: yes, lgtm, size/XS

#1591 Set maxScale to 2.
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#1593 add locking to appsync handler
  pkg/config/appsync_server_config.go
  pkg/controller/appsync/appsync.go
  pkg/controller/appsync/appsync_test.go
  pkg/database/cleanup.go
Labels: approved, cla: yes, lgtm, size/M

#1594 add database columns and config for feature flag
  pkg/config/certificate_signing_config.go
  pkg/database/migrations.go
  pkg/database/realm.go
Labels: approved, cla: yes, lgtm, size/S

#1596 Pagination starts at page 1
  pkg/database/pagination.go
  pkg/pagination/pagination.go
Labels: approved, cla: yes, lgtm, size/XS

#1598 add trendline to realm stats
  cmd/server/assets/realmadmin/_stats_codes.html
Labels: approved, cla: yes, lgtm, size/M

#1601 Add audits for saving a Token Signing Key
  pkg/database/token_signing_keys.go
  pkg/database/token_signing_keys_test.go
Labels: approved, cla: yes, lgtm, size/M

#1600 Add tests for cleanup
  pkg/controller/cleanup/cleanup.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/cleanup/handle_cleanup_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1604 Return a success response on remote workers when no work is done
  pkg/controller/appsync/appsync.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/rotation/handle_rotate.go
Labels: approved, cla: yes, lgtm, size/XS

#1605 Display realm_id in system admin event logs
  cmd/server/assets/admin/events/index.html
Labels: approved, cla: yes, lgtm, size/XS

#1606 Restore user re-created metric and alert
  docs/playbooks/alerts/UpstreamUserRecreates.md
  pkg/controller/healthz.go
  pkg/controller/user/metrics.go
  pkg/controller/user/reset_password.go
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/M

#1608 Add db lock to stats-puller service. Share 'Should<servicename>' func
  pkg/config/appsync_server_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/stats_puller_config.go
  pkg/controller/appsync/appsync.go
  pkg/controller/appsync/appsync_test.go
  pkg/controller/appsync/controller.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/cleanup/handle_cleanup_test.go
  pkg/controller/rotation/handle_rotate.go
  pkg/controller/rotation/handle_rotate_test.go
  pkg/controller/statspuller/handle_pull.go
  pkg/database/lock.go
  pkg/database/lock_test.go
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/L

#1609 Put migration name back
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/XS

#1602 Source token signing keys from the database
  cmd/cleanup/main.go
  cmd/rotation/main.go
  cmd/server/assets/admin/info.html
  docs/production.md
  internal/envstest/apiserver.go
  internal/envstest/integration.go
  internal/routes/apiserver.go
  pkg/config/api_server_config.go
  pkg/config/token_signing_config.go
  pkg/controller/admin/caches.go
  pkg/controller/admin/info.go
  pkg/controller/certapi/certapi.go
  pkg/controller/certapi/certificate.go
  pkg/controller/rotation/handle_rotate.go
  pkg/controller/rotation/handle_rotate_test.go
  pkg/controller/verifyapi/verify.go
  pkg/controller/verifyapi/verifyapi.go
  pkg/database/migrations.go
  pkg/database/token_signing_keys.go
  pkg/database/token_signing_keys_test.go
  terraform/alerting/slos.tf
  terraform/service_rotation.tf
  terraform/services.tf
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1599 DB model for storing key server stats
  cmd/server/assets/realmadmin/_form_codes.html
  cmd/server/assets/realmadmin/_form_general.html
  pkg/config/token_signing_config.go
  pkg/controller/realmadmin/express_disable.go
  pkg/controller/realmadmin/express_enable.go
  pkg/controller/realmadmin/settings_modify.go
  pkg/controller/realmadmin/settings_show.go
  pkg/database/key_server_stats.go
  pkg/database/key_server_stats_test.go
  pkg/database/migrations.go
Labels: approved, cla: yes, lgtm, size/L

#1613 Make sure return results are []string
  internal/project/errors.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/rotation/handle_rotate.go
Labels: approved, cla: yes, lgtm, size/M

#1614 Add verification certificate key auto rotation
  cmd/rotation/main.go
  cmd/server/assets/admin/_nav.html
  cmd/server/assets/realmadmin/keys.html
  internal/routes/server.go
  pkg/config/certificate_signing_config.go
  pkg/config/rotation_config.go
  pkg/controller/admin/realms_test.go
  pkg/controller/realmkeys/automatic_rotate.go
  pkg/controller/realmkeys/manual_rotate.go
  pkg/controller/rotation/handle_token_rotate.go
  pkg/controller/rotation/handle_token_rotate_test.go
  pkg/controller/rotation/handle_verification_rotate.go
  pkg/controller/rotation/handle_verification_rotate_test.go
  pkg/controller/rotation/rotation.go
  pkg/database/database_util.go
  pkg/database/realm.go
  terraform/service_rotation.tf
Labels: approved, cla: yes, lgtm, size/XL

#1615 Cleanup old key-server stats
  cmd/server/assets/realmadmin/_form_general.html
  pkg/config/cleanup_server_config.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/middleware/template.go
  pkg/database/key_server_stats.go
  pkg/database/key_server_stats_test.go
Labels: approved, cla: yes, lgtm, size/M

#1616 purge signing keys
  pkg/config/cleanup_server_config.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/database/realm_test.go
  pkg/database/signing_key.go
Labels: approved, cla: yes, lgtm, size/M

#1617 add key admin permissions to rotate job
  terraform/service_rotation.tf
Labels: approved, cla: yes, lgtm, size/S

#1619 Fix nits from signing key cleanup
  pkg/controller/cleanup/handle_cleanup.go
  pkg/database/signing_key.go
Labels: approved, cla: yes, lgtm, size/S

#1620 Build all cmd binaries at once
  bin/.keep
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/L

#1622 Keep schedules all in UTC timezone
  terraform/database.tf
  terraform/mirror/service.tf
  terraform/service-stats-puller.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_rotation.tf
Labels: approved, cla: yes, lgtm, size/S

#1624 legacy signing fixes
  pkg/controller/certapi/certapi.go
  pkg/controller/verifyapi/verify.go
  tools/get-certificate/main.go
  tools/get-code/main.go
  tools/get-token/main.go
Labels: approved, cla: yes, lgtm, size/M

#1625 Keep Schedules in PST
  terraform/database.tf
  terraform/mirror/service.tf
  terraform/service-stats-puller.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_rotation.tf
Labels: approved, cla: yes, lgtm, size/S

#1618 Clean up nits from verification certification rotation
  cmd/server/assets/realmadmin/keys.html
  pkg/controller/realmkeys/automatic_rotate.go
  pkg/controller/realmkeys/automatic_rotate_test.go
  pkg/controller/realmkeys/manual_rotate.go
  pkg/controller/realmkeys/manual_rotate_test.go
  pkg/controller/realmkeys/realmkeys_test.go
  pkg/controller/rotation/handle_verification_rotate.go
  pkg/controller/rotation/handle_verification_rotate_test.go
  pkg/database/database_util.go
  pkg/database/realm.go
  pkg/database/scopes.go
  pkg/pagination/pagination.go
  terraform/service_rotation.tf
Labels: approved, cla: yes, lgtm, size/XL

#1626 Ensure bin dir exists
  bin/.keep
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1627 update ENS deps
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#1628 Make codes/stats bit of seeding optional
  pkg/database/scopes.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#1629 Make seed script also verify codes and claim tokens
  pkg/controller/certapi/certificate.go
  pkg/controller/codes/issue_test.go
  pkg/controller/verifyapi/verify.go
  pkg/database/token.go
  pkg/database/token_test.go
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#1630 Ping when opening SQL connection
  pkg/database/database.go
Labels: approved, cla: yes, lgtm, size/S

#1631 Add new stats for codes_invalid and tokens to responses
  docs/api.md
  pkg/controller/apikey/stats.go
  pkg/database/authorized_app.go
  pkg/database/authorized_app_stats.go
  pkg/database/authorized_app_stats_test.go
  pkg/database/authorized_app_test.go
  pkg/database/realm.go
  pkg/database/realm_stats.go
  pkg/database/realm_stats_test.go
Labels: approved, cla: yes, lgtm, size/L

#1610 Onboarding in ens:// spec
  docs/ens-spec.md
Labels: approved, cla: yes, lgtm, size/S

#1632 change onboard -> onboarding
  docs/ens-spec.md
Labels: approved, cla: yes, lgtm, size/XS

#1636 add auto rotation realm guide
  docs/images/admin/signing-auto-01.png
  docs/images/admin/signing-auto-02.png
  docs/images/admin/signing-auto-03.png
  docs/realm-admin-guide.md
Labels: approved, cla: yes, lgtm, size/S

#1637 fix toc
  docs/realm-admin-guide.md
Labels: approved, cla: yes, lgtm, size/XS

#1639 Fix the query used by UpstreamUserRecreates alert.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1638 Increment stats at the end of successfully issuing codes
  pkg/controller/issueapi/issue.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/L

#1642 Resolving nits
  pkg/database/vercode.go
Labels: approved, cla: yes, lgtm, size/S

#1635 Add top-level onboarding domain to redirect service
  pkg/config/redirect_config.go
  pkg/controller/redirect/helpers.go
  pkg/controller/redirect/helpers_test.go
  pkg/controller/redirect/index.go
  pkg/controller/redirect/index_test.go
  pkg/controller/redirect/redirect.go
  terraform/redirect-lb.tf
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1643 Distinct certificates on load balancer
  terraform/redirect-lb.tf
Labels: approved, cla: yes, lgtm, size/XS

#1641 Add invalid codes and full token graphs to stats
  cmd/server/assets/realmadmin/_stats_codes.html
  cmd/server/assets/realmadmin/_stats_tokens.html
  cmd/server/assets/realmadmin/stats.html
Labels: approved, cla: yes, lgtm, size/L

#1645 Add random string to end of certificates
  terraform/redirect-lb.tf
Labels: approved, cla: yes, lgtm, size/S

#1646 Move API key stats into the API
  cmd/server/assets/apikeys/show.html
  docs/api.md
  internal/routes/server.go
  internal/routes/server_test.go
  pkg/controller/apikey/stats_test.go
  pkg/controller/stats/realm_authorized_app.go
  pkg/controller/stats/realm_user.go
  pkg/controller/stats/stats.go
  pkg/database/authorized_app.go
  pkg/database/authorized_app_stats.go
  pkg/database/authorized_app_stats_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1648 Allow pushes to run in parallel too
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/S

#1647 Condition should contain a unit.
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1651 seed key-server stats
  terraform/service_stats_puller.tf
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/M

#1653 Make sure attestor is provisioned before building
  terraform/main.tf
Labels: approved, cla: yes, lgtm, size/XS

#1654 Fix doc link
  docs/case-worker-guide.md
Labels: approved, cla: yes, lgtm, size/XS

#1652 add sms signing keys menu translations
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/ph/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
Labels: approved, cla: yes, lgtm, size/S

#1655 Add tests for i18n package
  go.mod
  go.sum
  internal/i18n/i18n.go
  internal/i18n/i18n_test.go
Labels: approved, cla: yes, lgtm, size/L

#1656 Add more unit tests for internal/project package
  internal/project/errors_test.go
  internal/project/util_test.go
Labels: approved, cla: yes, lgtm, size/M

#1658 Add tests for api package
  pkg/api/api.go
  pkg/api/api_test.go
Labels: approved, cla: yes, lgtm, size/M

#1657 Add more tests for routes
  internal/routes/adminapi_test.go
  internal/routes/apiserver_test.go
  internal/routes/enx_redirect_test.go
  internal/routes/server_test.go
Labels: approved, cla: yes, lgtm, size/L

#1659 Add more tests for cacher
  pkg/cache/cacher.go
  pkg/cache/cacher_test.go
  pkg/cache/config_test.go
  pkg/cache/noop_test.go
Labels: approved, cla: yes, lgtm, size/L

#1621 Retrieve stats from key-server
  cmd/stats-puller/main.go
  internal/clients/admin_api.go
  internal/clients/api_server.go
  internal/clients/app_sync.go
  internal/clients/clients.go
  internal/clients/key_server.go
  pkg/config/stats_puller_config.go
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/signers.go
  pkg/controller/statspuller/handle_pull.go
  pkg/controller/statspuller/statspull.go
  pkg/database/key_server_stats.go
  pkg/database/key_server_stats_test.go
  pkg/database/mobile_app.go
  pkg/database/mobile_app_test.go
  pkg/jwthelper/jwthelper.go
Labels: approved, cla: yes, lgtm, size/L

#1664 Split out error response in docs
  docs/api.md
Labels: approved, cla: yes, lgtm, size/M

#1665 Distribution by OS
  cmd/server/assets/realmadmin/_stats_keyserver.html
Labels: approved, cla: yes, lgtm, size/L

#1666 Move stats to the end
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/S

#1662 removing unneeded Elevated500 alert
  docs/playbooks/alerts/Elevated500s.md
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1667 Use gray for unknown
  cmd/server/assets/realmadmin/_stats_keyserver.html
Labels: approved, cla: yes, lgtm, size/XS

#1650 Implement first pass at SMS signature algorithm
  pkg/jwthelper/jwthelper.go
  pkg/signatures/signatures.go
  pkg/signatures/sms.go
  pkg/signatures/sms_test.go
Labels: approved, cla: yes, lgtm, size/L

#1669 TEK age & onset-upload distribution charts
  cmd/server/assets/realmadmin/_stats_codes.html
  cmd/server/assets/realmadmin/_stats_keyserver.html
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#1671 add docs for feature flags, make config available in all servers
  docs/development.md
  pkg/config/admin_server_config.go
  pkg/config/api_server_config.go
  pkg/config/appsync_server_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/e2e_runner_server_config.go
  pkg/config/redirect_config.go
  pkg/config/rotation_config.go
  pkg/config/stats_puller_config.go
Labels: approved, cla: yes, lgtm, size/S

#1670 Redraw stats charts on window resize
  cmd/server/assets/realmadmin/_stats_codes.html
  cmd/server/assets/realmadmin/_stats_keyserver.html
  cmd/server/assets/realmadmin/_stats_tokens.html
  cmd/server/assets/realmadmin/stats.html
Labels: approved, cla: yes, lgtm, size/L

#1673 Create SMSSigning config and instantiate key manager
  cmd/adminapi/main.go
  cmd/server/main.go
  docs/development.md
  internal/envstest/adminapi.go
  internal/envstest/server.go
  internal/routes/adminapi.go
  internal/routes/adminapi_test.go
  internal/routes/server.go
  internal/routes/server_test.go
  pkg/config/admin_server_config.go
  pkg/config/server_config.go
  pkg/config/sms_signing_config.go
  pkg/controller/issueapi/controller.go
  pkg/controller/issueapi/gen_code_test.go
  pkg/controller/issueapi/handle_issue_batch_test.go
  pkg/controller/issueapi/handle_issue_test.go
  pkg/controller/issueapi/issue_test.go
  pkg/controller/issueapi/issueapi_test.go
  pkg/controller/issueapi/send_sms_test.go
  pkg/controller/issueapi/validate_code_test.go
  pkg/database/realm.go
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/L

#1674 Move and cache SMS provider up one level
  pkg/controller/issueapi/controller.go
  pkg/controller/issueapi/handle_issue_test.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/send_sms.go
  pkg/controller/issueapi/send_sms_test.go
Labels: approved, cla: yes, lgtm, size/L

#1677 separating notification channels -paging and non-paging
  terraform/alerting/alerts.tf
  terraform/alerting/notifications.tf
  terraform/alerting/slos.tf
  terraform/alerting/variables.tf
Labels: approved, cla: yes, lgtm, size/M

#1679 Update CloudSchedulerJobFailed playbook.
  docs/playbooks/alerts/CloudSchedulerJobFailed.md
Labels: approved, cla: yes, lgtm, size/S

#1680 Give cleanup permission to cleanup keys
  terraform/service_cleanup.tf
Labels: approved, cla: yes, lgtm, size/S

#1681 Add debug logging for when distributed tasks are skipped
  pkg/controller/appsync/appsync.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/rotation/handle_token_rotate.go
  pkg/controller/rotation/handle_verification_rotate.go
  pkg/controller/statspuller/handle_pull.go
Labels: approved, cla: yes, lgtm, size/S

#1682 Change CloudSchedulerJobFailed duration to 1s
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1683 Update architecture docs
  README.md
  docs/architecture.md
Labels: approved, cla: yes, lgtm, size/L

#1686 give stats puller signer verifier
  terraform/service_stats_puller.tf
Labels: approved, cla: yes, lgtm, size/XS

#1687 log signer error
  pkg/controller/statspuller/handle_pull.go
Labels: approved, cla: yes, lgtm, size/XS

#1689 Different default audience for stats-puller
  pkg/config/stats_puller_config.go
  pkg/controller/statspuller/handle_pull.go
Labels: approved, cla: yes, lgtm, size/S

#1690 Ensure permissions are applied for cleanup service
  terraform/service_cleanup.tf
Labels: approved, cla: yes, lgtm, size/XS

#1685 Make key server json available over apiserver
  internal/routes/adminapi.go
Labels: approved, cla: yes, lgtm, size/XS

#1688 My dockerfiles work with this change
  builders/enx-redirect.dockerfile
  builders/server.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1691 Key server stats marshal to CSV
  go.mod
  go.sum
  internal/routes/adminapi.go
  internal/routes/server.go
  pkg/controller/stats/key_server.go
Labels: approved, cla: yes, lgtm, size/S

#1693 Change CloudScheduler alert to paging alert
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS
