Repository google/exposure-notifications-verification-server, pull requests merged in 2021-02, with the labels that each got.

#1743 Bump key-server dep to v0.21.0
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#1744 Unclosed h5 tag. All json/csv as footers
  cmd/server/assets/realmadmin/_stats_codes.html
  cmd/server/assets/realmadmin/_stats_keyserver.html
  cmd/server/assets/realmadmin/_stats_tokens.html
  cmd/server/assets/realmadmin/stats.html
Labels: approved, cla: yes, lgtm, size/M

#1745 Include multiline and whitespace in search in SMS preview
  cmd/server/assets/realmadmin/_form_sms.html
Labels: approved, cla: yes, lgtm, size/XS

#1746 Test render of all the code pages
  cmd/server/assets/codes/index.html
  cmd/server/assets/codes/show.html
  pkg/controller/codes/api.go
  pkg/controller/codes/expire.go
  pkg/controller/codes/expire_test.go
  pkg/controller/codes/index_test.go
  pkg/controller/codes/issue_test.go
  pkg/controller/codes/logic.go
  pkg/controller/codes/show.go
  pkg/controller/codes/show_test.go
Labels: approved, cla: yes, lgtm, size/L

#1748 Cover expire API
  pkg/controller/codes/expire_test.go
  pkg/controller/codes/index.go
Labels: approved, cla: yes, lgtm, size/M

#1751 don't pass redis password when auth disabled
  terraform/main.tf
  terraform/redis.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/S

#1749 Cover some /codes error cases
  pkg/controller/codes/expire_test.go
  pkg/controller/codes/logic.go
  pkg/controller/codes/show.go
  pkg/controller/codes/show_test.go
Labels: approved, cla: yes, lgtm, size/L

#1755 Add test coverage for /login submit actions
  internal/auth/local.go
  pkg/controller/codes/expire_test.go
  pkg/controller/login/change_password_test.go
  pkg/controller/login/reauth_test.go
  pkg/controller/login/reset_password_test.go
  pkg/controller/login/select_password_test.go
  pkg/controller/login/select_realm_test.go
  pkg/controller/login/verify_email_send_test.go
Labels: approved, cla: yes, lgtm, size/L

#1756 Coverage for /user
  pkg/controller/user/bulk_permisisons_test.go
  pkg/controller/user/import_batch.go
  pkg/controller/user/import_batch_test.go
  pkg/controller/user/import_test.go
  pkg/controller/user/index_search_test.go
  pkg/controller/user/reset_password_test.go
Labels: approved, cla: yes, lgtm, size/L

#1757 Add tests for rbac
  pkg/rbac/rbac_test.go
Labels: approved, cla: yes, lgtm, size/L

#1759 Add more rotation tests
  pkg/controller/rotation/handle_token_rotate_test.go
  pkg/controller/rotation/handle_verification_rotate_test.go
Labels: approved, cla: yes, lgtm, size/L

#1758 Simple test for noop SMS
  pkg/sms/noop_test.go
Labels: approved, cla: yes, lgtm, size/M

#1762 Double frequency for stats
  terraform/service_stats_puller.tf
Labels: approved, cla: yes, lgtm, size/XS

#1763 Fix data race
  pkg/database/config.go
  pkg/database/database_util.go
Labels: approved, cla: yes, lgtm, size/M

#1764 trim a whitespace
  terraform/service_stats_puller.tf
Labels: approved, cla: yes, lgtm, size/XS

#1765 fixing chart description wording
  cmd/server/assets/realmadmin/_stats_keyserver.html
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1767 Upgrade key server to main to pull in KMS fix
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/XS

#1768 Upgrade to gcloud 324.0.0 in builds
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
Labels: approved, cla: yes, lgtm, size/M

#1769 Add key-server stats route to docs
  docs/api.md
Labels: approved, cla: yes, lgtm, size/XS

#1773 Highlight when a message crosses an SMS boundary
  cmd/server/assets/realmadmin/_form_sms.html
Labels: approved, cla: yes, lgtm, size/M

#1772 Check session idleness in login
  internal/routes/server.go
  pkg/controller/middleware/sessions.go
Labels: approved, cla: yes, lgtm, size/M

#1774 Do not debug log on rate limiting, log on rate limited
  pkg/ratelimit/limitware/middleware.go
Labels: approved, cla: yes, lgtm, size/S

#1775 Add ignore_changes to prevent recurring diff
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_rotation.tf
  terraform/service_server.tf
  terraform/service_stats_puller.tf
Labels: approved, cla: yes, lgtm, size/M

#1776 Update example tf
  terraform/README.md
Labels: approved, cla: yes, lgtm, size/S

#1739 Update probers to check database for uptime
  terraform/alerting/probers.tf
Labels: approved, cla: yes, kind/release-blocking, lgtm, size/XS

#1778 Update paging and non-paging alerts
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/XS

#1779 Update google provider version.
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#1780 Set sample_rate to null if lb logging is not enabled.
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
Labels: approved, cla: yes, lgtm, size/S

#1782 Add custom tooltips for key-server stats
  cmd/server/assets/realmadmin/_stats_keyserver.html
  cmd/server/assets/static/css/application.css
Labels: approved, cla: yes, lgtm, size/M

#1783 Add sandbox annotation
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_rotation.tf
  terraform/service_server.tf
  terraform/service_stats_puller.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/S

#1784 Percentage in tooltip
  cmd/server/assets/realmadmin/_stats_codes.html
Labels: approved, cla: yes, lgtm, size/S

#1786 Ensure stats queries are run in tests
  pkg/database/user_stats_test.go
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/M

#1787 scope to 'if' and include a cacher
  pkg/database/vercode_test.go
Labels: approved, cla: yes, lgtm, size/S

#1788 Clarify what the graph ticks mean
  cmd/server/assets/realmadmin/_stats_codes.html
  cmd/server/assets/realmadmin/_stats_keyserver.html
Labels: approved, cla: yes, lgtm, size/S

#1790 Document example key server statistics
  cmd/server/assets/realmadmin/_stats_keyserver.html
  docs/images/admin/stats.png
  docs/realm-admin-guide.md
Labels: approved, cla: yes, lgtm, size/M

#1789 Label graph ticks from 0
  cmd/server/assets/realmadmin/_stats_keyserver.html
Labels: approved, cla: yes, lgtm, size/M

#1791 Add BETA launch stage annotation.
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/XS

#1792 Use a chromedp test for bulk-issue
  cmd/server/assets/codes/bulk-issue.html
  go.mod
  go.sum
  pkg/controller/codes/bulk_issue_test.go
  pkg/database/bulk_permission.go
  pkg/render/test_renderer.go
Labels: approved, cla: yes, lgtm, size/L

#1793 Remove Renderer interface
  cmd/e2e-runner/main.go
  pkg/controller/admin/admin.go
  pkg/controller/apikey/apikey.go
  pkg/controller/appsync/controller.go
  pkg/controller/associated/associated.go
  pkg/controller/certapi/certapi.go
  pkg/controller/cleanup/cleanup.go
  pkg/controller/codes/controller.go
  pkg/controller/controller.go
  pkg/controller/email.go
  pkg/controller/healthz.go
  pkg/controller/issueapi/controller.go
  pkg/controller/jwks/jwks.go
  pkg/controller/login/controller.go
  pkg/controller/middleware/apikey.go
  pkg/controller/middleware/auth.go
  pkg/controller/middleware/csrf.go
  pkg/controller/middleware/email_verified.go
  pkg/controller/middleware/enabled.go
  pkg/controller/middleware/firewall.go
  pkg/controller/middleware/header.go
  pkg/controller/middleware/membership.go
  pkg/controller/middleware/mfa.go
  pkg/controller/middleware/request_id.go
  pkg/controller/middleware/sessions.go
  pkg/controller/mobileapps/mobileapps.go
  pkg/controller/modeler/modeler.go
  pkg/controller/realmadmin/realmadmin.go
  pkg/controller/realmkeys/realmkeys.go
  pkg/controller/redirect/redirect.go
  pkg/controller/rotation/rotation.go
  pkg/controller/smskeys/smskeys.go
  pkg/controller/stats/stats.go
  pkg/controller/statspuller/statspull.go
  pkg/controller/user/user.go
  pkg/controller/verifyapi/verifyapi.go
  pkg/render/csv.go
  pkg/render/email.go
  pkg/render/html.go
  pkg/render/json.go
  pkg/render/renderer.go
  pkg/render/renderer_impl.go
Labels: approved, cla: yes, lgtm, size/XL

#1795 Tweak doc with bootstrap note
  docs/system-admin-guide.md
Labels: approved, cla: yes, lgtm, size/XS

#1797 Chart titles - remove 'age'
  cmd/server/assets/realmadmin/_stats_codes.html
Labels: approved, cla: yes, lgtm, size/S

#1799 User feedback on stats
  cmd/server/assets/realmadmin/_stats_codes.html
  cmd/server/assets/realmadmin/_stats_keyserver.html
Labels: approved, cla: yes, lgtm, size/XS

#1796 Use shared observability code from key server.
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/appsync/main.go
  cmd/cleanup/main.go
  cmd/e2e-runner/main.go
  cmd/enx-redirect/main.go
  cmd/migrate/main.go
  cmd/modeler/main.go
  cmd/rotation/main.go
  cmd/server/main.go
  cmd/stats-puller/main.go
  go.mod
  go.sum
  internal/buildinfo/buildinfo.go
  internal/clients/e2e.go
  pkg/controller/certapi/certificate.go
  pkg/controller/certapi/metrics.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/cleanup/metrics.go
  pkg/controller/issueapi/controller.go
  pkg/controller/issueapi/gen_code.go
  pkg/controller/issueapi/handle_issue.go
  pkg/controller/issueapi/handle_issue_batch.go
  pkg/controller/issueapi/metrics.go
  pkg/controller/issueapi/parse_date.go
  pkg/controller/issueapi/send_sms.go
  pkg/controller/issueapi/validate_code.go
  pkg/controller/middleware/debug.go
  pkg/controller/middleware/observability.go
  pkg/controller/middleware/template.go
  pkg/controller/rotation/handle_token_rotate.go
  pkg/controller/rotation/metrics.go
  pkg/controller/user/metrics.go
  pkg/controller/verifyapi/metrics.go
  pkg/controller/verifyapi/verify.go
  pkg/database/database.go
  pkg/database/metrics.go
  pkg/observability/observability.go
  pkg/ratelimit/limitware/metrics.go
  pkg/ratelimit/limitware/middleware.go
  terraform/module.service-boilerplate/main.tf
  terraform/module.service-boilerplate/module.iam/main.tf
  terraform/module.service-boilerplate/module.iam/variables.tf
Labels: approved, cla: yes, lgtm, size/XL

#1800 Ensure error from retry is bubbled to the caller
  pkg/controller/issueapi/gen_code.go
Labels: approved, cla: yes, lgtm, size/S

#1802 Run more checkers in the same job
  .github/workflows/codereview.yaml
Labels: approved, cla: yes, lgtm, size/M

#1803 Move tabcheck into GitHub Actions
  .github/workflows/codereview.yaml
  Makefile
  scripts/presubmit.sh
Labels: approved, cla: yes, lgtm, size/M

#1804 Handle sms errors in the function
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/send_sms.go
  pkg/controller/issueapi/send_sms_test.go
Labels: approved, cla: yes, lgtm, size/M

#1806 Allow parallel linting, fix missing newline
  .golangci.yaml
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#1808 Add a test for session
  pkg/controller/login/session_test.go
Labels: approved, cla: yes, lgtm, size/M

#1810 Update to latest key server dependencies
  Makefile
  builders/build.yaml
  go.mod
  go.sum
  internal/browser/executor.go
  internal/envstest/harness.go
  pkg/config/config.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/database_util.go
  scripts/build
  scripts/presubmit.sh
  tools/gen-keys/main.go
Labels: approved, cla: yes, lgtm, size/XL

#1811 Update retry_count and database backup to synchronous
  terraform/database.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_rotation.tf
  terraform/service_stats_puller.tf
Labels: approved, cla: yes, lgtm, size/S

#1809 Run go tests on GitHub Actions
  .github/workflows/ci.yaml
  .github/workflows/terraform.yml
  .gitignore
  Makefile
  pkg/controller/admin/caches_test.go
  pkg/controller/admin/email_test.go
  pkg/controller/admin/events_test.go
  pkg/controller/admin/info_test.go
  pkg/controller/admin/mobile_apps_test.go
  pkg/controller/admin/realms_test.go
  pkg/controller/admin/sms_test.go
  pkg/controller/admin/users_list_test.go
  pkg/controller/apikey/create_test.go
  pkg/controller/apikey/disable_test.go
  pkg/controller/apikey/enable_test.go
  pkg/controller/apikey/index_test.go
  pkg/controller/apikey/show_test.go
  pkg/controller/apikey/update_test.go
  pkg/controller/codes/bulk_issue_test.go
  pkg/controller/codes/expire_test.go
  pkg/controller/codes/index_test.go
  pkg/controller/codes/issue_test.go
  pkg/controller/codes/show_test.go
  pkg/controller/login/account_test.go
  pkg/controller/login/change_password_test.go
  pkg/controller/login/login_test.go
  pkg/controller/login/reauth_test.go
  pkg/controller/login/register_phone_test.go
  pkg/controller/login/reset_password_test.go
  pkg/controller/login/select_password_test.go
  pkg/controller/login/select_realm_test.go
  pkg/controller/login/signout_test.go
  pkg/controller/login/verify_email_receive_test.go
  pkg/controller/login/verify_email_send_test.go
  pkg/controller/mobileapps/create_test.go
  pkg/controller/mobileapps/disable_test.go
  pkg/controller/mobileapps/enable_test.go
  pkg/controller/mobileapps/index_test.go
  pkg/controller/mobileapps/show_test.go
  pkg/controller/mobileapps/update_test.go
  pkg/controller/realmadmin/events_test.go
  pkg/controller/realmadmin/sms_test.go
  pkg/controller/realmadmin/smtp_test.go
  pkg/controller/realmadmin/stats_test.go
  pkg/controller/realmkeys/index_test.go
  pkg/controller/user/create_test.go
  pkg/controller/user/delete_test.go
  pkg/controller/user/import_test.go
  pkg/controller/user/index_search_test.go
  pkg/controller/user/index_test.go
  pkg/controller/user/show_test.go
  pkg/controller/user/update_test.go
  pkg/sms/twilio_test.go
  scripts/ci-terraform.sh
  terraform-e2e-ci/README.md
  terraform-e2e-ci/main.tf
  terraform/mirror/docker.tf
  terraform/mirror/main.tf
  terraform/mirror/service.tf
  terraform/mirror/variables.tf
Labels: approved, cla: yes, lgtm, size/XL

#1812 remove stats piece
  docs/api.md
Labels: approved, cla: yes, lgtm, size/XS

#1817 Upgrade key server pin to v0.22.0
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#1818 Set blobstore, key manager, and secret manager in migrate
  builders/migrate.yaml
  scripts/migrate
Labels: approved, cla: yes, lgtm, size/XS

#1820 Set blobstore, key manager, and secret manager on services
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/XS

#1821 Ignore more annotations in Terraform diff
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_rotation.tf
  terraform/service_server.tf
  terraform/service_stats_puller.tf
Labels: approved, cla: yes, lgtm, size/M

#1822 Use append instead of inserting at index
  internal/clients/e2e.go
Labels: approved, cla: yes, lgtm, size/XS

#1828 Wrap returned error from decoding form
  pkg/controller/form.go
Labels: approved, cla: yes, lgtm, size/XS

#1831 admin API needs signing config to get key manager settings
  terraform/service_admin_apiserver.tf
Labels: approved, cla: yes, lgtm, size/XS

#1826 Make per-test timeout a project function
  internal/project/util.go
  pkg/controller/admin/caches_test.go
  pkg/controller/admin/email_test.go
  pkg/controller/admin/events_test.go
  pkg/controller/admin/info_test.go
  pkg/controller/admin/mobile_apps_test.go
  pkg/controller/admin/realms_test.go
  pkg/controller/admin/sms_test.go
  pkg/controller/admin/users_list_test.go
  pkg/controller/apikey/create_test.go
  pkg/controller/apikey/disable_test.go
  pkg/controller/apikey/enable_test.go
  pkg/controller/apikey/index_test.go
  pkg/controller/apikey/show_test.go
  pkg/controller/apikey/update_test.go
  pkg/controller/codes/bulk_issue_test.go
  pkg/controller/codes/expire_test.go
  pkg/controller/codes/index_test.go
  pkg/controller/codes/issue_test.go
  pkg/controller/codes/show_test.go
  pkg/controller/login/account_test.go
  pkg/controller/login/change_password_test.go
  pkg/controller/login/login_test.go
  pkg/controller/login/reauth_test.go
  pkg/controller/login/register_phone_test.go
  pkg/controller/login/reset_password_test.go
  pkg/controller/login/select_password_test.go
  pkg/controller/login/select_realm_test.go
  pkg/controller/login/signout_test.go
  pkg/controller/login/verify_email_receive_test.go
  pkg/controller/login/verify_email_send_test.go
  pkg/controller/mobileapps/create_test.go
  pkg/controller/mobileapps/disable_test.go
  pkg/controller/mobileapps/enable_test.go
  pkg/controller/mobileapps/index_test.go
  pkg/controller/mobileapps/show_test.go
  pkg/controller/mobileapps/update_test.go
  pkg/controller/realmadmin/events_test.go
  pkg/controller/realmadmin/sms_test.go
  pkg/controller/realmadmin/smtp_test.go
  pkg/controller/realmadmin/stats_test.go
  pkg/controller/realmkeys/index_test.go
  pkg/controller/user/create_test.go
  pkg/controller/user/delete_test.go
  pkg/controller/user/import_test.go
  pkg/controller/user/index_search_test.go
  pkg/controller/user/index_test.go
  pkg/controller/user/show_test.go
  pkg/controller/user/update_test.go
Labels: approved, cla: yes, lgtm, size/L

#1827 Add and connect recovery middleware
  cmd/appsync/main.go
  cmd/cleanup/main.go
  cmd/e2e-runner/main.go
  cmd/modeler/main.go
  cmd/rotation/main.go
  cmd/stats-puller/main.go
  internal/routes/adminapi.go
  internal/routes/apiserver.go
  internal/routes/enx_redirect.go
  internal/routes/server.go
  pkg/controller/middleware/recovery.go
  pkg/controller/middleware/recovery_test.go
Labels: approved, cla: yes, lgtm, size/L

#1834 Introduce configurable Authenticated SMS failure modes
  docs/playbooks/alerts/AuthenticatedSMSFailure.md
  pkg/config/admin_server_config.go
  pkg/config/issue.go
  pkg/config/server_config.go
  pkg/config/sms_signing_config.go
  pkg/controller/issueapi/metrics.go
  pkg/controller/issueapi/send_sms.go
  pkg/controller/issueapi/send_sms_test.go
  terraform/alerting/alerts.tf
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/L

#1835 updating path of buildinfo package for build flags
  builders/build.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1836 Remove dead link
  docs/playbooks/index.md
Labels: approved, cla: yes, lgtm, size/XS

#1837 Update security alerts for HumanAccessSecret and HumanDecryptedValue
  docs/playbooks/alerts/HumanAccessedSecret.md
  docs/playbooks/alerts/HumanDecryptedValue.md
  terraform/alerting/alerts.tf
  terraform/alerting/monitoring.tf
Labels: approved, cla: yes, lgtm, size/M

#1840 Only update SMS preview when the textarea updates
  cmd/server/assets/realmadmin/_form_sms.html
Labels: approved, cla: yes, lgtm, size/XS

#1839 Send authenticated SMS in e2e-runner
  .github/workflows/ci.yaml
  cmd/e2e-runner/main.go
  docs/images/e2e/authenticated-sms-before-enable.png
  docs/images/e2e/authenticated-sms-enable.png
  docs/images/e2e/sms-settings-tab.png
  docs/production.md
  go.mod
  go.sum
  internal/clients/e2e.go
  internal/envstest/adminapi.go
  internal/envstest/bootstrap.go
  internal/envstest/harness.go
  internal/envstest/integration.go
  internal/envstest/server.go
  internal/project/util.go
  pkg/database/database_util.go
  pkg/integration/enx_redirect_test.go
  pkg/integration/integration_test.go
  pkg/sms/twilio_test.go
  terraform/services.tf
  terraform/variables.tf
Labels: approved, cla: yes, lgtm, size/L

#1842 Get Cloud SQL Proxy from new link
  builders/migrate.dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1843 Only return a signer if Authenticated SMS is enabled
  internal/envstest/adminapi.go
  internal/envstest/apiserver.go
  internal/envstest/enx_redirect.go
  internal/envstest/server.go
  pkg/config/admin_server_config.go
  pkg/config/issue.go
  pkg/config/server_config.go
  pkg/controller/issueapi/issue.go
Labels: approved, cla: yes, lgtm, size/S

#1841 Only run when envvar is set
  internal/envstest/integration.go
  pkg/controller/login/register_phone_test.go
Labels: approved, cla: yes, lgtm, size/S

#1845 Add structured logger for gorm
  pkg/database/database.go
  pkg/database/database_logger.go
  pkg/database/database_logger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1844 Improve cloud scheduler job alerts
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1847 Strictify MQL
  terraform/alerting/alerts.tf
Labels: approved, cla: yes, lgtm, size/S

#1848 Document authenticated sms
  docs/images/admin/authenticated-sms-create-version.png
  docs/images/admin/authenticated-sms-disabled.png
  docs/images/admin/authenticated-sms-enable.png
  docs/images/admin/authenticated-sms-enabled.png
  docs/images/admin/authenticated-sms-key-created.png
  docs/images/admin/sms-settings.png
  docs/images/admin/sms-template.png
  docs/realm-admin-guide.md
Labels: approved, cla: yes, size/M

#1850 Make e2e-runner publish a real client
  cmd/e2e-runner/main.go
  internal/clients/e2e.go
  internal/clients/key_server.go
  terraform/services.tf
Labels: approved, cla: yes, lgtm, size/M

#1851 Create session.Values if empty
  pkg/controller/flash.go
Labels: approved, cla: yes, lgtm, size/XS

#1852 Refactor user tests to use less chromedp
  .github/workflows/ci.yaml
  internal/envstest/adminapi.go
  internal/envstest/apiserver.go
  internal/envstest/enx_redirect.go
  internal/envstest/harness.go
  internal/envstest/helpers.go
  internal/envstest/integration.go
  internal/envstest/server.go
  internal/envstest/unit.go
  pkg/controller/user/bulk_permisisons_test.go
  pkg/controller/user/create_test.go
  pkg/controller/user/delete_test.go
  pkg/controller/user/export.go
  pkg/controller/user/export_test.go
  pkg/controller/user/import_batch_test.go
  pkg/controller/user/import_test.go
  pkg/controller/user/index_search_test.go
  pkg/controller/user/index_test.go
  pkg/controller/user/reset_password_test.go
  pkg/controller/user/show_test.go
  pkg/controller/user/update_test.go
  pkg/controller/user/user_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1853 Only test verification server with google tags
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#1854 Also run tests on main
  .github/workflows/ci.yaml
  .github/workflows/stale.yml
  .github/workflows/terraform.yml
Labels: approved, cla: yes, lgtm, size/S

#1855 Disable authenticated sms in tests when the creds are missing
  internal/envstest/integration.go
Labels: approved, cla: yes, lgtm, size/XS

#1856 Merge e2e tests and integration tests
  .github/workflows/ci.yaml
  internal/envstest/integration.go
  pkg/integration/integration_test.go
Labels: approved, cla: yes, lgtm, size/L

#1849 Process one class of HTTP status constants to named constants
  internal/clients/enx_redirect.go
  internal/envstest/unit.go
  pkg/controller/admin/caches_test.go
  pkg/controller/admin/email_test.go
  pkg/controller/admin/events_test.go
  pkg/controller/admin/info_test.go
  pkg/controller/admin/mobile_apps_test.go
  pkg/controller/admin/realms_test.go
  pkg/controller/admin/users_list_test.go
  pkg/controller/admin/users_operations_test.go
  pkg/controller/apikey/create_test.go
  pkg/controller/apikey/disable_test.go
  pkg/controller/apikey/enable_test.go
  pkg/controller/apikey/index_test.go
  pkg/controller/apikey/show_test.go
  pkg/controller/apikey/update_test.go
  pkg/controller/appsync/handle_sync_test.go
  pkg/controller/associated/index_test.go
  pkg/controller/login/post_authenticate_test.go
  pkg/controller/mobileapps/create_test.go
  pkg/controller/mobileapps/disable_test.go
  pkg/controller/mobileapps/enable_test.go
  pkg/controller/mobileapps/index_test.go
  pkg/controller/mobileapps/show_test.go
  pkg/controller/mobileapps/update_test.go
  pkg/controller/realmadmin/events_test.go
  pkg/controller/realmadmin/express_disable_test.go
  pkg/controller/realmadmin/express_enable_test.go
  pkg/controller/realmadmin/settings_modify_test.go
  pkg/controller/realmkeys/automatic_rotate_test.go
  pkg/controller/realmkeys/manual_rotate_test.go
  pkg/controller/redirect/index_test.go
  pkg/controller/rotation/handle_token_rotate_test.go
  pkg/controller/rotation/handle_verification_rotate_test.go
  pkg/controller/smskeys/activate_test.go
  pkg/controller/smskeys/create_test.go
  pkg/controller/smskeys/destroy_test.go
  pkg/controller/smskeys/disable_test.go
  pkg/controller/smskeys/enable_test.go
  pkg/controller/smskeys/index_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1857 Use less chromedp and less database churn in API key tests
  pkg/controller/apikey/create_test.go
  pkg/controller/apikey/disable_test.go
  pkg/controller/apikey/enable_test.go
  pkg/controller/apikey/index_test.go
  pkg/controller/apikey/show_test.go
  pkg/controller/apikey/update_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1858 Link out to Twilio splits calculator for advanced calculations
  cmd/server/assets/realmadmin/_form_sms.html
Labels: approved, cla: yes, lgtm, size/XS

#1859 Reduce arbitrary sleeps in tests
  pkg/controller/appsync/appsync.go
  pkg/controller/appsync/appsync_test.go
  pkg/controller/appsync/controller_test.go
  pkg/controller/appsync/handle_sync_test.go
  pkg/controller/cleanup/handle_cleanup_test.go
  pkg/controller/rotation/handle_token_rotate_test.go
  pkg/controller/rotation/handle_verification_rotate_test.go
Labels: approved, cla: yes, lgtm, size/L

#1860 Change rate limiting defaults to 120/min
  pkg/ratelimit/config.go
Labels: approved, cla: yes, lgtm, size/XS

#1861 Use less chromedp on admin controller tests
  pkg/controller/admin/caches_test.go
  pkg/controller/admin/email_test.go
  pkg/controller/admin/events_test.go
  pkg/controller/admin/info_test.go
  pkg/controller/admin/mobile_apps_test.go
  pkg/controller/admin/realms.go
  pkg/controller/admin/realms_test.go
  pkg/controller/admin/sms_test.go
  pkg/controller/admin/users_list_test.go
  pkg/controller/admin/users_operations_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1865 Upgrade to Go 1.16
  .github/workflows/ci.yaml
  builders/build.yaml
  cmd/adminapi/main.go
  cmd/apiserver/main.go
  cmd/appsync/main.go
  cmd/cleanup/main.go
  cmd/e2e-runner/main.go
  cmd/enx-redirect/main.go
  cmd/migrate/main.go
  cmd/modeler/main.go
  cmd/rotation/main.go
  cmd/server/main.go
  cmd/stats-puller/main.go
  docs/images/architecture/go.mod
  go.mod
  go.sum
  internal/clients/clients.go
  internal/envstest/harness.go
  internal/envstest/sql.go
  internal/firebase/password_reset_email.go
  internal/firebase/verify_email.go
  internal/firebase/verify_password_reset_code.go
  internal/i18n/i18n.go
  pkg/cache/cacher_test.go
  pkg/controller/associated/index_test.go
  pkg/controller/redirect/index_test.go
  pkg/database/database.go
  pkg/database/database_test.go
  pkg/database/database_util.go
  pkg/sms/twilio.go
  tools/e2e-test/main.go
  tools/gen-keys/main.go
  tools/gen-secret/main.go
  tools/get-certificate/main.go
  tools/get-code/main.go
  tools/get-token/main.go
  tools/seed/main.go
  tools/verify-sms-signature/main.go
Labels: approved, cla: yes, lgtm, size/L

#1862 Use less chromedp on codes tests
  internal/routes/adminapi.go
  internal/routes/server.go
  pkg/controller/admin/events_test.go
  pkg/controller/codes/bulk_issue_test.go
  pkg/controller/codes/controller.go
  pkg/controller/codes/expire.go
  pkg/controller/codes/expire_test.go
  pkg/controller/codes/index.go
  pkg/controller/codes/index_test.go
  pkg/controller/codes/show_test.go
Labels: approved, cla: yes, size/XL

#1863 Use less chromedp in login controller
  pkg/controller/issueapi/gen_code_test.go
  pkg/controller/issueapi/handle_issue_batch_test.go
  pkg/controller/issueapi/handle_issue_test.go
  pkg/controller/issueapi/issue_test.go
  pkg/controller/issueapi/issueapi_test.go
  pkg/controller/issueapi/parse_date_test.go
  pkg/controller/issueapi/send_sms_test.go
  pkg/controller/issueapi/validate_code_test.go
  pkg/controller/login/account_test.go
  pkg/controller/login/change_password_test.go
  pkg/controller/login/login_test.go
  pkg/controller/login/post_authenticate_test.go
  pkg/controller/login/reauth_test.go
  pkg/controller/login/register_phone_test.go
  pkg/controller/login/reset_password_test.go
  pkg/controller/login/select_password_test.go
  pkg/controller/login/select_realm_test.go
  pkg/controller/login/session_test.go
  pkg/controller/login/signout_test.go
  pkg/controller/login/verify_email_receive_test.go
  pkg/controller/login/verify_email_send_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1866 Drop support for crypto/dsa in public key parsing
  pkg/keyutils/public_keys.go
Labels: approved, cla: yes, lgtm, size/XS

#1867 Clarify claim latency charts
  cmd/server/assets/realmadmin/_stats_codes.html
Labels: approved, cla: yes, kind/statistics, lgtm, size/S

#1870 Set service names and fix build cache
  builders/build.yaml
Labels: approved, cla: yes, lgtm, size/M

#1869 Do not remove ASSETS_PATH and LOCALES_PATH from Terraform yet
  terraform/service_server.tf
  terraform/services.tf
Labels: approved, cla: yes, size/XS

#1873 Capture "error" gorm output too
  pkg/database/database_logger.go
  pkg/database/database_logger_test.go
Labels: approved, cla: yes, lgtm, size/S

#1872 Remove deprecated TOKEN_SIGNING_KEYS
  internal/envstest/apiserver.go
  pkg/config/token_signing_config.go
  pkg/controller/certapi/certapi.go
  pkg/controller/cleanup/handle_cleanup_test.go
  pkg/controller/rotation/handle_token_rotate.go
  pkg/controller/rotation/handle_token_rotate_test.go
  pkg/controller/verifyapi/verify.go
  terraform/services.tf
  tools/seed/main.go
Labels: approved, cla: yes, lgtm, size/L

#1871 Remove unneeded chromedp from realmadmin and realmkeys
  builders/build.yaml
  pkg/controller/mobileapps/create_test.go
  pkg/controller/mobileapps/disable_test.go
  pkg/controller/mobileapps/enable_test.go
  pkg/controller/mobileapps/index_test.go
  pkg/controller/mobileapps/show_test.go
  pkg/controller/mobileapps/update_test.go
  pkg/controller/realmadmin/events_test.go
  pkg/controller/realmadmin/express_disable_test.go
  pkg/controller/realmadmin/express_enable_test.go
  pkg/controller/realmadmin/settings_modify_test.go
  pkg/controller/realmadmin/sms_test.go
  pkg/controller/realmadmin/smtp_test.go
  pkg/controller/realmadmin/stats_test.go
  pkg/controller/realmkeys/activate_test.go
  pkg/controller/realmkeys/index_test.go
  pkg/database/mobile_app.go
Labels: approved, cla: yes, size/XXL

#1874 Fix updated linter issues
  .github/workflows/ci.yaml
  internal/i18n/i18n.go
  internal/i18n/i18n_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1877 Allow setting system notices
  assets/server/header.html
  docs/images/system-admin/system-notice.png
  docs/system-admin-guide.md
  pkg/config/server_config.go
  pkg/controller/middleware/template.go
Labels: approved, cla: yes, lgtm, size/M

#1878 Do not use embedded fs in dev mode
  assets/assets.go
  internal/project/util.go
Labels: approved, cla: yes, lgtm, size/S

#1879 Enable query insights
  terraform/database.tf
Labels: approved, cla: yes, lgtm, size/XS

#1881 Upgrade to Firebase auth 8.2.9
  assets/server/firebase.html
Labels: approved, cla: yes, lgtm, size/XS

#1882 Change to tmpdir when installing linters
  Makefile
Labels: approved, cla: yes, lgtm, size/XS

#1885 Skip golang-ci restoring the cache
  .github/workflows/ci.yaml
Labels: approved, cla: yes, size/XS

#1884 Update to latest bootstrap, jquery, and intlTelInput
  assets/server/header.html
Labels: approved, cla: yes, size/S

#1883 Add more debug output when chromedp fails
  pkg/controller/codes/issue_test.go
Labels: approved, cla: yes, size/XS

#1888 Remove shared state from tests
  internal/envstest/unit.go
  pkg/controller/apikey/create_test.go
  pkg/controller/apikey/disable_test.go
  pkg/controller/apikey/enable_test.go
  pkg/controller/apikey/index_test.go
  pkg/controller/apikey/show_test.go
  pkg/controller/apikey/update_test.go
  pkg/controller/mobileapps/create_test.go
  pkg/controller/mobileapps/disable_test.go
  pkg/controller/mobileapps/enable_test.go
  pkg/controller/mobileapps/index_test.go
  pkg/controller/mobileapps/show_test.go
  pkg/controller/mobileapps/update_test.go
  pkg/controller/realmadmin/events_test.go
  pkg/controller/realmadmin/settings_modify_test.go
  pkg/controller/realmkeys/activate.go
  pkg/controller/realmkeys/activate_test.go
  pkg/controller/realmkeys/automatic_rotate_test.go
  pkg/controller/realmkeys/create_test.go
  pkg/controller/realmkeys/destroy.go
  pkg/controller/realmkeys/destroy_test.go
  pkg/controller/realmkeys/manual_rotate_test.go
  pkg/controller/realmkeys/save.go
  pkg/controller/realmkeys/save_test.go
  pkg/controller/realmkeys/upgrade_test.go
  pkg/controller/smskeys/activate_test.go
  pkg/controller/smskeys/create_test.go
  pkg/controller/smskeys/destroy_test.go
  pkg/controller/smskeys/disable_test.go
  pkg/controller/smskeys/enable_test.go
  pkg/controller/smskeys/index_test.go
  pkg/controller/user/bulk_permisisons_test.go
  pkg/controller/user/create_test.go
  pkg/controller/user/delete_test.go
  pkg/controller/user/export_test.go
  pkg/controller/user/import_batch_test.go
  pkg/controller/user/import_test.go
  pkg/controller/user/index_test.go
  pkg/controller/user/reset_password_test.go
  pkg/controller/user/show_test.go
  pkg/controller/user/update_test.go
  pkg/controller/user/user_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1886 change chart combos
  assets/server/realmadmin/_stats_codes.html
  assets/server/realmadmin/_stats_keyserver.html
  assets/server/realmadmin/stats.html
  docs/api.md
  go.mod
  go.sum
  internal/routes/server.go
  pkg/controller/realmadmin/events_test.go
  pkg/controller/realmadmin/express_disable_test.go
  pkg/controller/realmadmin/express_enable_test.go
  pkg/controller/realmadmin/realmadmin.go
  pkg/controller/realmadmin/settings_modify_test.go
  pkg/controller/realmadmin/sms_test.go
  pkg/controller/realmadmin/smtp_test.go
  pkg/controller/realmadmin/stats.go
  pkg/controller/realmadmin/stats_test.go
  pkg/controller/stats/composite.go
  pkg/database/database.go
  pkg/database/key_server_stats.go
  pkg/database/realm_stats.go
Labels: approved, cla: yes, kind/statistics, lgtm, size/XL
