Repository google/exposure-notifications-verification-server, pull requests merged in 2021-04, with the labels that each got.

#1969 add Arabic translations and right-aligned locale option
  assets/server/codes/bulk-issue.html
  assets/server/codes/issue.html
  assets/server/header.html
  assets/server/static/css/application.css
  internal/i18n/i18n.go
  internal/i18n/i18n_test.go
  internal/i18n/locales/ar/default.po
  pkg/controller/middleware/i18n.go
  terraform/verification-lb.tf
Labels: cla: yes, kind/enhancement

#1971 user report messaging and signing
  assets/server/realmadmin/_form_sms.html
  pkg/controller/issueapi/send_sms.go
  pkg/signatures/sms.go
Labels: cla: yes, kind/enhancement

#1973 capture OS in request context from user agent
  internal/routes/apiserver.go
  pkg/controller/context.go
  pkg/controller/middleware/operating_system.go
  pkg/controller/middleware/operating_system_test.go
Labels: cla: yes, kind/enhancement

#1974 remove add that wasn't ready
  terraform/verification-lb.tf
Labels: cla: yes

#1975 capture invalid codes by os in realm_stats
  internal/clients/clients.go
  pkg/controller/context.go
  pkg/controller/middleware/operating_system.go
  pkg/controller/middleware/operating_system_test.go
  pkg/controller/verifyapi/verify.go
  pkg/database/migrations.go
  pkg/database/mobile_app.go
  pkg/database/realm_stats.go
  pkg/database/token.go
  tools/get-token/main.go
Labels: cla: yes

#1976 chart of invalid codes by OS
  assets/server/realmadmin/_stats_codes.html
  assets/server/static/js/application.js
  pkg/database/composite_stats.go
  pkg/database/composite_stats_test.go
  pkg/database/realm.go
  pkg/database/realm_stats.go
  pkg/database/realm_stats_test.go
  tools/seed/main.go
Labels: cla: yes, kind/statistics

#1977 hint that app store redirectect should be off for join iOS enx and cu…
  assets/server/mobileapps/_app.html
Labels: cla: yes

#1978 Add some translations for login and password resets
  assets/server/flash.html
  assets/server/header.html
  assets/server/login/account.html
  assets/server/login/login.html
  assets/server/login/register-phone.html
  assets/server/login/reset-password.html
  assets/server/static/css/application.css
  docs/realm-admin-guide.md
  internal/envstest/server.go
  internal/i18n/locales/ar/default.po
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/id/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/mn/default.po
  internal/i18n/locales/ph/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
  pkg/config/server_config.go
  pkg/controller/admin/caches_test.go
  pkg/controller/admin/events_test.go
  pkg/controller/admin/info_test.go
  pkg/controller/admin/mobile_apps_test.go
  pkg/controller/admin/realms_test.go
  pkg/controller/admin/users_list_test.go
  pkg/controller/admin/users_operations_test.go
  pkg/controller/codes/bulk_issue_test.go
  pkg/controller/codes/expire_test.go
  pkg/controller/codes/index_test.go
  pkg/controller/codes/show_test.go
  pkg/controller/login/account_test.go
  pkg/controller/login/change_password_test.go
  pkg/controller/login/login_test.go
  pkg/controller/login/post_authenticate_test.go
  pkg/controller/login/reauth_test.go
  pkg/controller/login/register_phone_test.go
  pkg/controller/login/reset_password_test.go
  pkg/controller/login/select_password_test.go
  pkg/controller/login/select_realm_test.go
  pkg/controller/login/session_test.go
  pkg/controller/login/signout_test.go
  pkg/controller/login/verify_email_receive_test.go
  pkg/controller/login/verify_email_send_test.go
  scripts/dev
Labels: cla: yes

#1980 Update change password javascript and styles
  assets/assets.go
  assets/server/login/_loginscripts.html
  assets/server/login/change-password.html
  assets/server/static/js/application.js
Labels: cla: yes

#1983 authenticated SMS to default on
  pkg/config/feature_config.go
Labels: cla: yes

#1981 Update deps
  go.mod
  go.sum
  internal/i18n/i18n_test.go
Labels: cla: yes

#1982 only redirect for known host headers
  terraform/verification-lb.tf
Labels: cla: yes, kind/infrastructure

#1984 specific host match redirect rules for ENX redirect domains
  terraform/redirect-lb.tf
Labels: cla: yes, kind/infrastructure

#1986 Fix names on path matcher rules
  terraform/redirect-lb.tf
Labels: cla: yes

#1988 Load javascript asynchronously
  assets/server/admin/sms/show.html
  assets/server/apikeys/show.html
  assets/server/codes/bulk-issue.html
  assets/server/codes/index.html
  assets/server/codes/issue.html
  assets/server/codes/show.html
  assets/server/firebase.html
  assets/server/header.html
  assets/server/login/_loginscripts.html
  assets/server/login/change-password.html
  assets/server/login/login.html
  assets/server/login/register-phone.html
  assets/server/login/select-password.html
  assets/server/login/signout.html
  assets/server/login/verify-email-check.html
  assets/server/mobileapps/_app.html
  assets/server/realmadmin/_form_abuse_prevention.html
  assets/server/realmadmin/_form_security.html
  assets/server/realmadmin/_form_sms.html
  assets/server/realmadmin/_stats_codes.html
  assets/server/realmadmin/_stats_external_issuers.html
  assets/server/realmadmin/_stats_keyserver.html
  assets/server/realmadmin/_stats_tokens.html
  assets/server/realmadmin/_stats_users.html
  assets/server/realmadmin/edit.html
  assets/server/realmadmin/keys.html
  assets/server/realmadmin/smskeys.html
  assets/server/realmadmin/stats.html
  assets/server/static/js/application.js
  assets/server/users/_form.html
  assets/server/users/import.html
  assets/server/users/index.html
  assets/server/users/show.html
Labels: cla: yes

#1990 Set cache headers on static assets, do not apply middlewares
  internal/routes/server.go
  pkg/controller/middleware/static.go
  pkg/controller/middleware/static_test.go
Labels: cla: yes

#1991 add warning about UR and auth SMS
  assets/server/realmadmin/_form_codes.html
  assets/server/realmadmin/smskeys.html
Labels: cla: yes, kind/enhancement

#1989 add some UX fixes
  pkg/controller/realmadmin/express_enable.go
  pkg/controller/realmadmin/settings_modify.go
  pkg/controller/realmkeys/save.go
  pkg/controller/realmkeys/save_test.go
Labels: cla: yes

#1992 Minify js and css assets on build
  assets/server/header.html
  builders/build.yaml
Labels: cla: yes

#1993 Flags go on each line
  builders/build.yaml
Labels: cla: yes

#1994 Upgrade to gcloud 335.0.0
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
Labels: cla: yes

#1996 Add translations to change/select password pages
  assets/server/login/_loginscripts.html
  assets/server/login/change-password.html
  assets/server/login/select-password.html
  internal/i18n/locales/ar/default.po
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fil/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/id/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/mn/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
  pkg/controller/login/select_password.go
Labels: cla: yes

#1997 Add translations for signout and realm selection pages
  assets/server/login/select-realm.html
  assets/server/login/signout.html
  internal/i18n/locales/ar/default.po
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fil/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/id/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/mn/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
  pkg/controller/login/select_realm_test.go
Labels: cla: yes

#1999 Add translations for email verify pages
  assets/server/login/verify-email-check.html
  assets/server/login/verify-email.html
  assets/server/static/js/application.js
  internal/i18n/locales/ar/default.po
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fil/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/id/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/mn/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
Labels: cla: yes

#1998 Return gzipped responses if the client requests
  go.mod
  go.sum
  internal/routes/server.go
  pkg/controller/middleware/gzip.go
Labels: cla: yes

#2000 Use min versions of intl-tel-input
  assets/server/codes/issue.html
  assets/server/header.html
  assets/server/login/register-phone.html
Labels: cla: yes

#2001 Retry chromedp test 3 times
  internal/project/util.go
  pkg/controller/codes/issue_test.go
Labels: cla: yes

#2002 Mention links should be clicked on mobile devices
  assets/enx-redirect/404.html
  assets/enx-redirect/header.html
  assets/server/404.html
  internal/i18n/locales/ar/default.po
  internal/i18n/locales/de/default.po
  internal/i18n/locales/en/default.po
  internal/i18n/locales/es/default.po
  internal/i18n/locales/fil/default.po
  internal/i18n/locales/fr/default.po
  internal/i18n/locales/id/default.po
  internal/i18n/locales/it/default.po
  internal/i18n/locales/ja/default.po
  internal/i18n/locales/mn/default.po
  internal/i18n/locales/pt/default.po
  internal/i18n/locales/tr/default.po
  internal/routes/enx_redirect.go
  internal/routes/server.go
  pkg/controller/context.go
  pkg/controller/controller.go
  pkg/render/html.go
Labels: cla: yes

#2003 Untangle co-dependencies on chart javascripts
  assets/server/apikeys/show.html
  assets/server/codes/bulk-issue.html
  assets/server/codes/show.html
  assets/server/firebase.html
  assets/server/login/change-password.html
  assets/server/realmadmin/_stats_codes.html
  assets/server/realmadmin/_stats_external_issuers.html
  assets/server/realmadmin/_stats_keyserver.html
  assets/server/realmadmin/_stats_tokens.html
  assets/server/realmadmin/_stats_users.html
  assets/server/realmadmin/keys.html
  assets/server/realmadmin/smskeys.html
  assets/server/realmadmin/stats.html
  assets/server/static/js/application.js
  assets/server/users/show.html
Labels: cla: yes

#2005 Fix audit logs typo
  pkg/database/realm.go
Labels: cla: yes

#2012 Incorporate translation suggestions
  internal/i18n/locales/ar/default.po
Labels: cla: yes

#2015 Updates to arabic translations
  internal/i18n/locales/ar/default.po
Labels: cla: yes

#2014 Cleanup e2e API keys that have existed for > 24 hours
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/cleanup/handle_cleanup_test.go
  pkg/database/authorized_app.go
  pkg/database/authorized_app_test.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: cla: yes

#2016 Revert "Cleanup e2e API keys that have existed for > 24 hours"
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/cleanup/handle_cleanup_test.go
  pkg/database/authorized_app.go
  pkg/database/authorized_app_test.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: cla: yes

#2018 Update key server deps
  go.mod
  go.sum
Labels: cla: yes

#2019 Lower Cloud KMS database-encrypter rotation to 90d
  docs/production.md
  terraform/keys.tf
Labels: cla: yes

#2020 Introduce function for getting the e2e-realm (if one exists)
  pkg/controller/cleanup/handle_cleanup.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: cla: yes

#2022 Track API key "last used"
  assets/server/apikeys/index.html
  assets/server/apikeys/show.html
  go.mod
  go.sum
  pkg/config/feature_config.go
  pkg/controller/apikey/create_test.go
  pkg/controller/apikey/disable_test.go
  pkg/controller/apikey/enable_test.go
  pkg/controller/apikey/index_test.go
  pkg/controller/apikey/show_test.go
  pkg/controller/apikey/update_test.go
  pkg/controller/middleware/apikey.go
  pkg/database/authorized_app.go
  pkg/database/migrations.go
  pkg/render/renderer.go
Labels: cla: yes

#2023 Handle gorm log at debug level
  pkg/database/database_logger.go
  pkg/database/database_logger_test.go
Labels: cla: yes

#2025 Remove unused csrf token from Terraform
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_server.tf
  terraform/services.tf
  terraform/sessions.tf
Labels: cla: yes

#2024 Do not store firebase cookie and verify ID token is < 5min old
  assets/server/firebase.html
  internal/auth/firebase.go
Labels: cla: yes

#2026 Note that last_used_time has 15m granularity
  assets/server/apikeys/index.html
  assets/server/apikeys/show.html
Labels: cla: yes

#2027 Handle string or log in gorm log type
  pkg/database/database_logger.go
Labels: cla: yes

#2029 Use a wildcard for redirect domains
  terraform/redirect-lb.tf
Labels: cla: yes, kind/infrastructure

#2030 Remove beta notice from authenticated SMS guide
  docs/images/admin/authenticated-sms-create-version.png
  docs/images/admin/authenticated-sms-disabled.png
  docs/images/admin/authenticated-sms-enable.png
  docs/images/admin/authenticated-sms-enabled.png
  docs/images/admin/authenticated-sms-key-created.png
Labels: cla: yes

#2031 Add secret models and structure to info page
  assets/server/admin/info.html
  go.mod
  go.sum
  pkg/config/feature_config.go
  pkg/controller/admin/info.go
  pkg/controller/middleware/apikey_test.go
  pkg/database/migrations.go
  pkg/database/scopes.go
  pkg/database/secret.go
  pkg/database/secret_test.go
Labels: cla: yes

#2032 Extract key/secret bootstrapping into functions for seeding
  cmd/rotation/main.go
  pkg/config/rotation_config.go
  pkg/controller/rotation/handle_token_rotate.go
  pkg/controller/rotation/handle_token_rotate_test.go
  pkg/controller/rotation/handle_verification_rotate.go
  pkg/controller/rotation/handle_verification_rotate_test.go
  pkg/controller/rotation/metrics.go
  pkg/controller/rotation/rotation.go
  terraform/service_rotation.tf
  tools/seed/main.go
Labels: cla: yes

#2034 Add custom cookiestore codec
  pkg/cookiestore/codec.go
  pkg/cookiestore/cookiestore.go
Labels: cla: yes

#2033 Add secretresolver
  pkg/database/secretresolver.go
  pkg/database/secretresolver_test.go
Labels: cla: yes

#2036 Unescape mobile app paths in UI
  assets/server/mobileapps/show.html
  pkg/render/renderer.go
Labels: cla: yes

#2037 Do not run email verification js until after load
  assets/server/login/verify-email.html
Labels: cla: yes

#2038 Persist Firebase cookie for the session duration
  assets/server/firebase.html
Labels: cla: yes

#2035 Add rotation handlers
  pkg/config/rotation_config.go
  pkg/controller/rotation/handle_secrets_rotate.go
  pkg/controller/rotation/handle_secrets_rotate_test.go
  pkg/controller/rotation/rotation.go
  pkg/database/user_report_test.go
  terraform/alerting/alerts.tf
  terraform/service_rotation.tf
  terraform/services.tf
  terraform/sessions.tf
  tools/seed/main.go
Labels: cla: yes

#2041 Move ratelimit middleware after API key
  internal/routes/adminapi.go
Labels: cla: yes

#2040 add end to end runner for user-report test type
  cmd/e2e-runner/main.go
  cmd/e2e-runner/metrics.go
  internal/clients/e2e.go
  internal/envstest/bootstrap.go
  pkg/config/e2e_runner_server_config.go
  pkg/controller/issueapi/gen_code.go
  pkg/controller/issueapi/handle_issue.go
  pkg/database/user_report.go
  pkg/database/user_report_test.go
  pkg/database/vercode.go
  pkg/integration/enx_redirect_test.go
  terraform/alerting/alerts.tf
  terraform/service_e2e_runner.tf
  tools/get-code/main.go
Labels: cla: yes, kind/infrastructure

#2042 missing ID tag
  terraform/sessions.tf
Labels: cla: yes

#2043 add user report to default accept
  pkg/api/util.go
Labels: cla: yes

#2044 Fix permissions on rotation service
  terraform/service_rotation.tf
Labels: cla: yes

#2045 fix tests
  pkg/api/util_test.go
Labels: cla: yes

#2046 decreasing threshold for hostdown alert to improve alert times for DN…
  terraform/alerting/alerts.tf
Labels: cla: yes

#2039 Add automated secrets rotation
  cmd/rotation/main.go
  docs/development.md
  docs/production.md
  internal/envstest/enx_redirect.go
  internal/envstest/harness.go
  internal/envstest/server.go
  internal/project/context.go
  internal/routes/enx_redirect.go
  internal/routes/server.go
  pkg/config/redirect_config.go
  pkg/config/server_config.go
  pkg/controller/middleware/apikey_test.go
  pkg/controller/rotation/handle_secrets_rotate.go
  pkg/controller/rotation/handle_secrets_rotate_test.go
  pkg/cookiestore/codec.go
  pkg/database/authorized_app.go
  pkg/database/config.go
  pkg/database/database.go
  pkg/database/database_util.go
  pkg/database/secret.go
  pkg/database/secretresolver.go
  pkg/database/user_report.go
  pkg/database/vercode.go
  terraform/alerting/alerts.tf
  terraform/database.tf
  terraform/main.tf
  terraform/service_rotation.tf
  terraform/sessions.tf
Labels: cla: yes

#2048 make certificate NBF duration configurable
  pkg/config/certificate_signing_config.go
  pkg/controller/certapi/certificate.go
Labels: cla: yes

#2049 also apply clock skew to IAT
  pkg/controller/certapi/certificate.go
Labels: cla: yes

#2047 Timing
  assets/server/admin/realms/edit.html
  assets/server/realmadmin/_form_codes.html
  pkg/controller/admin/realms.go
  pkg/controller/admin/realms_test.go
  pkg/controller/realmadmin/express_disable_test.go
  pkg/controller/realmadmin/express_enable_test.go
  pkg/controller/realmadmin/settings_modify.go
  pkg/controller/realmadmin/settings_show.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_test.go
Labels: cla: yes, kind/enhancement

#2050 Check inactive secrets when comparing TTLs
  pkg/controller/rotation/handle_secrets_rotate.go
  pkg/controller/rotation/handle_secrets_rotate_test.go
Labels: cla: yes

#2052 Annotate why realm saving failed
  internal/envstest/bootstrap.go
Labels: cla: yes

#2053 Remove spaces after column definition
  internal/envstest/bootstrap.go
  pkg/database/realm.go
Labels: cla: yes

#2054 Fix syntax on envconfig
  pkg/config/rotation_config.go
Labels: cla: yes

#2055 Update deps
  go.mod
  go.sum
Labels: cla: yes

#2056 Display feature statuses on system admin info page
  assets/server/admin/info.html
  go.mod
  go.sum
  pkg/controller/admin/info.go
Labels: cla: yes, kind/enhancement

#2058 Bump key server dep
  go.mod
  go.sum
Labels: cla: yes

#2060 Enable viewing API key usage by default
  pkg/config/feature_config.go
Labels: cla: yes, kind/enhancement

#2063 user report improvements
  assets/enx-redirect/report/header.html
  assets/enx-redirect/report/index.html
  assets/server/realmadmin/_form_codes.html
  assets/server/realmadmin/_form_sms.html
  internal/clients/app_sync.go
  pkg/controller/appsync/handle_sync_test.go
  pkg/controller/appsync/helpers.go
  pkg/controller/appsync/helpers_test.go
  pkg/controller/userreport/index.go
  pkg/controller/userreport/send.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_test.go
  pkg/database/token_test.go
  pkg/integration/enx_redirect_test.go
Labels: cla: yes
