Repository google/exposure-notifications-verification-server, pull requests merged in 2021-03, with the labels that each got.

#1891 bump key server dep to v23
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/S

#1892 Also run all tests at least once a day
  .github/workflows/ci.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1895 Update and rename OWNERS to CODEOWNERS
  CODEOWNERS
  OWNERS
Labels: cla: yes

#1890 Add Indonesia (id) locale
  internal/i18n/locales/id/default.po
Labels: approved, cla: yes, do-not-merge/hold, lgtm, ok-to-test, size/L

#1897 Update and rename OWNERS to CODEOWNERS
  terraform/CODEOWNERS
  terraform/OWNERS
Labels: cla: yes

#1898 add new charts to realm admin guide
  docs/images/admin/stats.png
  docs/images/admin/stats01.png
  docs/images/admin/stats02.png
  docs/images/admin/stats03.png
  docs/images/admin/stats04.png
  docs/images/admin/stats05.png
  docs/images/admin/stats06.png
  docs/realm-admin-guide.md
Labels: cla: yes

#1902 Allow customizing log retention period
  terraform/main.tf
  terraform/variables.tf
Labels: cla: yes

#1903 Add chaff reporting
  assets/server/admin/realms/edit.html
  assets/server/admin/realms/index.html
  pkg/config/cleanup_server_config.go
  pkg/controller/admin/realms.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/cleanup/handle_cleanup_test.go
  pkg/controller/middleware/chaff.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_chaff_event.go
  pkg/database/realm_chaff_events_test.go
  pkg/database/realm_test.go
Labels: cla: yes

#1904 Add JSON tests for stats APIs
  pkg/controller/stats/composite.go
  pkg/database/authorized_app_stats_test.go
  pkg/database/composite_stats.go
  pkg/database/composite_stats_test.go
  pkg/database/external_issuer_stats_test.go
  pkg/database/realm_stats_test.go
  pkg/database/realm_user_stats_test.go
Labels: cla: yes

#1906 Next wave of status code changes
  pkg/controller/middleware/apikey_test.go
  pkg/controller/middleware/email_verified_test.go
  pkg/controller/middleware/firewall_test.go
  pkg/controller/middleware/header_test.go
  pkg/controller/middleware/membership_test.go
  pkg/controller/middleware/mfa_test.go
  pkg/controller/middleware/recovery_test.go
  pkg/render/json.go
  pkg/render/renderer.go
  pkg/sms/twilio.go
Labels: cla: yes

#1905 Retry and parallelize stats puller
  go.mod
  pkg/config/stats_puller_config.go
  pkg/controller/statspuller/handle_pull.go
Labels: cla: yes

#1907 Set alert interval to 10 mins
  terraform/alerting/alerts.tf
Labels: cla: yes

#1908 Adjust cron job schedule according to #1777
  terraform/service_appsync.tf
  terraform/service_modeler.tf
  terraform/service_rotation.tf
  terraform/service_stats_puller.tf
Labels: cla: yes

#1910 Only run Terraform checks once
  .github/workflows/terraform.yml
Labels: cla: yes

#1909 Set binauth annotation
  terraform/variables.tf
Labels: cla: yes

#1911 fix nil ptr in stats puller
  pkg/controller/statspuller/handle_pull.go
Labels: cla: yes, kind/bug

#1912 Make connect and drain timeout configuration
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: cla: yes

#1914 Revert "Make connect and drain timeout configuration"
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_server.tf
  terraform/variables.tf
Labels: cla: yes

#1917 Modeler is not a public-facing service
  terraform/service_modeler.tf
Labels: cla: yes

#1916 Improve service timeouts
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_rotation.tf
  terraform/service_server.tf
  terraform/service_stats_puller.tf
Labels: cla: yes

#1919 restrict redirects to allowed paths
  pkg/controller/login/reauth.go
  pkg/controller/login/reauth_test.go
Labels: cla: yes

#1920 Fix failing test
  pkg/controller/user/bulk_permisisons_test.go
Labels: cla: yes

#1921 bump keyserver dep version
  go.mod
  go.sum
Labels: cla: yes

#1922 Use an in-memory key server for end-to-end tests
  go.mod
  go.sum
  internal/clients/e2e.go
  internal/envstest/integration.go
  pkg/integration/integration_test.go
Labels: cla: yes

#1923 Use last column instead of 3 for coverage
  .github/workflows/ci.yaml
Labels: cla: yes

#1925 Lower in-memory cache time and return a warning about cached values
  pkg/controller/issueapi/controller.go
  pkg/controller/realmadmin/settings_modify.go
  pkg/database/database.go
Labels: cla: yes

#1926 Increment metric on success for background jobs
  pkg/controller/appsync/handle_sync.go
  pkg/controller/appsync/metrics.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/cleanup/metrics.go
  pkg/controller/modeler/metrics.go
  pkg/controller/modeler/modeler.go
  pkg/controller/rotation/handle_token_rotate.go
  pkg/controller/rotation/handle_verification_rotate.go
  pkg/controller/rotation/metrics.go
  pkg/controller/statspuller/handle_pull.go
  pkg/controller/statspuller/metrics.go
Labels: cla: yes

#1927 Rename CleanupStatus to LockStatus
  pkg/controller/modeler/modeler.go
  pkg/database/lock.go
  pkg/database/lock_test.go
  pkg/database/migrations.go
  pkg/database/modeler_status.go
  pkg/database/modeler_status_test.go
Labels: cla: yes

#1929 Switch to forward-progress alerting
  docs/playbooks/alerts/CloudSchedulerJobFailed.md
  docs/playbooks/alerts/ForwardProgressFailed.md
  pkg/controller/appsync/handle_sync.go
  pkg/controller/rotation/metrics.go
  terraform/alerting/alerts.tf
  terraform/alerting/variables.tf
  terraform/service_appsync.tf
  terraform/service_modeler.tf
  terraform/service_stats_puller.tf
Labels: cla: yes

#1931 Re-add name, remove playbooks test
  docs/playbooks/playbook_test.go
  terraform/alerting/alerts.tf
Labels: cla: yes

#1932 Use an intermediate proxy for backups
  builders/build.yaml
  builders/deploy.yaml
  builders/promote.yaml
  cmd/backup/main.go
  docs/playbooks/alerts/ForwardProgressFailed.md
  pkg/config/backup_config.go
  pkg/controller/backup/backup.go
  pkg/controller/backup/backup_test.go
  pkg/controller/backup/handle_backup.go
  pkg/controller/backup/handle_backup_test.go
  pkg/controller/backup/metrics.go
  terraform/alerting/variables.tf
  terraform/database.tf
  terraform/service_backup.tf
  terraform/services.tf
Labels: cla: yes

#1933 add DB_PHONE_HMAC_KEY to migrate
  scripts/migrate
Labels: cla: yes

#1934 fix migrate
  builders/migrate.yaml
Labels: cla: yes

#1935 Remove warnings about unused environment variables
  pkg/config/redirect_config.go
  pkg/config/server_config.go
  terraform/services.tf
Labels: cla: yes

#1937 add composite stats handler to adminapi server
  internal/routes/adminapi.go
Labels: cla: yes, kind/statistics

#1938 Address SA5011 static check findings
  .github/workflows/ci.yaml
  pkg/controller/issueapi/send_sms_test.go
  pkg/controller/user/create_test.go
Labels: cla: yes

#1939 Allow overriding default fp alerts
  terraform/alerting/alerts.tf
  terraform/alerting/variables.tf
Labels: cla: yes

#1940 Re-add delta aligner
  terraform/alerting/alerts.tf
Labels: cla: yes

#1942 fix static check error
  pkg/database/authorized_app_test.go
Labels: cla: yes

#1943 remove platform for user report API
  pkg/api/api.go
  pkg/controller/issueapi/handle_user_report_test.go
  tools/user-report/main.go
Labels: cla: yes

#1941 add self report charts
  assets/server/realmadmin/_form_codes.html
  assets/server/realmadmin/_stats_codes.html
  go.mod
  go.sum
  pkg/database/composite_stats.go
  pkg/database/composite_stats_test.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/realm_stats.go
  pkg/database/realm_stats_test.go
  pkg/database/token.go
  pkg/database/vercode.go
  tools/seed/main.go
Labels: cla: yes, kind/statistics

#1944 change restrictions on user report SMS template
  assets/server/realmadmin/_form_sms.html
  pkg/database/realm.go
Labels: cla: yes

#1945 add key revisions back to key server chart iff user report is enabled
  assets/server/realmadmin/_stats_keyserver.html
Labels: cla: yes, kind/statistics

#1946 Set alignment to 1m
  terraform/alerting/alerts.tf
Labels: cla: yes

#1947 add sliders to key server graphs
  assets/server/realmadmin/_stats_keyserver.html
Labels: cla: yes, kind/statistics

#1949 Switch to standard alerts away from MQL
  terraform/alerting/alerts.tf
  terraform/alerting/variables.tf
Labels: cla: yes

#1951 Add special "_all" key to apply to all service environments
  terraform/service_admin_apiserver.tf
  terraform/service_apiserver.tf
  terraform/service_appsync.tf
  terraform/service_backup.tf
  terraform/service_cleanup.tf
  terraform/service_e2e_runner.tf
  terraform/service_modeler.tf
  terraform/service_redirect.tf
  terraform/service_rotation.tf
  terraform/service_server.tf
  terraform/service_stats_puller.tf
  terraform/variables.tf
Labels: cla: yes

#1950 Simplify background job error handling
  go.sum
  pkg/controller/appsync/handle_sync.go
  pkg/controller/backup/handle_backup.go
  pkg/controller/cleanup/handle_cleanup.go
  pkg/controller/modeler/modeler.go
  pkg/controller/rotation/handle_token_rotate.go
  pkg/controller/rotation/handle_verification_rotate.go
  pkg/controller/statspuller/handle_pull.go
  pkg/render/json.go
Labels: cla: yes

#1952 Switch e2e-runner to forward progress alerting
  cmd/e2e-runner/main.go
  cmd/e2e-runner/metrics.go
  docs/playbooks/alerts/E2ETestErrorRatioHigh.md
  docs/playbooks/alerts/ForwardProgressFailed.md
  docs/playbooks/index.md
  terraform/alerting/alerts.tf
  terraform/service_e2e_runner.tf
Labels: cla: yes

#1953 Fix copy-pasta errors
  terraform/alerting/alerts.tf
Labels: cla: yes

#1954 Ensure users retain system admin when being added to a realm
  pkg/controller/user/create.go
  pkg/controller/user/create_test.go
Labels: cla: yes

#1956 add Mongolian translations
  internal/i18n/locales/mn/default.po
Labels: cla: yes

#1955 allow admin /api/issue to issue user-report codes
  assets/server/realmadmin/_form_codes.html
  pkg/controller/issueapi/handle_issue.go
  pkg/controller/issueapi/handle_user_report.go
  pkg/controller/issueapi/issue.go
  pkg/controller/issueapi/validate_code.go
  pkg/controller/issueapi/validate_code_test.go
  pkg/controller/realmadmin/settings_modify.go
  pkg/database/migrations.go
  pkg/database/realm.go
  pkg/database/token.go
  pkg/database/token_test.go
  pkg/database/user_report.go
  pkg/database/user_report_test.go
  pkg/database/vercode.go
  pkg/database/vercode_test.go
  tools/seed/main.go
Labels: cla: yes, kind/enhancement

#1957 bootstrap e2e runner on first run instead of startup
  cmd/e2e-runner/main.go
Labels: cla: yes

#1958 fix os chart stack + nil ptr
  assets/server/realmadmin/_stats_keyserver.html
  pkg/controller/stats/composite.go
Labels: cla: yes

#1959 Revert "bootstrap e2e runner on first run instead of startup (#1957)"
  cmd/e2e-runner/main.go
Labels: cla: yes, kind/infrastructure

#1960 Do not mark PhoneNumberHMAC as required
  pkg/database/config.go
  pkg/database/user_report.go
Labels: cla: yes

#1961 Remove XSS header
  pkg/controller/middleware/secure.go
Labels: cla: yes

#1962 Lower data-layer TTLs
  pkg/config/backup_config.go
  pkg/config/cleanup_server_config.go
  pkg/config/rotation_config.go
  pkg/config/stats_puller_config.go
Labels: cla: yes

#1965 fix env var
  pkg/config/cleanup_server_config.go
  terraform/service_cleanup.tf
Labels: cla: yes

#1964 Centralize X-Forwarded-For processing to get real client IPs
  pkg/controller/middleware/firewall.go
  pkg/controller/middleware/firewall_test.go
  pkg/ratelimit/limitware/middleware.go
  pkg/realip/realip.go
  pkg/realip/realip_test.go
Labels: cla: yes

#1966 Drop UPDATE privileges on audits table
  pkg/database/migrations.go
Labels: cla: yes

#1963 Move CSRF implementation into session
  assets/server/codes/issue.html
  assets/server/login/_loginscripts.html
  assets/server/login/register-phone.html
  assets/server/static/js/application.js
  assets/server/users/import.html
  docs/development.md
  docs/production.md
  go.mod
  go.sum
  internal/envstest/server.go
  internal/routes/server.go
  pkg/api/api.go
  pkg/config/server_config.go
  pkg/controller/middleware/csrf.go
  pkg/controller/middleware/csrf_test.go
  pkg/controller/session.go
  terraform/main.tf
  terraform/services.tf
  terraform/sessions.tf
Labels: cla: yes

#1967 Remove presubmit script
  scripts/presubmit.sh
Labels: cla: yes
